pre-release-commit-message = "chore: release contrix crates version {{version}}"
sign-tag = true
tag-message = "Release {{crate_name}} version {{version}}"
tag-name = "{{crate_name}}-v{{version}}"
shared-version = true
allow-branch = ["HEAD", "release-*"]
