// @generated by tools/generate-sdk-error-codes.ps1 from
// arkret-spec/spec/v1/artifacts/registry/error-code-registry.json; do not edit by hand.
//
// One constant per canonical reason_codes entry. These are subordinate reason
// values, not top-level service error codes.

pub const REASON_CAPABILITY_REGISTRY_BASIS_UNAVAILABLE: &str =
    "capability_registry_basis_unavailable";
pub const REASON_UNSUPPORTED_DIGEST_ALGORITHM: &str = "unsupported_digest_algorithm";
pub const REASON_OK: &str = "ok";
pub const REASON_APPROVAL_REQUIRED: &str = "approval_required";
pub const REASON_NO_STRAND_TRACK_MESSAGE_GRANT: &str = "no_strand_track_message_grant";
pub const REASON_GRANT_REVOKED_BEFORE_EVENT_FRONTIER: &str = "grant_revoked_before_event_frontier";
pub const REASON_REVOKE_ORDER_UNKNOWN_REQUIRES_BACKFILL_OR_REVIEW: &str =
    "revoke_order_unknown_requires_backfill_or_review";
pub const REASON_REVOCATION_FRESHNESS_UNKNOWN: &str = "revocation_freshness_unknown";
pub const REASON_REALM_ALREADY_EXISTS: &str = "realm_already_exists";
pub const REASON_REALM_FOUNDING_GRANT_MISSING: &str = "realm_founding_grant_missing";
pub const REASON_INVALID_REALM_FOUNDING_GRANT: &str = "invalid_realm_founding_grant";
pub const REASON_REALM_ORGANIZATION_AUTHORIZATION_INVALID: &str =
    "realm_organization_authorization_invalid";
pub const REASON_REALM_ORGANIZATION_DELEGATION_MISSING: &str =
    "realm_organization_delegation_missing";
pub const REASON_REALM_ORGANIZATION_EXPIRED: &str = "realm_organization_expired";
pub const REASON_REALM_ORGANIZATION_SCOPE_MISSING: &str = "realm_organization_scope_missing";
pub const REASON_REALM_ORGANIZATION_REALM_ACCEPTANCE_MISSING: &str =
    "realm_organization_realm_acceptance_missing";
pub const REASON_OUT_OF_ORDER_BOOTSTRAP: &str = "out_of_order_bootstrap";
pub const REASON_POLICY_REVISION_GAP: &str = "policy_revision_gap";
pub const REASON_MODERATION_CONTROL_LIFTED: &str = "moderation_control_lifted";
pub const REASON_MODERATION_CONTROL_PENDING: &str = "moderation_control_pending";
pub const REASON_MODERATION_CONTROL_SPLIT: &str = "moderation_control_split";
pub const REASON_DID_PROOF_REPLAY_WINDOW_EXCEEDED: &str = "did_proof_replay_window_exceeded";
pub const REASON_E2EE_RELAXED_FEDERATION_POLICY_UNSUPPORTED: &str =
    "e2ee_relaxed_federation_policy_unsupported";
pub const REASON_DEACTIVATION_FEDERATION_INCOMPLETE: &str = "deactivation_federation_incomplete";
pub const REASON_ERASURE_PENDING_IS_TERMINAL: &str = "erasure_pending_is_terminal";
pub const REASON_ACCOUNT_STATUS_TRANSITION_INVALID: &str = "account_status_transition_invalid";
pub const REASON_PUSH_ROUTE_LIMIT_EXCEEDED: &str = "push_route_limit_exceeded";
pub const REASON_PUSH_ROUTE_REGISTRATION_RATE_LIMITED: &str =
    "push_route_registration_rate_limited";
pub const REASON_SELECTOR_ACTOR_WILDCARD_FORBIDDEN: &str = "selector_actor_wildcard_forbidden";
pub const REASON_SERVICE_NOT_PLAINTEXT_VISIBLE: &str = "service_not_plaintext_visible";
pub const REASON_AUDIT_RECEIPT_INVALIDATED: &str = "audit_receipt_invalidated";
pub const REASON_DUPLICATE_CONFLICT: &str = "duplicate_conflict";
pub const REASON_MESSAGE_ID_CONFLICT: &str = "message_id_conflict";
pub const REASON_STATE_MISMATCH: &str = "state_mismatch";
pub const REASON_QUARANTINED: &str = "quarantined";
pub const REASON_PARTIAL_AUTH_STATE: &str = "partial_auth_state";
pub const REASON_AUTH_INCOMPLETE: &str = "auth_incomplete";
pub const REASON_PROJECTION_INCOMPLETE: &str = "projection_incomplete";
pub const REASON_DECRYPTION_PENDING: &str = "decryption_pending";
pub const REASON_DECRYPTION_FAILED: &str = "decryption_failed";
pub const REASON_UNSUPPORTED_FEATURE: &str = "unsupported_feature";
pub const REASON_UNSUPPORTED_EVENT_KIND: &str = "unsupported_event_kind";
pub const REASON_UNKNOWN_EVENT_KIND: &str = "unknown_event_kind";
pub const REASON_INVALID_CANONICAL_JSON: &str = "invalid_canonical_json";
pub const REASON_INVALID_ENCODING: &str = "invalid_encoding";
pub const REASON_STRUCTURE_DEPTH_EXCEEDED: &str = "structure_depth_exceeded";
pub const REASON_CBOR_BOUNDS_INVALID: &str = "cbor_bounds_invalid";
pub const REASON_CBOR_NOT_DETERMINISTIC: &str = "cbor_not_deterministic";
pub const REASON_INVALID_CURSOR: &str = "invalid_cursor";
pub const REASON_CURSOR_UNRECOGNIZED: &str = "cursor_unrecognized";
pub const REASON_CURSOR_EXPIRED: &str = "cursor_expired";
pub const REASON_CURSOR_INTEGRITY_INVALID: &str = "cursor_integrity_invalid";
pub const REASON_CURSOR_REVOKED: &str = "cursor_revoked";
pub const REASON_AUTHORIZED_GRANT_REVOKED: &str = "authorized_grant_revoked";
pub const REASON_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH: &str =
    "device_recovery_ssk_generation_mismatch";
pub const REASON_SPAM: &str = "spam";
pub const REASON_HARASSMENT: &str = "harassment";
pub const REASON_HATE_SPEECH: &str = "hate_speech";
pub const REASON_NSFW: &str = "nsfw";
pub const REASON_ILLEGAL: &str = "illegal";
pub const REASON_MISINFORMATION: &str = "misinformation";
pub const REASON_OTHER: &str = "other";
pub const REASON_ABUSE_CLUSTER: &str = "abuse_cluster";
pub const REASON_ABUSE_NETWORK: &str = "abuse_network";
pub const REASON_ABUSE_REVIEW: &str = "abuse_review";
pub const REASON_POLICY_RECALL: &str = "policy_recall";
pub const REASON_INCLUSION_PROOF_FAILED: &str = "inclusion_proof_failed";
pub const REASON_SNAPSHOT_ISSUER_REVOKED: &str = "snapshot_issuer_revoked";
pub const REASON_REDUCER_PROFILE_MISMATCH: &str = "reducer_profile_mismatch";
pub const REASON_FEDERATION_AUTHORITY_MISMATCH: &str = "federation_authority_mismatch";
pub const REASON_FEDERATION_TRUST_DOMAIN_MISMATCH: &str = "federation_trust_domain_mismatch";
pub const REASON_SELECTOR_TOO_COMPLEX: &str = "selector_too_complex";
pub const REASON_INCEPTION_UPGRADE_EVIDENCE_INSUFFICIENT: &str =
    "inception_upgrade_evidence_insufficient";
pub const REASON_INCEPTION_UPGRADE_SIGNATURE_CHAIN_INVALID: &str =
    "inception_upgrade_signature_chain_invalid";
pub const REASON_INCEPTION_UPGRADE_OLD_DOCUMENT_HASH_MISMATCH: &str =
    "inception_upgrade_old_document_hash_mismatch";
pub const REASON_INCEPTION_UPGRADE_FINGERPRINT_MISMATCH: &str =
    "inception_upgrade_fingerprint_mismatch";
pub const REASON_INCEPTION_KEY_WINDOW_EXCEEDED: &str = "inception_key_window_exceeded";
pub const REASON_AUDIT_RELEASE_BINDING_MISSING: &str = "audit_release_binding_missing";
pub const REASON_AUDIT_RELEASE_BINDING_INACTIVE: &str = "audit_release_binding_inactive";
pub const REASON_AUDIT_RELEASE_SCOPE_MISMATCH: &str = "audit_release_scope_mismatch";
pub const REASON_AUDIT_RELEASE_NOTICE_MISSING: &str = "audit_release_notice_missing";
pub const REASON_AUDIT_RELEASE_CURRENT_EPOCH_FORBIDDEN: &str =
    "audit_release_current_epoch_forbidden";
pub const REASON_AUDIT_RELEASE_RETROACTIVE_SCOPE_FORBIDDEN: &str =
    "audit_release_retroactive_scope_forbidden";
pub const REASON_AUDIT_RELEASE_MANIFEST_INVALID: &str = "audit_release_manifest_invalid";
pub const REASON_AUDIT_RELEASE_ATTESTATION_INVALID: &str = "audit_release_attestation_invalid";
pub const REASON_CARDINALITY_VIOLATION: &str = "cardinality_violation";
pub const REASON_CLAIM_FAILED: &str = "claim_failed";
pub const REASON_CONFLICTING_E2EE_PROFILES: &str = "conflicting_e2ee_profiles";
pub const REASON_MLS_SEND_PAUSE_ADVISORY_REQUIRES_E2EE_RELAXED_PROFILE: &str =
    "mls_send_pause_advisory_requires_e2ee_relaxed_profile";
pub const REASON_STRAND_NOT_ACTIVE: &str = "strand_not_active";
pub const REASON_STRAND_NOT_ARCHIVED: &str = "strand_not_archived";
pub const REASON_STRAND_ALREADY_TERMINAL: &str = "strand_already_terminal";
pub const REASON_SPACE_NOT_ACTIVE: &str = "space_not_active";
pub const REASON_SPACE_NOT_ARCHIVED: &str = "space_not_archived";
pub const REASON_SPACE_ALREADY_TERMINAL: &str = "space_already_terminal";
pub const REASON_SPACE_PARENT_CYCLE: &str = "space_parent_cycle";
pub const REASON_SPACE_PARENT_UNREADABLE: &str = "space_parent_unreadable";
pub const REASON_MORPH_NOT_ACTIVE: &str = "morph_not_active";
pub const REASON_MORPH_NOT_ARCHIVED: &str = "morph_not_archived";
pub const REASON_MORPH_ALREADY_TERMINAL: &str = "morph_already_terminal";
pub const REASON_MESSAGE_ALREADY_TERMINAL: &str = "message_already_terminal";
pub const REASON_RELATION_ALREADY_TERMINAL: &str = "relation_already_terminal";
pub const REASON_RELATION_PROFILE_CARDINALITY_CONFLICT: &str =
    "relation_profile_cardinality_conflict";
pub const REASON_RELATION_SCOPE_UNRESOLVED: &str = "relation_scope_unresolved";
pub const REASON_RELATION_CONFLICT_FANOUT_EXCEEDED: &str = "relation_conflict_fanout_exceeded";
pub const REASON_INVITE_ALREADY_TERMINAL: &str = "invite_already_terminal";
pub const REASON_CROSS_SIGNING_RESET: &str = "cross_signing_reset";
pub const REASON_CROSS_SIGNING_RESET_PROOF_AUTHORITY_INVALID: &str =
    "cross_signing_reset_proof_authority_invalid";
pub const REASON_CROSS_SIGNING_RESET_SIGNATURE_INVALID: &str =
    "cross_signing_reset_signature_invalid";
pub const REASON_CROSS_SIGNING_RESET_RECOVERY_SERVICE_ATTESTATION_DOMAIN_MISMATCH: &str =
    "cross_signing_reset_recovery_service_attestation_domain_mismatch";
pub const REASON_CROSS_SIGNING_RESET_GENERATION_MISMATCH: &str =
    "cross_signing_reset_generation_mismatch";
pub const REASON_CROSS_SIGNING_RESET_RECOVERY_REF_UNKNOWN: &str =
    "cross_signing_reset_recovery_ref_unknown";
pub const REASON_CROSS_SIGNING_RESET_UNLOCK_COMMITMENT_MISMATCH: &str =
    "cross_signing_reset_unlock_commitment_mismatch";
pub const REASON_CROSS_SIGNING_RESET_QUORUM_INSUFFICIENT: &str =
    "cross_signing_reset_quorum_insufficient";
pub const REASON_CROSS_SIGNING_RESET_QUORUM_BELOW_POLICY: &str =
    "cross_signing_reset_quorum_below_policy";
pub const REASON_CROSS_SIGNING_RESET_RECOVERY_SERVICE_UNKNOWN: &str =
    "cross_signing_reset_recovery_service_unknown";
pub const REASON_CROSS_SIGNING_RESET_ATTESTATION_MISSING: &str =
    "cross_signing_reset_attestation_missing";
pub const REASON_CROSS_SIGNING_RESET_CLOCK_SKEW_EXCEEDED: &str =
    "cross_signing_reset_clock_skew_exceeded";
pub const REASON_CROSS_SIGNING_RESET_REPLAYED: &str = "cross_signing_reset_replayed";
pub const REASON_UNSUPPORTED_SIGNATURE_ALG: &str = "unsupported_signature_alg";
pub const REASON_UNSUPPORTED_HPKE_SUITE: &str = "unsupported_hpke_suite";
pub const REASON_CLAIM_RATE_LIMITED: &str = "claim_rate_limited";
pub const REASON_NAMING_CONVENTION_VIOLATION: &str = "naming_convention_violation";
pub const REASON_APPROVAL_NONCE_REUSED: &str = "approval_nonce_reused";
pub const REASON_APPROVAL_ALREADY_CONSUMED: &str = "approval_already_consumed";
pub const REASON_EXECUTED_BY_MISSING: &str = "executed_by_missing";
pub const REASON_THIRD_PARTY_INVITE_TOKEN_IN_QUERY: &str = "third_party_invite_token_in_query";
pub const REASON_PATCH_PATH_INVALID: &str = "patch_path_invalid";
pub const REASON_PATCH_ATOMIC_CONFLICT: &str = "patch_atomic_conflict";
pub const REASON_PATCH_PATH_REDUCER_MANAGED: &str = "patch_path_reducer_managed";
pub const REASON_PATCH_UNSET_REDACTABLE_FIELD: &str = "patch_unset_redactable_field";
pub const REASON_PATCH_SELECTOR_NO_MATCH: &str = "patch_selector_no_match";
pub const REASON_PATCH_SELECTOR_AMBIGUOUS: &str = "patch_selector_ambiguous";
pub const REASON_AEAD_NONCE_COUNTER_REPLAY: &str = "aead_nonce_counter_replay";
pub const REASON_AEAD_NONCE_DERIVATION_INVALID: &str = "aead_nonce_derivation_invalid";
pub const REASON_AEAD_NONCE_SENDER_DOMAIN_COLLISION: &str = "aead_nonce_sender_domain_collision";
pub const REASON_ACCOUNTABILITY_GRANT_MISSING: &str = "accountability_grant_missing";
pub const REASON_FOCUS_MISMATCH: &str = "focus_mismatch";
pub const REASON_UNKNOWN_FOCUS_TYPE: &str = "unknown_focus_type";
pub const REASON_TOKEN_ISSUER_UNAUTHORISED: &str = "token_issuer_unauthorised";
pub const REASON_PARTICIPANT_BINDING_INVALID: &str = "participant_binding_invalid";
pub const REASON_PARTICIPANT_IDENTITY_UNRECOGNISED: &str = "participant_identity_unrecognised";
pub const REASON_SESSION_FOCUS_ALREADY_COMMITTED: &str = "session_focus_already_committed";
pub const REASON_CALL_STATE_TERMINAL: &str = "call_state_terminal";
pub const REASON_CALL_STATE_TRANSITION_INVALID: &str = "call_state_transition_invalid";
pub const REASON_RECORDING_STATE_TRANSITION_INVALID: &str = "recording_state_transition_invalid";
pub const REASON_E2EE_KEY_SOURCE_UNAUTHORISED: &str = "e2ee_key_source_unauthorised";
pub const REASON_RECORDING_ARTIFACT_PIPELINE_BYPASSED: &str =
    "recording_artifact_pipeline_bypassed";
pub const REASON_TRANSCRIPTION_DENIED: &str = "transcription_denied";
pub const REASON_TRANSCRIPTION_ARTIFACT_PIPELINE_BYPASSED: &str =
    "transcription_artifact_pipeline_bypassed";
pub const REASON_RECORDING_CONSENT_REQUIRED: &str = "recording_consent_required";
pub const REASON_CALL_MODERATION_UNAUTHORISED: &str = "call_moderation_unauthorised";
pub const REASON_CALL_PARTICIPANT_REMOVED: &str = "call_participant_removed";
pub const REASON_CALL_SUMMARY_INVALID: &str = "call_summary_invalid";
pub const REASON_MEDIA_SERVICE_FOCI_REQUIRED: &str = "media_service_foci_required";
pub const REASON_MEDIA_SERVICE_BINDING_UNCOVERED: &str = "media_service_binding_uncovered";
pub const REASON_FOCUS_UNAVAILABLE_FOR_CLIENT: &str = "focus_unavailable_for_client";
pub const REASON_SESSION_FOCUS_NO_SPLIT_BRAIN: &str = "session_focus_no_split_brain";
pub const REASON_TOKEN_EXPIRED: &str = "token_expired";
pub const REASON_VERIFICATION_METHOD_PRINCIPAL_MISMATCH: &str =
    "verification_method_principal_mismatch";
pub const REASON_AGENT_GRANT_EXPIRY_REQUIRED: &str = "agent_grant_expiry_required";
pub const REASON_AGENT_GRANT_CONSTRAINT_MISSING: &str = "agent_grant_constraint_missing";
pub const REASON_AGENT_KEY_AUTHORIZATION_EXPIRED: &str = "agent_key_authorization_expired";
pub const REASON_SUPERSEDED_BY_REPAIRING: &str = "superseded_by_repairing";
pub const REASON_PAIRING_EXPIRED: &str = "pairing_expired";
pub const REASON_PAIRING_REQUEST_EXPIRED: &str = "pairing_request_expired";
pub const REASON_PROOF_INVALID: &str = "proof_invalid";
pub const REASON_AGENT_PAUSED: &str = "agent_paused";
pub const REASON_AGENT_DEACTIVATED: &str = "agent_deactivated";
pub const REASON_KEYPACKAGE_WELCOME_ENVELOPE_MISMATCH: &str =
    "keypackage_welcome_envelope_mismatch";
pub const REASON_KEYPACKAGE_CLAIM_RATE_LIMITED: &str = "keypackage_claim_rate_limited";
pub const REASON_DELEGATION_CYCLE: &str = "delegation_cycle";
pub const REASON_DELEGATION_EXPIRY_WIDENING: &str = "delegation_expiry_widening";
pub const REASON_GRANT_EXCEEDS_ISSUER_AUTHORITY: &str = "grant_exceeds_issuer_authority";
pub const REASON_SUBDELEGATION_PROHIBITED: &str = "subdelegation_prohibited";
pub const REASON_SCOPE_EXPANSION_FORBIDDEN: &str = "scope_expansion_forbidden";
pub const REASON_DELEGATION_SCOPE_MISMATCH: &str = "delegation_scope_mismatch";
pub const REASON_DELEGATION_SCOPE_CUSTOM_UNSUPPORTED: &str = "delegation_scope_custom_unsupported";
pub const REASON_MISSING_PARENT_REFERENCE: &str = "missing_parent_reference";
pub const REASON_AGENT_PARTICIPATION_CEILING_UNRESOLVED: &str =
    "agent_participation_ceiling_unresolved";
pub const REASON_SPACE_PARENT_CHAIN_IN_BOTTOM_STATE: &str = "space_parent_chain_in_bottom_state";
pub const REASON_RECOVERY_WITNESS_MISSING: &str = "recovery_witness_missing";
pub const REASON_RECOVERY_WITNESS_INVALID: &str = "recovery_witness_invalid";
pub const REASON_RECOVERY_WITNESS_POST_CONFLICT: &str = "recovery_witness_post_conflict";
pub const REASON_RECOVERY_CAPABILITY_NOT_SEALED: &str = "recovery_capability_not_sealed";
pub const REASON_RECOVERY_WITNESS_REVOKE_LAGGING: &str = "recovery_witness_revoke_lagging";
pub const REASON_CHALLENGE_PROOF_INVALID: &str = "challenge_proof_invalid";
pub const REASON_GRANT_REVOKED_UPSTREAM: &str = "grant_revoked_upstream";
pub const REASON_GRANT_VALIDITY_WINDOW_EMPTY: &str = "grant_validity_window_empty";
pub const REASON_PRINCIPAL_DEACTIVATED: &str = "principal_deactivated";
pub const REASON_ACTOR_SIGNATURE_REVOKED: &str = "actor_signature_revoked";
pub const REASON_DELEGATION_REVOKED: &str = "delegation_revoked";
pub const REASON_RECIPIENT_UNAVAILABLE: &str = "recipient_unavailable";
pub const REASON_MODERATION_STATE_CONFLICT: &str = "moderation_state_conflict";
pub const REASON_WELCOME_CAPABILITY_MISMATCH: &str = "welcome_capability_mismatch";
pub const REASON_AUDIT_CAPABILITY_INCOMPLETE: &str = "audit_capability_incomplete";
pub const REASON_WATCH_MUST_BE_SELF: &str = "watch_must_be_self";
pub const REASON_WATCH_MUTED_MUST_BE_SELF: &str = "watch_muted_must_be_self";
pub const REASON_WATCH_LEVEL_PUBLIC_MUST_BE_SELF: &str = "watch_level_public_must_be_self";
pub const REASON_WATCH_SET_OTHERS_AUDIT_MISSING: &str = "watch_set_others_audit_missing";
pub const REASON_CROSS_REALM_STRUCTURAL_RELATION: &str = "cross_realm_structural_relation";
pub const REASON_JOIN_AUTHORISATION_INVALID: &str = "join_authorisation_invalid";
pub const REASON_JOIN_RULE_POLICY_MISMATCH: &str = "join_rule_policy_mismatch";
pub const REASON_QUORUM_UNREACHABLE: &str = "quorum_unreachable";
pub const REASON_JOIN_RULE_TIGHTENED: &str = "join_rule_tightened";
pub const REASON_DELIVERY_BINDING_INVALID: &str = "delivery_binding_invalid";
pub const REASON_DELIVERY_BINDING_POLICY_MISMATCH: &str = "delivery_binding_policy_mismatch";
pub const REASON_PRINCIPAL_CONTROL_EVENT_KIND_FORBIDDEN: &str =
    "principal_control_event_kind_forbidden";
pub const REASON_EPOCH_UPDATE_REQUIRED: &str = "epoch_update_required";
pub const REASON_CLAIM_GENERATION_MISMATCH: &str = "claim_generation_mismatch";
pub const REASON_KEYPACKAGE_REFRESH_REQUIRED: &str = "keypackage_refresh_required";
pub const REASON_PRESIGN_INVALID: &str = "presign_invalid";
pub const REASON_PRESIGN_EXPIRED: &str = "presign_expired";
pub const REASON_PRESIGN_SCOPE_MISMATCH: &str = "presign_scope_mismatch";
pub const REASON_PRIVATE_ATTACHMENT: &str = "private_attachment";
pub const REASON_POLICY_DENIED: &str = "policy_denied";
pub const REASON_AUDIENCE_MISMATCH: &str = "audience_mismatch";
pub const REASON_HANDLE_SUBJECT_MISMATCH: &str = "handle_subject_mismatch";
pub const REASON_HANDLE_HOLDER_ACCEPTANCE_MISSING: &str = "handle_holder_acceptance_missing";
pub const REASON_HANDLE_HOMOGRAPH_FORBIDDEN: &str = "handle_homograph_forbidden";
pub const REASON_REALM_ALIAS_HOMOGRAPH_FORBIDDEN: &str = "realm_alias_homograph_forbidden";
pub const REASON_CIRCLE_SHORT_NAME_TAKEN: &str = "circle_short_name_taken";
pub const REASON_SIDECAR_CREATE_DENIED: &str = "sidecar_create_denied";
pub const REASON_SIDECAR_EXPOSURE_ACK_REQUIRED: &str = "sidecar_exposure_ack_required";
pub const REASON_WEBVH_CACHE_TOO_STALE: &str = "webvh_cache_too_stale";
pub const REASON_DELIVERY_BINDING_HANDOVER_PROOF_INVALID: &str =
    "delivery_binding_handover_proof_invalid";
pub const REASON_DELIVERY_BINDING_HANDOVER_RATE_LIMITED: &str =
    "delivery_binding_handover_rate_limited";
pub const REASON_SOFT_FAILED: &str = "soft_failed";
pub const REASON_SPACE_HAS_LIVE_DEPENDENTS: &str = "space_has_live_dependents";
pub const REASON_TTL_EXPIRED: &str = "ttl_expired";
pub const REASON_CHALLENGE_FAILED: &str = "challenge_failed";
pub const REASON_CHALLENGE_EXPIRED: &str = "challenge_expired";
pub const REASON_CLAIM_INVALID: &str = "claim_invalid";
pub const REASON_NOT_PROVISIONED: &str = "not_provisioned";
pub const REASON_MORPH_SCHEMA_REFS_EVOLUTION_UNAUTHORIZED: &str =
    "morph_schema_refs_evolution_unauthorized";
pub const REASON_MORPH_SCHEMA_REFS_TRANSFORMATION_UNSUPPORTED: &str =
    "morph_schema_refs_transformation_unsupported";
pub const REASON_MORPH_SCHEMA_VERSION_BINDING_MISSING: &str =
    "morph_schema_version_binding_missing";
pub const REASON_RANGE_COMPLETENESS_ROOT_MISMATCH: &str = "range_completeness_root_mismatch";
pub const REASON_RANGE_COMPLETENESS_ACTOR_SEQ_GAP: &str = "range_completeness_actor_seq_gap";
pub const REASON_WITNESS_DISAGREEMENT: &str = "witness_disagreement";
pub const REASON_RELAXED_WINDOW_EXCEEDS_CEILING: &str = "relaxed_window_exceeds_ceiling";
pub const REASON_E2EE_RELAXED_DISALLOWED_IN_COMPLIANCE_PROFILE: &str =
    "e2ee_relaxed_disallowed_in_compliance_profile";
pub const REASON_CROSS_DOMAIN_REPLAY_REJECTED: &str = "cross_domain_replay_rejected";
pub const REASON_RESET_EVENT_ID_MISMATCH: &str = "reset_event_id_mismatch";
pub const REASON_APPEAL_OVERTURN_MISSING_LIFT: &str = "appeal_overturn_missing_lift";
pub const REASON_APPEAL_MODIFY_MISSING_LIFT: &str = "appeal_modify_missing_lift";
pub const REASON_APPEAL_SELF_REVIEW_FORBIDDEN: &str = "appeal_self_review_forbidden";
pub const REASON_REALM_TERMINAL_STATE: &str = "realm_terminal_state";
pub const REASON_AUDIT_RELEASE_ATTESTATION_MISMATCH: &str = "audit_release_attestation_mismatch";
pub const REASON_AUDIT_PURPOSE_MISMATCH: &str = "audit_purpose_mismatch";
pub const REASON_LEGAL_HOLD_ACTIVE: &str = "legal_hold_active";
pub const REASON_BLOB_REDACTED: &str = "blob_redacted";
pub const REASON_MEDIA_PLAINTEXT_SERVICE_NOT_AUTHORISED: &str =
    "media_plaintext_service_not_authorised";
pub const REASON_MEDIA_PLAINTEXT_WARNING_REQUIRED: &str = "media_plaintext_warning_required";
pub const REASON_MLS_GOVERNANCE_BINDING_STALE: &str = "mls_governance_binding_stale";
pub const REASON_MIMI_GOVERNANCE_BINDING_MISSING: &str = "mimi_governance_binding_missing";
pub const REASON_MIMI_GOVERNANCE_BINDING_MISMATCH: &str = "mimi_governance_binding_mismatch";
pub const REASON_MIMI_POLICY_ROOT_MISMATCH: &str = "mimi_policy_root_mismatch";
pub const REASON_MIMI_ROOM_STATE_INCOMPATIBLE: &str = "mimi_room_state_incompatible";
pub const REASON_MIMI_PROVIDER_UNREACHABLE: &str = "mimi_provider_unreachable";
pub const REASON_MIMI_DRAFT_UNSUPPORTED: &str = "mimi_draft_unsupported";
pub const REASON_MIMI_ROOM_BINDING_STATUS_TRANSITION_INVALID: &str =
    "mimi_room_binding_status_transition_invalid";
pub const REASON_EXPIRED_INVITE_TOKEN: &str = "expired_invite_token";
pub const REASON_INVALID_ACK_TOKEN: &str = "invalid_ack_token";
pub const REASON_LATE_RECOVERY_REJECTED_MEMBERSHIP: &str = "late_recovery_rejected_membership";
pub const REASON_LATE_RECOVERY_SHARE_NOT_AUTHORIZED: &str = "late_recovery_share_not_authorized";
pub const REASON_LATE_RECOVERY_REJECTED_EXPIRED: &str = "late_recovery_rejected_expired";
pub const REASON_SEND_FAILED: &str = "send_failed";
pub const REASON_PREV_REFS_TOO_LARGE: &str = "prev_refs_too_large";
pub const REASON_CAUSAL_REFS_TOO_LARGE: &str = "causal_refs_too_large";
pub const REASON_REFS_TOO_LARGE: &str = "refs_too_large";
pub const REASON_DEVICE_AUTHORIZED_PRINCIPAL_CONTROL_REALM_MISMATCH: &str =
    "device_authorized_principal_control_realm_mismatch";
pub const REASON_DEVICE_ENROLLMENT_AUTHORITY_SNAPSHOT_MISSING: &str =
    "device_enrollment_authority_snapshot_missing";
pub const REASON_CELL_IN_BOTTOM_STATE: &str = "cell_in_bottom_state";
pub const REASON_INCEPTION_UPGRADE_EVIDENCE_STALE: &str = "inception_upgrade_evidence_stale";
pub const REASON_GATE_CHECK_FAILED: &str = "gate_check_failed";
pub const REASON_REALM_UNAVAILABLE: &str = "realm_unavailable";
pub const REASON_JOIN_POLICY_DUPLICATE_GATE_ID: &str = "join_policy_duplicate_gate_id";
pub const REASON_CIRCLE_REALM_MISMATCH: &str = "circle_realm_mismatch";
pub const REASON_CIRCLE_NOT_ACTIVE: &str = "circle_not_active";
pub const REASON_CIRCLE_NOT_ARCHIVED: &str = "circle_not_archived";
pub const REASON_CIRCLE_ALREADY_TERMINAL: &str = "circle_already_terminal";
pub const REASON_SCOPE_UNAVAILABLE: &str = "scope_unavailable";
pub const REASON_SCOPE_INCOMPARABLE: &str = "scope_incomparable";
pub const REASON_CIRCLE_MEMBER_MUST_BE_REALM_MEMBER: &str = "circle_member_must_be_realm_member";
pub const REASON_CIRCLE_COUNT_EXCEEDED: &str = "circle_count_exceeded";
pub const REASON_CIRCLE_ENCRYPTION_BELOW_REALM_FLOOR: &str = "circle_encryption_below_realm_floor";
pub const REASON_CONTENT_ENCRYPTION_FLOOR_VIOLATION: &str = "content_encryption_floor_violation";
pub const REASON_CONTENT_ENCRYPTION_FLOOR_DOWNGRADE: &str = "content_encryption_floor_downgrade";
pub const REASON_DURABILITY_SCHEME_INCOMPATIBLE: &str = "durability_scheme_incompatible";
pub const REASON_HISTORY_VISIBILITY_REQUIRES_HISTORY_CAPABLE_SCHEME: &str =
    "history_visibility_requires_history_capable_scheme";
pub const REASON_DURABILITY_RECOVERY_RECIPIENT_UNVERIFIED: &str =
    "durability_recovery_recipient_unverified";
pub const REASON_DURABILITY_SEAL_MISSING_BEFORE_GC: &str = "durability_seal_missing_before_gc";
pub const REASON_METADATA_ENCRYPTION_FLOOR_DOWNGRADE: &str = "metadata_encryption_floor_downgrade";
pub const REASON_SCOPE_REBIND_FORBIDDEN: &str = "scope_rebind_forbidden";
pub const REASON_AGENT_PARTICIPATION_CEILING_WIDEN: &str = "agent_participation_ceiling_widen";
pub const REASON_AGENT_PARTICIPATION_EXCEEDS_CEILING: &str = "agent_participation_exceeds_ceiling";
pub const REASON_AGENT_REPLY_NOT_PERMITTED: &str = "agent_reply_not_permitted";
pub const REASON_EFFECTIVE_SCOPE_REDUCER_MANAGED: &str = "effective_scope_reducer_managed";
pub const REASON_ACTOR_KIND_REDUCER_MANAGED: &str = "actor_kind_reducer_managed";
pub const REASON_METADATA_ENCRYPTION_FLOOR_VIOLATION: &str = "metadata_encryption_floor_violation";
pub const REASON_SERIES_CHAIN_BROKEN: &str = "series_chain_broken";
pub const REASON_SERIES_SEQ_NOT_MONOTONIC: &str = "series_seq_not_monotonic";
pub const REASON_SERIES_PREDECESSOR_NOT_FOUND: &str = "series_predecessor_not_found";
pub const REASON_RECOVERY_POLICY_MISMATCH: &str = "recovery_policy_mismatch";
pub const REASON_RECOVERY_POLICY_VERSION_NOT_MONOTONIC: &str =
    "recovery_policy_version_not_monotonic";
pub const REASON_RECOVERY_POLICY_SUPERSEDES_INVALID: &str = "recovery_policy_supersedes_invalid";
pub const REASON_RECOVERY_POLICY_GENESIS_NOT_V1: &str = "recovery_policy_genesis_not_v1";
pub const REASON_RECOVERY_PRINCIPAL_ISOLATION: &str = "recovery_principal_isolation";
pub const REASON_RECOVERY_PROOF_KIND_UNKNOWN: &str = "recovery_proof_kind_unknown";
pub const REASON_RECOVERY_SESSION_CHALLENGE_MISMATCH: &str = "recovery_session_challenge_mismatch";
pub const REASON_RECOVERY_SESSION_TERMINAL: &str = "recovery_session_terminal";
pub const REASON_PROOF_FAILED: &str = "proof_failed";
pub const REASON_OPERATOR_REJECTED: &str = "operator_rejected";
pub const REASON_RISK_POLICY: &str = "risk_policy";
pub const REASON_SUPERSEDED: &str = "superseded";
pub const REASON_COUNTER_BOUND_EXCEEDED: &str = "counter_bound_exceeded";
pub const REASON_INVALID_MEMBERSHIP_TRANSITION: &str = "invalid_membership_transition";
pub const REASON_CONTROLLER_MEMBERSHIP_ENDED: &str = "controller_membership_ended";
pub const REASON_SHARE_COMMITMENT_MISMATCH: &str = "share_commitment_mismatch";
pub const REASON_BACKUP_FRONTIER_STALE: &str = "backup_frontier_stale";
pub const REASON_BACKUP_POST_RESET_STALE: &str = "backup_post_reset_stale";
pub const REASON_STALE_BACKUP_TRUST_GENERATION: &str = "stale_backup_trust_generation";
pub const REASON_UNTRUSTED_BACKUP_SIGNATURE: &str = "untrusted_backup_signature";
pub const REASON_KEY_BACKUP_WIRE_SCHEMA_REQUIRED: &str = "key_backup_wire_schema_required";
pub const REASON_RECOVERY_EVIDENCE_UNBOUND: &str = "recovery_evidence_unbound";
pub const REASON_UNSUPPORTED_AEAD_PROFILE: &str = "unsupported_aead_profile";
pub const REASON_ATTESTATION_MISSING: &str = "attestation_missing";
pub const REASON_SELECTOR_GOVERNANCE_WILDCARD_FORBIDDEN: &str =
    "selector_governance_wildcard_forbidden";
pub const REASON_DIRECT_DOWNLOAD_DISALLOWED_PRESIGN_FORBIDDEN: &str =
    "direct_download_disallowed_presign_forbidden";
pub const REASON_MINIMAL_METADATA_PRESIGN_FORBIDDEN: &str = "minimal_metadata_presign_forbidden";
pub const REASON_READ_RECEIPT_VISIBILITY_COMBINATION_INVALID: &str =
    "read_receipt_visibility_combination_invalid";
pub const REASON_EGRESS_POLICY_DENIED: &str = "egress_policy_denied";
pub const REASON_ERASURE_RECEIPT_STUB_DIGEST_MISMATCH: &str =
    "erasure_receipt_stub_digest_mismatch";
pub const REASON_WEBVH_CACHE_UNAVAILABLE: &str = "webvh_cache_unavailable";
pub const REASON_UNSUPPORTED_ATTACHMENT_SCHEME: &str = "unsupported_attachment_scheme";
pub const REASON_SEGMENT_SEQUENCE_INVALID: &str = "segment_sequence_invalid";
pub const REASON_SEGMENT_AEAD_FAILED: &str = "segment_aead_failed";
pub const REASON_SEGMENT_STREAM_TRUNCATED: &str = "segment_stream_truncated";
pub const REASON_SEGMENT_REPLAY: &str = "segment_replay";
pub const REASON_SEGMENT_BOUNDS_INVALID: &str = "segment_bounds_invalid";
pub const REASON_LAST_RESORT_NOT_SUPPORTED: &str = "last_resort_not_supported";
pub const REASON_LAST_RESORT_REALM_AFFINITY_VIOLATION: &str =
    "last_resort_realm_affinity_violation";
pub const REASON_LAST_RESORT_ROTATION_REQUIRED: &str = "last_resort_rotation_required";
pub const REASON_INCLUSION_LIST_VIOLATION: &str = "inclusion_list_violation";
pub const REASON_DELTA_CONTAINS_DATA_EVENT: &str = "delta_contains_data_event";
pub const REASON_COVERED_SET_MISMATCH: &str = "covered_set_mismatch";
pub const REASON_FORENSIC_ATTRIBUTION_MISMATCH: &str = "forensic_attribution_mismatch";
pub const REASON_INSUFFICIENT_CHALLENGE_SAMPLES: &str = "insufficient_challenge_samples";
pub const REASON_MINIMAL_DISCLOSURE_VIOLATION: &str = "minimal_disclosure_violation";
pub const REASON_EVIDENCE_RECIPIENT_MISMATCH: &str = "evidence_recipient_mismatch";
pub const REASON_REVOKE_UNDO_INVALID_SIGNATURE: &str = "revoke_undo_invalid_signature";
pub const REASON_REACTION_TARGET_UNSUPPORTED: &str = "reaction_target_unsupported";
pub const REASON_REACTION_SCOPE_MISMATCH: &str = "reaction_scope_mismatch";
pub const REASON_EXTERNAL_RATE_LIMITED: &str = "external_rate_limited";
pub const REASON_APPLET_NAMESPACE_MISMATCH: &str = "applet_namespace_mismatch";
pub const REASON_PROOF_BINDING_MISSING: &str = "proof_binding_missing";
pub const REASON_SCHEMA_DERIVATION_MISMATCH: &str = "schema_derivation_mismatch";
pub const REASON_MORPH_SCHEMA_REFS_PRECONDITION_MISMATCH: &str =
    "morph_schema_refs_precondition_mismatch";
pub const REASON_UNKNOWN_KIND: &str = "unknown_kind";
pub const REASON_UNKNOWN_FIELD: &str = "unknown_field";
pub const REASON_READ_RECEIPT_FORCED_PUBLIC_WORLD_READABLE_FORBIDDEN: &str =
    "read_receipt_forced_public_world_readable_forbidden";
pub const REASON_MIMI_OBSERVER_WRITE_FORBIDDEN: &str = "mimi_observer_write_forbidden";
pub const REASON_PLANE_CROSS_WRITE: &str = "plane_cross_write";
pub const REASON_RELATION_KIND_WATCHES_DERIVED: &str = "relation_kind_watches_derived";
pub const REASON_RELATION_KIND_CONTAINS_DERIVED: &str = "relation_kind_contains_derived";
pub const REASON_INVALID_TASK_FSM_TRANSITION: &str = "invalid_task_fsm_transition";
pub const REASON_AUDIT_AGENT_KEY_DESTRUCTION_ATTESTATION_MISSING: &str =
    "audit_agent_key_destruction_attestation_missing";
pub const REASON_AUDIT_AGENT_REMOVE_REQUIRES_PAIRED_DESTRUCTION_ATTESTATION: &str =
    "audit_agent_remove_requires_paired_destruction_attestation";
pub const REASON_AUDIT_AGENT_DESTRUCTION_NOT_PAIRED_WITH_REMOVE: &str =
    "audit_agent_destruction_not_paired_with_remove";
pub const REASON_AUDIT_AGENT_DESTRUCTION_PROOF_NOT_ENCLAVE_SIGNED: &str =
    "audit_agent_destruction_proof_not_enclave_signed";
pub const REASON_AUDIT_AGENT_EPOCH_RANGE_INCOMPLETE: &str = "audit_agent_epoch_range_incomplete";
pub const REASON_AUDIT_AGENT_ATTESTATION_MISMATCH: &str = "audit_agent_attestation_mismatch";
pub const REASON_LITE_PROFILE_WRITES_DISALLOWED_EVENT_KIND: &str =
    "lite_profile_writes_disallowed_event_kind";
pub const REASON_CROSS_SPACE_STRUCTURAL_RELATION: &str = "cross_space_structural_relation";
pub const REASON_GOVERNANCE_BINDING_MISMATCH: &str = "governance_binding_mismatch";
pub const REASON_MEMBER_IDENTITY_PROOF_INVALID: &str = "member_identity_proof_invalid";
pub const REASON_MEMBER_IDENTITY_REPLACEMENT_DIGEST_MISMATCH: &str =
    "member_identity_replacement_digest_mismatch";
pub const REASON_MEMBER_IDENTITY_STATE_MISMATCH: &str = "member_identity_state_mismatch";
pub const REASON_MEMBER_IDENTITY_UNKNOWN_SEGMENT: &str = "member_identity_unknown_segment";
pub const REASON_QUEUE_FULL: &str = "queue_full";
pub const REASON_INTERNAL_ERROR: &str = "internal_error";
pub const REASON_SERVICE_KEY_REVOKED: &str = "service_key_revoked";
pub const REASON_CONSENT_REVOKED: &str = "consent_revoked";
pub const REASON_IDENTITY_LINK_NO_LONGER_VISIBLE: &str = "identity_link_no_longer_visible";
pub const REASON_IDENTITY_LINK_POLICY_TIGHTENED: &str = "identity_link_policy_tightened";
pub const REASON_INVALIDATED_BY_RATE_LIMIT: &str = "invalidated_by_rate_limit";
pub const REASON_INVITE_OOB_ENTROPY_TOO_LOW: &str = "invite_oob_entropy_too_low";
pub const REASON_REALM_LINK_SELF_REFERENCE: &str = "realm_link_self_reference";
pub const REASON_REALM_LINK_INVALID_TRANSITION: &str = "realm_link_invalid_transition";
pub const REASON_HUMAN_APPROVAL_REQUIRED: &str = "human_approval_required";
pub const REASON_MINIMAL_METADATA_AUTHOR_CREDENTIAL_INVALID: &str =
    "minimal_metadata_author_credential_invalid";

/// Canonical subordinate reason codes from error-code-registry.json, in registry order.
pub const KNOWN_REASON_CODES: &[&str] = &[
    REASON_CAPABILITY_REGISTRY_BASIS_UNAVAILABLE,
    REASON_UNSUPPORTED_DIGEST_ALGORITHM,
    REASON_OK,
    REASON_APPROVAL_REQUIRED,
    REASON_NO_STRAND_TRACK_MESSAGE_GRANT,
    REASON_GRANT_REVOKED_BEFORE_EVENT_FRONTIER,
    REASON_REVOKE_ORDER_UNKNOWN_REQUIRES_BACKFILL_OR_REVIEW,
    REASON_REVOCATION_FRESHNESS_UNKNOWN,
    REASON_REALM_ALREADY_EXISTS,
    REASON_REALM_FOUNDING_GRANT_MISSING,
    REASON_INVALID_REALM_FOUNDING_GRANT,
    REASON_REALM_ORGANIZATION_AUTHORIZATION_INVALID,
    REASON_REALM_ORGANIZATION_DELEGATION_MISSING,
    REASON_REALM_ORGANIZATION_EXPIRED,
    REASON_REALM_ORGANIZATION_SCOPE_MISSING,
    REASON_REALM_ORGANIZATION_REALM_ACCEPTANCE_MISSING,
    REASON_OUT_OF_ORDER_BOOTSTRAP,
    REASON_POLICY_REVISION_GAP,
    REASON_MODERATION_CONTROL_LIFTED,
    REASON_MODERATION_CONTROL_PENDING,
    REASON_MODERATION_CONTROL_SPLIT,
    REASON_DID_PROOF_REPLAY_WINDOW_EXCEEDED,
    REASON_E2EE_RELAXED_FEDERATION_POLICY_UNSUPPORTED,
    REASON_DEACTIVATION_FEDERATION_INCOMPLETE,
    REASON_ERASURE_PENDING_IS_TERMINAL,
    REASON_ACCOUNT_STATUS_TRANSITION_INVALID,
    REASON_PUSH_ROUTE_LIMIT_EXCEEDED,
    REASON_PUSH_ROUTE_REGISTRATION_RATE_LIMITED,
    REASON_SELECTOR_ACTOR_WILDCARD_FORBIDDEN,
    REASON_SERVICE_NOT_PLAINTEXT_VISIBLE,
    REASON_AUDIT_RECEIPT_INVALIDATED,
    REASON_DUPLICATE_CONFLICT,
    REASON_MESSAGE_ID_CONFLICT,
    REASON_STATE_MISMATCH,
    REASON_QUARANTINED,
    REASON_PARTIAL_AUTH_STATE,
    REASON_AUTH_INCOMPLETE,
    REASON_PROJECTION_INCOMPLETE,
    REASON_DECRYPTION_PENDING,
    REASON_DECRYPTION_FAILED,
    REASON_UNSUPPORTED_FEATURE,
    REASON_UNSUPPORTED_EVENT_KIND,
    REASON_UNKNOWN_EVENT_KIND,
    REASON_INVALID_CANONICAL_JSON,
    REASON_INVALID_ENCODING,
    REASON_STRUCTURE_DEPTH_EXCEEDED,
    REASON_CBOR_BOUNDS_INVALID,
    REASON_CBOR_NOT_DETERMINISTIC,
    REASON_INVALID_CURSOR,
    REASON_CURSOR_UNRECOGNIZED,
    REASON_CURSOR_EXPIRED,
    REASON_CURSOR_INTEGRITY_INVALID,
    REASON_CURSOR_REVOKED,
    REASON_AUTHORIZED_GRANT_REVOKED,
    REASON_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH,
    REASON_SPAM,
    REASON_HARASSMENT,
    REASON_HATE_SPEECH,
    REASON_NSFW,
    REASON_ILLEGAL,
    REASON_MISINFORMATION,
    REASON_OTHER,
    REASON_ABUSE_CLUSTER,
    REASON_ABUSE_NETWORK,
    REASON_ABUSE_REVIEW,
    REASON_POLICY_RECALL,
    REASON_INCLUSION_PROOF_FAILED,
    REASON_SNAPSHOT_ISSUER_REVOKED,
    REASON_REDUCER_PROFILE_MISMATCH,
    REASON_FEDERATION_AUTHORITY_MISMATCH,
    REASON_FEDERATION_TRUST_DOMAIN_MISMATCH,
    REASON_SELECTOR_TOO_COMPLEX,
    REASON_INCEPTION_UPGRADE_EVIDENCE_INSUFFICIENT,
    REASON_INCEPTION_UPGRADE_SIGNATURE_CHAIN_INVALID,
    REASON_INCEPTION_UPGRADE_OLD_DOCUMENT_HASH_MISMATCH,
    REASON_INCEPTION_UPGRADE_FINGERPRINT_MISMATCH,
    REASON_INCEPTION_KEY_WINDOW_EXCEEDED,
    REASON_AUDIT_RELEASE_BINDING_MISSING,
    REASON_AUDIT_RELEASE_BINDING_INACTIVE,
    REASON_AUDIT_RELEASE_SCOPE_MISMATCH,
    REASON_AUDIT_RELEASE_NOTICE_MISSING,
    REASON_AUDIT_RELEASE_CURRENT_EPOCH_FORBIDDEN,
    REASON_AUDIT_RELEASE_RETROACTIVE_SCOPE_FORBIDDEN,
    REASON_AUDIT_RELEASE_MANIFEST_INVALID,
    REASON_AUDIT_RELEASE_ATTESTATION_INVALID,
    REASON_CARDINALITY_VIOLATION,
    REASON_CLAIM_FAILED,
    REASON_CONFLICTING_E2EE_PROFILES,
    REASON_MLS_SEND_PAUSE_ADVISORY_REQUIRES_E2EE_RELAXED_PROFILE,
    REASON_STRAND_NOT_ACTIVE,
    REASON_STRAND_NOT_ARCHIVED,
    REASON_STRAND_ALREADY_TERMINAL,
    REASON_SPACE_NOT_ACTIVE,
    REASON_SPACE_NOT_ARCHIVED,
    REASON_SPACE_ALREADY_TERMINAL,
    REASON_SPACE_PARENT_CYCLE,
    REASON_SPACE_PARENT_UNREADABLE,
    REASON_MORPH_NOT_ACTIVE,
    REASON_MORPH_NOT_ARCHIVED,
    REASON_MORPH_ALREADY_TERMINAL,
    REASON_MESSAGE_ALREADY_TERMINAL,
    REASON_RELATION_ALREADY_TERMINAL,
    REASON_RELATION_PROFILE_CARDINALITY_CONFLICT,
    REASON_RELATION_SCOPE_UNRESOLVED,
    REASON_RELATION_CONFLICT_FANOUT_EXCEEDED,
    REASON_INVITE_ALREADY_TERMINAL,
    REASON_CROSS_SIGNING_RESET,
    REASON_CROSS_SIGNING_RESET_PROOF_AUTHORITY_INVALID,
    REASON_CROSS_SIGNING_RESET_SIGNATURE_INVALID,
    REASON_CROSS_SIGNING_RESET_RECOVERY_SERVICE_ATTESTATION_DOMAIN_MISMATCH,
    REASON_CROSS_SIGNING_RESET_GENERATION_MISMATCH,
    REASON_CROSS_SIGNING_RESET_RECOVERY_REF_UNKNOWN,
    REASON_CROSS_SIGNING_RESET_UNLOCK_COMMITMENT_MISMATCH,
    REASON_CROSS_SIGNING_RESET_QUORUM_INSUFFICIENT,
    REASON_CROSS_SIGNING_RESET_QUORUM_BELOW_POLICY,
    REASON_CROSS_SIGNING_RESET_RECOVERY_SERVICE_UNKNOWN,
    REASON_CROSS_SIGNING_RESET_ATTESTATION_MISSING,
    REASON_CROSS_SIGNING_RESET_CLOCK_SKEW_EXCEEDED,
    REASON_CROSS_SIGNING_RESET_REPLAYED,
    REASON_UNSUPPORTED_SIGNATURE_ALG,
    REASON_UNSUPPORTED_HPKE_SUITE,
    REASON_CLAIM_RATE_LIMITED,
    REASON_NAMING_CONVENTION_VIOLATION,
    REASON_APPROVAL_NONCE_REUSED,
    REASON_APPROVAL_ALREADY_CONSUMED,
    REASON_EXECUTED_BY_MISSING,
    REASON_THIRD_PARTY_INVITE_TOKEN_IN_QUERY,
    REASON_PATCH_PATH_INVALID,
    REASON_PATCH_ATOMIC_CONFLICT,
    REASON_PATCH_PATH_REDUCER_MANAGED,
    REASON_PATCH_UNSET_REDACTABLE_FIELD,
    REASON_PATCH_SELECTOR_NO_MATCH,
    REASON_PATCH_SELECTOR_AMBIGUOUS,
    REASON_AEAD_NONCE_COUNTER_REPLAY,
    REASON_AEAD_NONCE_DERIVATION_INVALID,
    REASON_AEAD_NONCE_SENDER_DOMAIN_COLLISION,
    REASON_ACCOUNTABILITY_GRANT_MISSING,
    REASON_FOCUS_MISMATCH,
    REASON_UNKNOWN_FOCUS_TYPE,
    REASON_TOKEN_ISSUER_UNAUTHORISED,
    REASON_PARTICIPANT_BINDING_INVALID,
    REASON_PARTICIPANT_IDENTITY_UNRECOGNISED,
    REASON_SESSION_FOCUS_ALREADY_COMMITTED,
    REASON_CALL_STATE_TERMINAL,
    REASON_CALL_STATE_TRANSITION_INVALID,
    REASON_RECORDING_STATE_TRANSITION_INVALID,
    REASON_E2EE_KEY_SOURCE_UNAUTHORISED,
    REASON_RECORDING_ARTIFACT_PIPELINE_BYPASSED,
    REASON_TRANSCRIPTION_DENIED,
    REASON_TRANSCRIPTION_ARTIFACT_PIPELINE_BYPASSED,
    REASON_RECORDING_CONSENT_REQUIRED,
    REASON_CALL_MODERATION_UNAUTHORISED,
    REASON_CALL_PARTICIPANT_REMOVED,
    REASON_CALL_SUMMARY_INVALID,
    REASON_MEDIA_SERVICE_FOCI_REQUIRED,
    REASON_MEDIA_SERVICE_BINDING_UNCOVERED,
    REASON_FOCUS_UNAVAILABLE_FOR_CLIENT,
    REASON_SESSION_FOCUS_NO_SPLIT_BRAIN,
    REASON_TOKEN_EXPIRED,
    REASON_VERIFICATION_METHOD_PRINCIPAL_MISMATCH,
    REASON_AGENT_GRANT_EXPIRY_REQUIRED,
    REASON_AGENT_GRANT_CONSTRAINT_MISSING,
    REASON_AGENT_KEY_AUTHORIZATION_EXPIRED,
    REASON_SUPERSEDED_BY_REPAIRING,
    REASON_PAIRING_EXPIRED,
    REASON_PAIRING_REQUEST_EXPIRED,
    REASON_PROOF_INVALID,
    REASON_AGENT_PAUSED,
    REASON_AGENT_DEACTIVATED,
    REASON_KEYPACKAGE_WELCOME_ENVELOPE_MISMATCH,
    REASON_KEYPACKAGE_CLAIM_RATE_LIMITED,
    REASON_DELEGATION_CYCLE,
    REASON_DELEGATION_EXPIRY_WIDENING,
    REASON_GRANT_EXCEEDS_ISSUER_AUTHORITY,
    REASON_SUBDELEGATION_PROHIBITED,
    REASON_SCOPE_EXPANSION_FORBIDDEN,
    REASON_DELEGATION_SCOPE_MISMATCH,
    REASON_DELEGATION_SCOPE_CUSTOM_UNSUPPORTED,
    REASON_MISSING_PARENT_REFERENCE,
    REASON_AGENT_PARTICIPATION_CEILING_UNRESOLVED,
    REASON_SPACE_PARENT_CHAIN_IN_BOTTOM_STATE,
    REASON_RECOVERY_WITNESS_MISSING,
    REASON_RECOVERY_WITNESS_INVALID,
    REASON_RECOVERY_WITNESS_POST_CONFLICT,
    REASON_RECOVERY_CAPABILITY_NOT_SEALED,
    REASON_RECOVERY_WITNESS_REVOKE_LAGGING,
    REASON_CHALLENGE_PROOF_INVALID,
    REASON_GRANT_REVOKED_UPSTREAM,
    REASON_GRANT_VALIDITY_WINDOW_EMPTY,
    REASON_PRINCIPAL_DEACTIVATED,
    REASON_ACTOR_SIGNATURE_REVOKED,
    REASON_DELEGATION_REVOKED,
    REASON_RECIPIENT_UNAVAILABLE,
    REASON_MODERATION_STATE_CONFLICT,
    REASON_WELCOME_CAPABILITY_MISMATCH,
    REASON_AUDIT_CAPABILITY_INCOMPLETE,
    REASON_WATCH_MUST_BE_SELF,
    REASON_WATCH_MUTED_MUST_BE_SELF,
    REASON_WATCH_LEVEL_PUBLIC_MUST_BE_SELF,
    REASON_WATCH_SET_OTHERS_AUDIT_MISSING,
    REASON_CROSS_REALM_STRUCTURAL_RELATION,
    REASON_JOIN_AUTHORISATION_INVALID,
    REASON_JOIN_RULE_POLICY_MISMATCH,
    REASON_QUORUM_UNREACHABLE,
    REASON_JOIN_RULE_TIGHTENED,
    REASON_DELIVERY_BINDING_INVALID,
    REASON_DELIVERY_BINDING_POLICY_MISMATCH,
    REASON_PRINCIPAL_CONTROL_EVENT_KIND_FORBIDDEN,
    REASON_EPOCH_UPDATE_REQUIRED,
    REASON_CLAIM_GENERATION_MISMATCH,
    REASON_KEYPACKAGE_REFRESH_REQUIRED,
    REASON_PRESIGN_INVALID,
    REASON_PRESIGN_EXPIRED,
    REASON_PRESIGN_SCOPE_MISMATCH,
    REASON_PRIVATE_ATTACHMENT,
    REASON_POLICY_DENIED,
    REASON_AUDIENCE_MISMATCH,
    REASON_HANDLE_SUBJECT_MISMATCH,
    REASON_HANDLE_HOLDER_ACCEPTANCE_MISSING,
    REASON_HANDLE_HOMOGRAPH_FORBIDDEN,
    REASON_REALM_ALIAS_HOMOGRAPH_FORBIDDEN,
    REASON_CIRCLE_SHORT_NAME_TAKEN,
    REASON_SIDECAR_CREATE_DENIED,
    REASON_SIDECAR_EXPOSURE_ACK_REQUIRED,
    REASON_WEBVH_CACHE_TOO_STALE,
    REASON_DELIVERY_BINDING_HANDOVER_PROOF_INVALID,
    REASON_DELIVERY_BINDING_HANDOVER_RATE_LIMITED,
    REASON_SOFT_FAILED,
    REASON_SPACE_HAS_LIVE_DEPENDENTS,
    REASON_TTL_EXPIRED,
    REASON_CHALLENGE_FAILED,
    REASON_CHALLENGE_EXPIRED,
    REASON_CLAIM_INVALID,
    REASON_NOT_PROVISIONED,
    REASON_MORPH_SCHEMA_REFS_EVOLUTION_UNAUTHORIZED,
    REASON_MORPH_SCHEMA_REFS_TRANSFORMATION_UNSUPPORTED,
    REASON_MORPH_SCHEMA_VERSION_BINDING_MISSING,
    REASON_RANGE_COMPLETENESS_ROOT_MISMATCH,
    REASON_RANGE_COMPLETENESS_ACTOR_SEQ_GAP,
    REASON_WITNESS_DISAGREEMENT,
    REASON_RELAXED_WINDOW_EXCEEDS_CEILING,
    REASON_E2EE_RELAXED_DISALLOWED_IN_COMPLIANCE_PROFILE,
    REASON_CROSS_DOMAIN_REPLAY_REJECTED,
    REASON_RESET_EVENT_ID_MISMATCH,
    REASON_APPEAL_OVERTURN_MISSING_LIFT,
    REASON_APPEAL_MODIFY_MISSING_LIFT,
    REASON_APPEAL_SELF_REVIEW_FORBIDDEN,
    REASON_REALM_TERMINAL_STATE,
    REASON_AUDIT_RELEASE_ATTESTATION_MISMATCH,
    REASON_AUDIT_PURPOSE_MISMATCH,
    REASON_LEGAL_HOLD_ACTIVE,
    REASON_BLOB_REDACTED,
    REASON_MEDIA_PLAINTEXT_SERVICE_NOT_AUTHORISED,
    REASON_MEDIA_PLAINTEXT_WARNING_REQUIRED,
    REASON_MLS_GOVERNANCE_BINDING_STALE,
    REASON_MIMI_GOVERNANCE_BINDING_MISSING,
    REASON_MIMI_GOVERNANCE_BINDING_MISMATCH,
    REASON_MIMI_POLICY_ROOT_MISMATCH,
    REASON_MIMI_ROOM_STATE_INCOMPATIBLE,
    REASON_MIMI_PROVIDER_UNREACHABLE,
    REASON_MIMI_DRAFT_UNSUPPORTED,
    REASON_MIMI_ROOM_BINDING_STATUS_TRANSITION_INVALID,
    REASON_EXPIRED_INVITE_TOKEN,
    REASON_INVALID_ACK_TOKEN,
    REASON_LATE_RECOVERY_REJECTED_MEMBERSHIP,
    REASON_LATE_RECOVERY_SHARE_NOT_AUTHORIZED,
    REASON_LATE_RECOVERY_REJECTED_EXPIRED,
    REASON_SEND_FAILED,
    REASON_PREV_REFS_TOO_LARGE,
    REASON_CAUSAL_REFS_TOO_LARGE,
    REASON_REFS_TOO_LARGE,
    REASON_DEVICE_AUTHORIZED_PRINCIPAL_CONTROL_REALM_MISMATCH,
    REASON_DEVICE_ENROLLMENT_AUTHORITY_SNAPSHOT_MISSING,
    REASON_CELL_IN_BOTTOM_STATE,
    REASON_INCEPTION_UPGRADE_EVIDENCE_STALE,
    REASON_GATE_CHECK_FAILED,
    REASON_REALM_UNAVAILABLE,
    REASON_JOIN_POLICY_DUPLICATE_GATE_ID,
    REASON_CIRCLE_REALM_MISMATCH,
    REASON_CIRCLE_NOT_ACTIVE,
    REASON_CIRCLE_NOT_ARCHIVED,
    REASON_CIRCLE_ALREADY_TERMINAL,
    REASON_SCOPE_UNAVAILABLE,
    REASON_SCOPE_INCOMPARABLE,
    REASON_CIRCLE_MEMBER_MUST_BE_REALM_MEMBER,
    REASON_CIRCLE_COUNT_EXCEEDED,
    REASON_CIRCLE_ENCRYPTION_BELOW_REALM_FLOOR,
    REASON_CONTENT_ENCRYPTION_FLOOR_VIOLATION,
    REASON_CONTENT_ENCRYPTION_FLOOR_DOWNGRADE,
    REASON_DURABILITY_SCHEME_INCOMPATIBLE,
    REASON_HISTORY_VISIBILITY_REQUIRES_HISTORY_CAPABLE_SCHEME,
    REASON_DURABILITY_RECOVERY_RECIPIENT_UNVERIFIED,
    REASON_DURABILITY_SEAL_MISSING_BEFORE_GC,
    REASON_METADATA_ENCRYPTION_FLOOR_DOWNGRADE,
    REASON_SCOPE_REBIND_FORBIDDEN,
    REASON_AGENT_PARTICIPATION_CEILING_WIDEN,
    REASON_AGENT_PARTICIPATION_EXCEEDS_CEILING,
    REASON_AGENT_REPLY_NOT_PERMITTED,
    REASON_EFFECTIVE_SCOPE_REDUCER_MANAGED,
    REASON_ACTOR_KIND_REDUCER_MANAGED,
    REASON_METADATA_ENCRYPTION_FLOOR_VIOLATION,
    REASON_SERIES_CHAIN_BROKEN,
    REASON_SERIES_SEQ_NOT_MONOTONIC,
    REASON_SERIES_PREDECESSOR_NOT_FOUND,
    REASON_RECOVERY_POLICY_MISMATCH,
    REASON_RECOVERY_POLICY_VERSION_NOT_MONOTONIC,
    REASON_RECOVERY_POLICY_SUPERSEDES_INVALID,
    REASON_RECOVERY_POLICY_GENESIS_NOT_V1,
    REASON_RECOVERY_PRINCIPAL_ISOLATION,
    REASON_RECOVERY_PROOF_KIND_UNKNOWN,
    REASON_RECOVERY_SESSION_CHALLENGE_MISMATCH,
    REASON_RECOVERY_SESSION_TERMINAL,
    REASON_PROOF_FAILED,
    REASON_OPERATOR_REJECTED,
    REASON_RISK_POLICY,
    REASON_SUPERSEDED,
    REASON_COUNTER_BOUND_EXCEEDED,
    REASON_INVALID_MEMBERSHIP_TRANSITION,
    REASON_CONTROLLER_MEMBERSHIP_ENDED,
    REASON_SHARE_COMMITMENT_MISMATCH,
    REASON_BACKUP_FRONTIER_STALE,
    REASON_BACKUP_POST_RESET_STALE,
    REASON_STALE_BACKUP_TRUST_GENERATION,
    REASON_UNTRUSTED_BACKUP_SIGNATURE,
    REASON_KEY_BACKUP_WIRE_SCHEMA_REQUIRED,
    REASON_RECOVERY_EVIDENCE_UNBOUND,
    REASON_UNSUPPORTED_AEAD_PROFILE,
    REASON_ATTESTATION_MISSING,
    REASON_SELECTOR_GOVERNANCE_WILDCARD_FORBIDDEN,
    REASON_DIRECT_DOWNLOAD_DISALLOWED_PRESIGN_FORBIDDEN,
    REASON_MINIMAL_METADATA_PRESIGN_FORBIDDEN,
    REASON_READ_RECEIPT_VISIBILITY_COMBINATION_INVALID,
    REASON_EGRESS_POLICY_DENIED,
    REASON_ERASURE_RECEIPT_STUB_DIGEST_MISMATCH,
    REASON_WEBVH_CACHE_UNAVAILABLE,
    REASON_UNSUPPORTED_ATTACHMENT_SCHEME,
    REASON_SEGMENT_SEQUENCE_INVALID,
    REASON_SEGMENT_AEAD_FAILED,
    REASON_SEGMENT_STREAM_TRUNCATED,
    REASON_SEGMENT_REPLAY,
    REASON_SEGMENT_BOUNDS_INVALID,
    REASON_LAST_RESORT_NOT_SUPPORTED,
    REASON_LAST_RESORT_REALM_AFFINITY_VIOLATION,
    REASON_LAST_RESORT_ROTATION_REQUIRED,
    REASON_INCLUSION_LIST_VIOLATION,
    REASON_DELTA_CONTAINS_DATA_EVENT,
    REASON_COVERED_SET_MISMATCH,
    REASON_FORENSIC_ATTRIBUTION_MISMATCH,
    REASON_INSUFFICIENT_CHALLENGE_SAMPLES,
    REASON_MINIMAL_DISCLOSURE_VIOLATION,
    REASON_EVIDENCE_RECIPIENT_MISMATCH,
    REASON_REVOKE_UNDO_INVALID_SIGNATURE,
    REASON_REACTION_TARGET_UNSUPPORTED,
    REASON_REACTION_SCOPE_MISMATCH,
    REASON_EXTERNAL_RATE_LIMITED,
    REASON_APPLET_NAMESPACE_MISMATCH,
    REASON_PROOF_BINDING_MISSING,
    REASON_SCHEMA_DERIVATION_MISMATCH,
    REASON_MORPH_SCHEMA_REFS_PRECONDITION_MISMATCH,
    REASON_UNKNOWN_KIND,
    REASON_UNKNOWN_FIELD,
    REASON_READ_RECEIPT_FORCED_PUBLIC_WORLD_READABLE_FORBIDDEN,
    REASON_MIMI_OBSERVER_WRITE_FORBIDDEN,
    REASON_PLANE_CROSS_WRITE,
    REASON_RELATION_KIND_WATCHES_DERIVED,
    REASON_RELATION_KIND_CONTAINS_DERIVED,
    REASON_INVALID_TASK_FSM_TRANSITION,
    REASON_AUDIT_AGENT_KEY_DESTRUCTION_ATTESTATION_MISSING,
    REASON_AUDIT_AGENT_REMOVE_REQUIRES_PAIRED_DESTRUCTION_ATTESTATION,
    REASON_AUDIT_AGENT_DESTRUCTION_NOT_PAIRED_WITH_REMOVE,
    REASON_AUDIT_AGENT_DESTRUCTION_PROOF_NOT_ENCLAVE_SIGNED,
    REASON_AUDIT_AGENT_EPOCH_RANGE_INCOMPLETE,
    REASON_AUDIT_AGENT_ATTESTATION_MISMATCH,
    REASON_LITE_PROFILE_WRITES_DISALLOWED_EVENT_KIND,
    REASON_CROSS_SPACE_STRUCTURAL_RELATION,
    REASON_GOVERNANCE_BINDING_MISMATCH,
    REASON_MEMBER_IDENTITY_PROOF_INVALID,
    REASON_MEMBER_IDENTITY_REPLACEMENT_DIGEST_MISMATCH,
    REASON_MEMBER_IDENTITY_STATE_MISMATCH,
    REASON_MEMBER_IDENTITY_UNKNOWN_SEGMENT,
    REASON_QUEUE_FULL,
    REASON_INTERNAL_ERROR,
    REASON_SERVICE_KEY_REVOKED,
    REASON_CONSENT_REVOKED,
    REASON_IDENTITY_LINK_NO_LONGER_VISIBLE,
    REASON_IDENTITY_LINK_POLICY_TIGHTENED,
    REASON_INVALIDATED_BY_RATE_LIMIT,
    REASON_INVITE_OOB_ENTROPY_TOO_LOW,
    REASON_REALM_LINK_SELF_REFERENCE,
    REASON_REALM_LINK_INVALID_TRANSITION,
    REASON_HUMAN_APPROVAL_REQUIRED,
    REASON_MINIMAL_METADATA_AUTHOR_CREDENTIAL_INVALID,
];
