use super::codes::*;

/// Return true when code is a registered canonical error code.
pub fn is_known_error_code(code: &str) -> bool {
    KNOWN_ERROR_CODES.contains(&code)
}

/// Return the HTTP status binding for code per error-code-registry.json.
/// None means the code is not registered.
pub fn error_code_http_status(code: &str) -> Option<u16> {
    match code {
        ERROR_CODE_HISTORICAL_ONLY => Some(200),
        ERROR_CODE_BAD_JSON
        | ERROR_CODE_BAD_QUERY
        | ERROR_CODE_MISSING_PARAM
        | ERROR_CODE_INVALID_PARAM
        | ERROR_CODE_INVALID_RESPONSE
        | ERROR_CODE_GRANT_ALREADY_CONSUMED
        | ERROR_CODE_SESSION_LOGGED_OUT
        | ERROR_CODE_AUDIENCE_MISMATCH
        | ERROR_CODE_SIGNATURE_INVALID
        | ERROR_CODE_SIGNATURE_STALE
        | ERROR_CODE_SOURCE_REFS_UNVERIFIABLE
        | ERROR_CODE_GOVERNANCE_KEY_INVALID
        | ERROR_CODE_TTL_OUT_OF_RANGE
        | ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE
        | ERROR_CODE_CURSOR_INTEGRITY_INVALID
        | ERROR_CODE_CURSOR_UNRECOGNIZED
        | ERROR_CODE_BLOB_PRESIGN_INVALID
        | ERROR_CODE_CURSOR_INVALID
        | ERROR_CODE_PUSH_TOKEN_INVALID => Some(400),
        ERROR_CODE_UNAUTHENTICATED
        | ERROR_CODE_AUTH_EXPIRED
        | ERROR_CODE_SOFT_LOGGED_OUT
        | ERROR_CODE_ACCOUNT_LOCKED
        | ERROR_CODE_ACCOUNT_DEACTIVATED
        | ERROR_CODE_ACCOUNT_ERASED
        | ERROR_CODE_DID_PROOF_REQUIRED
        | ERROR_CODE_INVALID_SIGNATURE
        | ERROR_CODE_HTTP_SIGNATURE_REQUIRED
        | ERROR_CODE_HTTP_SIGNATURE_INVALID
        | ERROR_CODE_SIGNATURE_WINDOW_INVALID
        | ERROR_CODE_TURN_CREDENTIAL_EXPIRED => Some(401),
        ERROR_CODE_DIRECTORY_NOT_AUTHORIZED
        | ERROR_CODE_ACCEPT_POLICY_DENIED
        | ERROR_CODE_CAPABILITY_DENIED
        | ERROR_CODE_REALM_FROZEN
        | ERROR_CODE_CLAIM_REQUIRED
        | ERROR_CODE_POLICY_VIOLATION
        | ERROR_CODE_POLICY_DENIED
        | ERROR_CODE_ACCOUNT_SUSPENDED
        | ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED
        | ERROR_CODE_QUOTA_EXCEEDED
        | ERROR_CODE_BLOB_QUOTA_EXCEEDED
        | ERROR_CODE_DEVICE_ENROLLMENT_AUTHORITY_NOT_DESIGNATED
        | ERROR_CODE_HANDLE_UNVERIFIED
        | ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED
        | ERROR_CODE_HISTORY_NOT_VISIBLE
        | ERROR_CODE_PREVIEW_POLICY_DENIED
        | ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED
        | ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED
        | ERROR_CODE_APPLET_REVOKED
        | ERROR_CODE_REVIEWER_CAPABILITY_REVOKED
        | ERROR_CODE_NOT_MEMBER
        | ERROR_CODE_MEDIA_PERMISSION_DENIED
        | ERROR_CODE_ICE_CONFIG_DENIED
        | ERROR_CODE_SFU_NOT_ALLOWED
        | ERROR_CODE_E2EE_REQUIRED
        | ERROR_CODE_RECORDING_DENIED => Some(403),
        ERROR_CODE_NOT_FOUND
        | ERROR_CODE_UNRECOGNIZED_ENDPOINT
        | ERROR_CODE_SEAL_REF_UNKNOWN
        | ERROR_CODE_AUDIENCE_UNKNOWN
        | ERROR_CODE_DEVICE_UNKNOWN
        | ERROR_CODE_DID_NOT_FOUND
        | ERROR_CODE_KEYPACKAGE_UNKNOWN
        | ERROR_CODE_PRINCIPAL_UNKNOWN
        | ERROR_CODE_PUSH_TARGET_UNKNOWN
        | ERROR_CODE_PUSH_TOKEN_UNKNOWN
        | ERROR_CODE_SESSION_GRANT_NOT_FOUND
        | ERROR_CODE_CALL_NOT_FOUND => Some(404),
        ERROR_CODE_METHOD_NOT_ALLOWED => Some(405),
        ERROR_CODE_TAKEDOWN_IN_FORCE
        | ERROR_CODE_POLICY_REVISION_ROLLBACK
        | ERROR_CODE_CONFLICT
        | ERROR_CODE_CAS_CONFLICT
        | ERROR_CODE_CAUSAL_CONFLICT
        | ERROR_CODE_DEPENDENCY_MISSING
        | ERROR_CODE_DISCUSSION_TRACK_DISABLED
        | ERROR_CODE_EPOCH_MISMATCH
        | ERROR_CODE_DUPLICATE_CONFLICT
        | ERROR_CODE_RANK_EXHAUSTED
        | ERROR_CODE_KEY_UNAVAILABLE
        | ERROR_CODE_STATE_MISMATCH
        | ERROR_CODE_AUDIT_RECEIPT_INVALIDATED
        | ERROR_CODE_STALE_FRONTIER
        | ERROR_CODE_STALE_PEER
        | ERROR_CODE_AUTHORIZED_GRANT_REVOKED
        | ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH
        | ERROR_CODE_ACTOR_SEQ_INVALID
        | ERROR_CODE_STALE_SEAL_REF
        | ERROR_CODE_DID_ALREADY_EXISTS
        | ERROR_CODE_KEY_REPLAY
        | ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED
        | ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED
        | ERROR_CODE_POLICY_STALE
        | ERROR_CODE_QUARANTINE
        | ERROR_CODE_STREAM_DROPPED
        | ERROR_CODE_STREAM_RESYNC_REQUIRED
        | ERROR_CODE_PROJECTION_INCOMPLETE
        | ERROR_CODE_MEDIA_NEGOTIATION_FAILED
        | ERROR_CODE_FAILED_PRECONDITION
        | ERROR_CODE_DIRECT_CONVERSATION_UNAVAILABLE
        | ERROR_CODE_PEER_UNRESOLVABLE
        | ERROR_CODE_CONTACT_REQUEST_NOT_PENDING
        | ERROR_CODE_CONTACT_REQUEST_EXPIRED
        | ERROR_CODE_SEAL_INCOMPLETE
        | ERROR_CODE_DELIVERY_BINDING_STALE
        | ERROR_CODE_DELIVERY_BINDING_HANDED_OVER
        | ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE
        | ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH
        | ERROR_CODE_CALL_ALREADY_ANSWERED
        | ERROR_CODE_FAILED_BOTTOM => Some(409),
        // CBA plane invariant violation is a terminal precondition-class
        // failure (registry: 412) and MUST NOT be folded into 409.
        ERROR_CODE_FAILED_PLANE => Some(412),
        ERROR_CODE_CURSOR_EXPIRED
        | ERROR_CODE_CURSOR_REVOKED
        | ERROR_CODE_BLOB_EXPIRED
        | ERROR_CODE_DID_REVOKED
        | ERROR_CODE_CALL_EXPIRED => Some(410),
        ERROR_CODE_PAYLOAD_TOO_LARGE
        | ERROR_CODE_LIMIT_EXCEEDED
        | ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE
        | ERROR_CODE_TOO_LARGE => Some(413),
        ERROR_CODE_SCHEMA_VIOLATION
        | ERROR_CODE_DUPLICATE_CLAUSE_CLAIM
        | ERROR_CODE_KEY_TRANSPARENCY_PROOF_MISSING
        | ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED
        | ERROR_CODE_DIGEST_MISMATCH
        | ERROR_CODE_AAD_DIGEST_MISMATCH
        | ERROR_CODE_PAYLOAD_DIGEST_MISMATCH
        | ERROR_CODE_UNKNOWN_DID
        | ERROR_CODE_BLOB_DIGEST_MISMATCH
        | ERROR_CODE_UNSUPPORTED_DID_METHOD
        | ERROR_CODE_UNSUPPORTED_MEDIA_POLICY
        | ERROR_CODE_POLICY_COMBINATION_INVALID
        | ERROR_CODE_HISTORY_SHARING_POLICY_MISSING
        | ERROR_CODE_NOTARY_RECOVERY_MISSING
        | ERROR_CODE_UNSUPPORTED_LATTICE_TYPE
        | ERROR_CODE_PROFILE_UNSUPPORTED
        | ERROR_CODE_UNSUPPORTED_JOIN_RULE
        | ERROR_CODE_UNSUPPORTED_DIGEST_ALGORITHM
        | ERROR_CODE_UNSUPPORTED_SIGNATURE_ALG
        | ERROR_CODE_UNSUPPORTED_HPKE_SUITE
        | ERROR_CODE_INVALID_AVATAR_BLOB_REF
        | ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH
        | ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT
        | ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF
        | ERROR_CODE_MLS_GOVERNANCE_PROOF_BOUNDS_EXCEEDED
        | ERROR_CODE_MORPH_TYPE_IMMUTABLE => Some(422),
        ERROR_CODE_RATE_LIMITED => Some(429),
        ERROR_CODE_INTERNAL_ERROR => Some(500),
        ERROR_CODE_UNSUPPORTED_FEATURE
        | ERROR_CODE_UNSUPPORTED_EVENT_KIND
        | ERROR_CODE_NOT_IMPLEMENTED => Some(501),
        ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE
        | ERROR_CODE_HLC_LOGICAL_OVERFLOW
        | ERROR_CODE_FRONTIER_UNAVAILABLE
        | ERROR_CODE_POLICY_UNAVAILABLE
        | ERROR_CODE_PUSH_GATEWAY_UNREACHABLE
        | ERROR_CODE_SNAPSHOT_UNAVAILABLE
        | ERROR_CODE_TEMPORARILY_UNAVAILABLE
        | ERROR_CODE_SERVICE_UNAVAILABLE
        | ERROR_CODE_FRANKING_PROOF_UNAVAILABLE => Some(503),
        ERROR_CODE_TIMEOUT => Some(504),
        ERROR_CODE_MLS_GOVERNANCE_ANCHOR_UNREACHABLE => Some(409),
        ERROR_CODE_SERVICE_IDENTITY_UNAVAILABLE
        | ERROR_CODE_SERVICE_IDENTITY_PROVIDER_UNAVAILABLE => Some(503),
        ERROR_CODE_SERVICE_REGISTRATION_REJECTED => Some(400),
        ERROR_CODE_SERVICE_IDENTITY_CONFLICT => Some(409),
        ERROR_CODE_APPLET_ALREADY_REGISTERED => Some(409),
        ERROR_CODE_APPLET_EFFECTIVE_SCOPE_MISMATCH => Some(404),
        ERROR_CODE_APPLET_INSTALL_PROJECTION_INCOMPLETE => Some(409),
        ERROR_CODE_APPLET_INSTALL_REQUIRED => Some(409),
        ERROR_CODE_APPLET_NAMESPACE_CONFLICT => Some(409),
        ERROR_CODE_APPLET_PACKAGE_EXPIRED => Some(400),
        ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISMATCH => Some(400),
        ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISSING => Some(400),
        ERROR_CODE_APPLET_REGISTRATION_EPOCH_SIGNING_KEY_MISMATCH => Some(400),
        ERROR_CODE_APPLET_TRANSACTION_IN_PROGRESS => Some(409),
        ERROR_CODE_BOT_ACTOR_REVOKED => Some(403),
        ERROR_CODE_ENCLAVE_NO_UPSTREAM_PROXY_FOR_EXTERNAL => Some(403),
        ERROR_CODE_ENCLAVE_NOT_TRUSTED => Some(403),
        ERROR_CODE_EXTERNAL_INVITE_ACTOR_MISMATCH => Some(403),
        ERROR_CODE_EXTERNAL_USER_NO_MAIN_ACCESS => Some(403),
        ERROR_CODE_UPSTREAM_UNAVAILABLE => Some(412),
        ERROR_CODE_AGENT_PROVISION_FANOUT_UNAVAILABLE => Some(501),
        ERROR_CODE_CANNOT_PAIR_CURRENT_DEVICE => Some(409),
        ERROR_CODE_CROSS_SIGNING_STATE_MISSING => Some(409),
        ERROR_CODE_DEVICE_ALREADY_AUTHORIZED => Some(409),
        ERROR_CODE_DEVICE_NOT_AUTHORIZED => Some(403),
        ERROR_CODE_DEVICE_REVOKED => Some(409),
        ERROR_CODE_DISCOVERY_FAILED => Some(404),
        ERROR_CODE_FIRST_BACKUP_GATE_UNSATISFIED => Some(409),
        ERROR_CODE_FRESH_DEVICE_SCOPE_VIOLATION => Some(403),
        ERROR_CODE_INVALID_AVATAR_URL => Some(400),
        ERROR_CODE_RECOVERY_AUTHORIZATION_DEVICE_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_AUTHORIZATION_PRINCIPAL_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_AUTHORIZATION_SESSION_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_CONTROL_EVENT_KIND_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_CONTROL_EVENT_NOT_FOUND => Some(409),
        ERROR_CODE_RECOVERY_LIST_UPDATE_DEVICE_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_LIST_UPDATE_PRINCIPAL_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_POLICY_CONFLICT => Some(409),
        ERROR_CODE_RECOVERY_POLICY_DEVICE_NOT_AUTHORIZED => Some(409),
        ERROR_CODE_RECOVERY_POLICY_ID_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_POLICY_MISSING => Some(409),
        ERROR_CODE_RECOVERY_POLICY_REVOKED => Some(409),
        ERROR_CODE_RECOVERY_POLICY_TRUST_DOMAIN_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_POLICY_VERSION_MISMATCH => Some(409),
        ERROR_CODE_RECOVERY_PROOF_AUTHORITY_INVALID => Some(401),
        ERROR_CODE_RECOVERY_PROOF_KIND_NOT_ALLOWED => Some(409),
        ERROR_CODE_RECOVERY_PROOF_KIND_UNIMPLEMENTED => Some(501),
        ERROR_CODE_RECOVERY_RECEIPT_CONFLICT => Some(409),
        ERROR_CODE_RECOVERY_SESSION_CONFLICT => Some(409),
        ERROR_CODE_RECOVERY_SESSION_ID_REUSED => Some(409),
        ERROR_CODE_RECOVERY_SESSION_NOT_PENDING => Some(409),
        ERROR_CODE_FEDERATION_ACTOR_ORIGIN_REJECTED => Some(403),
        ERROR_CODE_FEDERATION_INTEROP_TRACK_ONLY => Some(501),
        ERROR_CODE_FEDERATION_ORIGIN_DENIED => Some(403),
        ERROR_CODE_FEDERATION_PRIVATE_READ_RAIL_LOCAL_ONLY => Some(501),
        ERROR_CODE_REALM_FEDERATION_POLICY_CLOSED => Some(403),
        ERROR_CODE_REALM_FEDERATION_POLICY_INVALID => Some(403),
        ERROR_CODE_REALM_FEDERATION_POLICY_QUARANTINE => Some(403),
        ERROR_CODE_REALM_FEDERATION_POLICY_RESTRICTED => Some(403),
        ERROR_CODE_REALM_MODERATION_POLICY_DENIED => Some(403),
        ERROR_CODE_MIMI_E2EE_BOUNDARY_UNMARKED => Some(400),
        ERROR_CODE_MIMI_PAYLOAD_DIGEST_MISMATCH => Some(400),
        ERROR_CODE_MIMI_PAYLOAD_INVALID => Some(400),
        ERROR_CODE_MIMI_REPORTER_RESOLUTION_REQUIRED => Some(403),
        ERROR_CODE_STALE_PEER_STATE_UNAVAILABLE => Some(503),
        ERROR_CODE_FRANKING_TAMPERED => Some(400),
        ERROR_CODE_MLS_KEYPACKAGE_CLAIM_REQUEST_EXPIRED => Some(409),
        ERROR_CODE_SNAPSHOT_CHUNK_DIGEST_MISMATCH => Some(400),
        _ => None,
    }
}
