#!/usr/bin/env python3
"""Drive the feasibility experiment for one models crate.

Reads the selected models crate and Spec artifacts. Writes to the chosen
``--out`` directory (default: ``tools/spec-struct-proto/out``). The deny-unknown
audit invokes ``--check`` to reject schema/serde drift. Produces:

* ``mapping.json``   - Rust type to Spec pointer inventory with evidence class.
* ``bindings.json``  - terminal-``$ref`` to Rust type table learned from the crate.
* ``generated.rs``   - the prototype's output for every mapped type.
* ``differences.json`` - every difference, bucketed.
* a stdout summary.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import bindings as bindings_module  # noqa: E402
import compare as compare_module  # noqa: E402
import mapping as mapping_module  # noqa: E402
from generate import Generator, render  # noqa: E402
from wire_value_audit import SchemaResolver  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent / "out"
PREAMBLE = """// GENERATED BY tools/spec-struct-proto - FEASIBILITY PROTOTYPE, NOT A BUILD INPUT.
// Nothing under crates/ reads this file. It exists to be diffed against the
// hand-written crate, so it deliberately omits rustdoc, builders and the
// `openapi` cfg_attr layer the hand-written types carry.
#![allow(dead_code)]

use std::collections::{BTreeMap, BTreeSet};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--crate", default="models-discovery")
    parser.add_argument("--spec-root", type=Path, default=mapping_module.DEFAULT_SPEC_ROOT)
    parser.add_argument("--out", type=Path, default=OUT_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a real drift is not the separately tracked Spec defect",
    )
    args = parser.parse_args()

    crate_src = mapping_module.SDK_ROOT / "crates" / args.crate / "src"
    mappings, types, _index = mapping_module.build(crate_src, args.spec_root)
    resolver = SchemaResolver(args.spec_root)
    newtypes, conflicts = bindings_module.learn(types, mappings, resolver)

    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "mapping.json").write_text(
        json.dumps([entry.__dict__ for entry in mappings], indent=2),
        encoding="utf-8",
        newline="\n",
    )
    (args.out / "bindings.json").write_text(
        json.dumps(
            {"version": 1, "bindings": newtypes, "conflicts": conflicts}, indent=2
        ),
        encoding="utf-8",
        newline="\n",
    )

    named_pointers = {
        entry.pointer: entry.rust_type
        for entry in mappings
        if entry.pointer and entry.evidence != "near-match"
    }
    # A named type must be generated, not substituted for itself.
    generator = Generator(resolver, newtypes, named_pointers)

    comparisons: list[compare_module.Comparison] = []
    rendered: dict[str, str] = {}
    collisions: list[str] = []
    unattempted: list[tuple[str, str]] = []

    targets = [
        entry
        for entry in mappings
        if entry.pointer and entry.rust_type in types
    ]
    for entry in targets:
        item = types[entry.rust_type]
        if not item.is_serde:
            unattempted.append((entry.rust_type, "type does not derive Serialize/Deserialize"))
            continue
        if item.kind in ("newtype", "unit_struct"):
            unattempted.append((entry.rust_type, f"{item.kind}: no property set to generate"))
            continue
        local = Generator(resolver, newtypes, {
            pointer: name
            for pointer, name in named_pointers.items()
            if name != entry.rust_type
        })
        produced = local.build(entry.rust_type, entry.pointer)
        generator.gaps.extend(local.gaps)
        generator.constraints.extend(local.constraints)
        if produced is None:
            unattempted.append((entry.rust_type, "generator produced nothing"))
            continue
        for emitted in [produced] + [g for g in local.generated if g is not produced]:
            text = render(emitted)
            previous = rendered.get(emitted.name)
            if previous is None:
                rendered[emitted.name] = text
            elif previous != text:
                collisions.append(f"{emitted.name} ({emitted.pointer})")
        comparisons.append(
            compare_module.compare(
                item, produced, types, {g.name: g for g in local.generated}
            )
        )

    (args.out / "generated.rs").write_text(
        PREAMBLE + "\n" + "\n\n".join(rendered[key] for key in sorted(rendered)) + "\n",
        encoding="utf-8",
        newline="\n",
    )

    differences = [
        difference.__dict__
        for comparison in comparisons
        for difference in comparison.differences
    ]
    (args.out / "differences.json").write_text(
        json.dumps(
            {
                "attempted": len(comparisons),
                "identical": sum(1 for c in comparisons if c.identical),
                "unattempted": [
                    {"rust_type": name, "reason": reason} for name, reason in unattempted
                ],
                "name_collisions": collisions,
                "generator_gaps": [gap.__dict__ for gap in generator.gaps],
                "unexpressed_constraints": [c.__dict__ for c in generator.constraints],
                "differences": differences,
            },
            indent=2,
        ),
        encoding="utf-8",
        newline="\n",
    )

    evidence = Counter(entry.evidence for entry in mappings)
    buckets = Counter(difference["bucket"] for difference in differences)
    print(f"crate                : {args.crate}")
    print(f"rust types parsed    : {len(types)}")
    for name, count in sorted(evidence.items()):
        print(f"  mapping/{name:<20}: {count}")
    print(f"generation attempted : {len(comparisons)}")
    print(f"  byte-shape identical: {sum(1 for c in comparisons if c.identical)}")
    print(f"  with differences    : {sum(1 for c in comparisons if not c.identical)}")
    print(f"generation skipped   : {len(unattempted)}")
    print(f"generated type decls : {len(rendered)}")
    print(f"name collisions      : {len(collisions)}")
    print(f"generator gaps       : {len(generator.gaps)}")
    print(f"unexpressed constrs  : {len(generator.constraints)}")
    print(f"binding conflicts    : {len(conflicts)}")
    for name, count in sorted(buckets.items()):
        print(f"  difference/{name:<17}: {count}")
    if args.check:
        unexpected = [
            difference
            for difference in differences
            if difference["bucket"] == "drift"
        ]
        if unexpected:
            for difference in unexpected:
                print(
                    "unexpected spec/Rust drift: "
                    f"{difference['rust_type']}.{difference['member']} -> "
                    f"{difference['pointer']}: {difference['detail']}",
                    file=sys.stderr,
                )
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
