[package]
authors = ["Chris Young <chris@sonc.ai>"]
categories = ["api-bindings", "network-programming"]
description = "HTTP client bindings for Contrix v1 service endpoints."
edition = "2024"
homepage = "https://github.com/contrix/contrix-rust-sdk"
keywords = ["contrix", "client", "http", "sdk"]
license = "Apache-2.0"
name = "contrix-client"
readme = "README.md"
repository = "https://github.com/contrix/contrix-rust-sdk"
rust-version.workspace = true
version = "0.7.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dependencies]
contrix-core = { workspace = true, features = ["client"] }
reqwest = { workspace = true, features = ["json", "gzip", "http2"] }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["time"] }
url = { workspace = true, features = ["serde"] }

[lints]
workspace = true
