[package]
authors = ["Chris Young <chris@sonc.ai>"]
description = "Contrix v1 federation protocol API models."
edition = "2024"
homepage = "https://github.com/contrix/contrix-rust-sdk"
keywords = ["contrix", "federation", "protocol", "server"]
license = "Apache-2.0"
name = "contrix-federation-api"
readme = "README.md"
repository = "https://github.com/contrix/contrix-rust-sdk"
rust-version.workspace = true
version = "0.7.0"

[features]
default = []

[dependencies]
chrono = { workspace = true, features = ["serde"] }
contrix-core.workspace = true
contrix-signatures.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
