// @generated by tools/generate-sdk-error-codes.ps1 from
// cokret-spec/spec/v1/artifacts/registry/error-code-registry.json; do not edit by hand.
//
// One constant per canonical top-level error code. The failed_precondition
// sub-reasons live in reasons.rs as REASON_* constants; they are NOT top-level
// wire codes and must never be declared here as ERROR_CODE_*.

pub const ERROR_CODE_BAD_JSON: &str = "bad_json";
pub const ERROR_CODE_BAD_QUERY: &str = "bad_query";
pub const ERROR_CODE_SCHEMA_VIOLATION: &str = "schema_violation";
pub const ERROR_CODE_MISSING_PARAM: &str = "missing_param";
pub const ERROR_CODE_INVALID_PARAM: &str = "invalid_param";
pub const ERROR_CODE_INVALID_RESPONSE: &str = "invalid_response";
pub const ERROR_CODE_UNAUTHENTICATED: &str = "unauthenticated";
pub const ERROR_CODE_AUTH_EXPIRED: &str = "auth_expired";
pub const ERROR_CODE_GRANT_ALREADY_CONSUMED: &str = "grant_already_consumed";
pub const ERROR_CODE_SESSION_LOGGED_OUT: &str = "session_logged_out";
pub const ERROR_CODE_AUDIENCE_MISMATCH: &str = "audience_mismatch";
pub const ERROR_CODE_SOFT_LOGGED_OUT: &str = "soft_logged_out";
pub const ERROR_CODE_ACCOUNT_LOCKED: &str = "account_locked";
pub const ERROR_CODE_ACCOUNT_SUSPENDED: &str = "account_suspended";
pub const ERROR_CODE_ACCOUNT_DEACTIVATED: &str = "account_deactivated";
pub const ERROR_CODE_ACCOUNT_ERASED: &str = "account_erased";
pub const ERROR_CODE_DID_PROOF_REQUIRED: &str = "did_proof_required";
pub const ERROR_CODE_INVALID_SIGNATURE: &str = "invalid_signature";
pub const ERROR_CODE_HTTP_SIGNATURE_REQUIRED: &str = "http_signature_required";
pub const ERROR_CODE_HTTP_SIGNATURE_INVALID: &str = "http_signature_invalid";
pub const ERROR_CODE_SIGNATURE_WINDOW_INVALID: &str = "signature_window_invalid";
pub const ERROR_CODE_DIRECTORY_NOT_AUTHORIZED: &str = "directory_not_authorized";
pub const ERROR_CODE_ACCEPT_POLICY_DENIED: &str = "accept_policy_denied";
pub const ERROR_CODE_SIGNATURE_INVALID: &str = "signature_invalid";
pub const ERROR_CODE_SIGNATURE_STALE: &str = "signature_stale";
pub const ERROR_CODE_SOURCE_REFS_UNVERIFIABLE: &str = "source_refs_unverifiable";
pub const ERROR_CODE_GOVERNANCE_KEY_INVALID: &str = "governance_key_invalid";
pub const ERROR_CODE_TTL_OUT_OF_RANGE: &str = "ttl_out_of_range";
pub const ERROR_CODE_TAKEDOWN_IN_FORCE: &str = "takedown_in_force";
pub const ERROR_CODE_POLICY_REVISION_ROLLBACK: &str = "policy_revision_rollback";
pub const ERROR_CODE_CAPABILITY_DENIED: &str = "capability_denied";
pub const ERROR_CODE_REALM_FROZEN: &str = "realm_frozen";
pub const ERROR_CODE_CLAIM_REQUIRED: &str = "claim_required";
pub const ERROR_CODE_POLICY_VIOLATION: &str = "policy_violation";
pub const ERROR_CODE_POLICY_DENIED: &str = "policy_denied";
pub const ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED: &str =
    "read_receipt_compliance_floor_violated";
pub const ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED: &str = "ephemeral_kind_not_permitted";
pub const ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE: &str = "ephemeral_ttl_out_of_range";
pub const ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE: &str = "ephemeral_channel_unavailable";
pub const ERROR_CODE_NOT_FOUND: &str = "not_found";
pub const ERROR_CODE_UNRECOGNIZED_ENDPOINT: &str = "unrecognized_endpoint";
pub const ERROR_CODE_METHOD_NOT_ALLOWED: &str = "method_not_allowed";
pub const ERROR_CODE_CONFLICT: &str = "conflict";
pub const ERROR_CODE_CAS_CONFLICT: &str = "cas_conflict";
pub const ERROR_CODE_CAUSAL_CONFLICT: &str = "causal_conflict";
pub const ERROR_CODE_DEPENDENCY_MISSING: &str = "dependency_missing";
pub const ERROR_CODE_DISCUSSION_TRACK_DISABLED: &str = "discussion_track_disabled";
pub const ERROR_CODE_EPOCH_MISMATCH: &str = "epoch_mismatch";
pub const ERROR_CODE_DUPLICATE_CONFLICT: &str = "duplicate_conflict";
pub const ERROR_CODE_RANK_EXHAUSTED: &str = "rank_exhausted";
pub const ERROR_CODE_HLC_LOGICAL_OVERFLOW: &str = "hlc_logical_overflow";
pub const ERROR_CODE_PAYLOAD_TOO_LARGE: &str = "payload_too_large";
pub const ERROR_CODE_DIGEST_MISMATCH: &str = "digest_mismatch";
pub const ERROR_CODE_AAD_DIGEST_MISMATCH: &str = "aad_digest_mismatch";
pub const ERROR_CODE_PAYLOAD_DIGEST_MISMATCH: &str = "payload_digest_mismatch";
pub const ERROR_CODE_KEY_UNAVAILABLE: &str = "key_unavailable";
pub const ERROR_CODE_STATE_MISMATCH: &str = "state_mismatch";
pub const ERROR_CODE_AUDIT_RECEIPT_INVALIDATED: &str = "audit_receipt_invalidated";
pub const ERROR_CODE_UNKNOWN_DID: &str = "unknown_did";
pub const ERROR_CODE_QUOTA_EXCEEDED: &str = "quota_exceeded";
pub const ERROR_CODE_LIMIT_EXCEEDED: &str = "limit_exceeded";
pub const ERROR_CODE_RATE_LIMITED: &str = "rate_limited";
pub const ERROR_CODE_TIMEOUT: &str = "timeout";
pub const ERROR_CODE_STALE_FRONTIER: &str = "stale_frontier";
pub const ERROR_CODE_STALE_PEER: &str = "stale_peer";
pub const ERROR_CODE_AUTHORIZED_GRANT_REVOKED: &str = "authorized_grant_revoked";
pub const ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH: &str =
    "device_recovery_ssk_generation_mismatch";
pub const ERROR_CODE_CURSOR_EXPIRED: &str = "cursor_expired";
pub const ERROR_CODE_CURSOR_INTEGRITY_INVALID: &str = "cursor_integrity_invalid";
pub const ERROR_CODE_CURSOR_REVOKED: &str = "cursor_revoked";
pub const ERROR_CODE_CURSOR_UNRECOGNIZED: &str = "cursor_unrecognized";
pub const ERROR_CODE_ACTOR_SEQ_INVALID: &str = "actor_seq_invalid";
pub const ERROR_CODE_STALE_SEAL_REF: &str = "stale_seal_ref";
pub const ERROR_CODE_SEAL_REF_UNKNOWN: &str = "seal_ref_unknown";
pub const ERROR_CODE_AUDIENCE_UNKNOWN: &str = "audience_unknown";
pub const ERROR_CODE_BLOB_DIGEST_MISMATCH: &str = "blob_digest_mismatch";
pub const ERROR_CODE_BLOB_EXPIRED: &str = "blob_expired";
pub const ERROR_CODE_BLOB_PRESIGN_INVALID: &str = "blob_presign_invalid";
pub const ERROR_CODE_BLOB_QUOTA_EXCEEDED: &str = "blob_quota_exceeded";
pub const ERROR_CODE_CURSOR_INVALID: &str = "cursor_invalid";
pub const ERROR_CODE_DEVICE_ENROLLMENT_AUTHORITY_NOT_DESIGNATED: &str =
    "device_enrollment_authority_not_designated";
pub const ERROR_CODE_DEVICE_UNKNOWN: &str = "device_unknown";
pub const ERROR_CODE_DID_ALREADY_EXISTS: &str = "did_already_exists";
pub const ERROR_CODE_DID_NOT_FOUND: &str = "did_not_found";
pub const ERROR_CODE_DID_REVOKED: &str = "did_revoked";
pub const ERROR_CODE_FRONTIER_UNAVAILABLE: &str = "frontier_unavailable";
pub const ERROR_CODE_HANDLE_UNVERIFIED: &str = "handle_unverified";
pub const ERROR_CODE_KEY_REPLAY: &str = "key_replay";
pub const ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED: &str = "keypackage_already_consumed";
pub const ERROR_CODE_KEYPACKAGE_UNKNOWN: &str = "keypackage_unknown";
pub const ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED: &str = "one_time_keys_exhausted";
pub const ERROR_CODE_POLICY_STALE: &str = "policy_stale";
pub const ERROR_CODE_POLICY_UNAVAILABLE: &str = "policy_unavailable";
pub const ERROR_CODE_PRINCIPAL_UNKNOWN: &str = "principal_unknown";
pub const ERROR_CODE_PUSH_GATEWAY_UNREACHABLE: &str = "push_gateway_unreachable";
pub const ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE: &str = "push_payload_too_large";
pub const ERROR_CODE_PUSH_TARGET_UNKNOWN: &str = "push_target_unknown";
pub const ERROR_CODE_PUSH_TOKEN_INVALID: &str = "push_token_invalid";
pub const ERROR_CODE_PUSH_TOKEN_UNKNOWN: &str = "push_token_unknown";
pub const ERROR_CODE_QUARANTINE: &str = "quarantine";
pub const ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED: &str = "snapshot_authority_unverified";
pub const ERROR_CODE_SNAPSHOT_UNAVAILABLE: &str = "snapshot_unavailable";
pub const ERROR_CODE_STREAM_DROPPED: &str = "stream_dropped";
pub const ERROR_CODE_STREAM_RESYNC_REQUIRED: &str = "stream_resync_required";
pub const ERROR_CODE_TOO_LARGE: &str = "too_large";
pub const ERROR_CODE_UNSUPPORTED_DID_METHOD: &str = "unsupported_did_method";
pub const ERROR_CODE_UNSUPPORTED_MEDIA_POLICY: &str = "unsupported_media_policy";
pub const ERROR_CODE_MEDIA_NEGOTIATION_FAILED: &str = "media_negotiation_failed";
pub const ERROR_CODE_UNSUPPORTED_FEATURE: &str = "unsupported_feature";
pub const ERROR_CODE_UNSUPPORTED_EVENT_KIND: &str = "unsupported_event_kind";
pub const ERROR_CODE_NOT_IMPLEMENTED: &str = "not_implemented";
pub const ERROR_CODE_PROJECTION_INCOMPLETE: &str = "projection_incomplete";
pub const ERROR_CODE_INTERNAL_ERROR: &str = "internal_error";
pub const ERROR_CODE_TEMPORARILY_UNAVAILABLE: &str = "temporarily_unavailable";
pub const ERROR_CODE_SERVICE_UNAVAILABLE: &str = "service_unavailable";
pub const ERROR_CODE_POLICY_COMBINATION_INVALID: &str = "policy_combination_invalid";
pub const ERROR_CODE_HISTORY_SHARING_POLICY_MISSING: &str = "history_sharing_policy_missing";
pub const ERROR_CODE_HISTORY_NOT_VISIBLE: &str = "history_not_visible";
pub const ERROR_CODE_PREVIEW_POLICY_DENIED: &str = "preview_policy_denied";
pub const ERROR_CODE_NOTARY_RECOVERY_MISSING: &str = "notary_recovery_missing";
pub const ERROR_CODE_UNSUPPORTED_LATTICE_TYPE: &str = "unsupported_lattice_type";
pub const ERROR_CODE_PROFILE_UNSUPPORTED: &str = "profile_unsupported";
pub const ERROR_CODE_UNSUPPORTED_JOIN_RULE: &str = "unsupported_join_rule";
pub const ERROR_CODE_FAILED_PRECONDITION: &str = "failed_precondition";
pub const ERROR_CODE_FAILED_PLANE: &str = "failed_plane";
pub const ERROR_CODE_FAILED_BOTTOM: &str = "failed_bottom";
pub const ERROR_CODE_CONTACT_NOT_ACCEPTED: &str = "contact_not_accepted";
pub const ERROR_CODE_CONTACT_CONSENT_MISSING: &str = "contact_consent_missing";
pub const ERROR_CODE_PEER_UNRESOLVABLE: &str = "peer_unresolvable";
pub const ERROR_CODE_CONTACT_REQUEST_NOT_PENDING: &str = "contact_request_not_pending";
pub const ERROR_CODE_CONTACT_REQUEST_EXPIRED: &str = "contact_request_expired";
pub const ERROR_CODE_UNSUPPORTED_DIGEST_ALGORITHM: &str = "unsupported_digest_algorithm";
pub const ERROR_CODE_UNSUPPORTED_SIGNATURE_ALG: &str = "unsupported_signature_alg";
pub const ERROR_CODE_UNSUPPORTED_HPKE_SUITE: &str = "unsupported_hpke_suite";
pub const ERROR_CODE_SEAL_INCOMPLETE: &str = "seal_incomplete";
pub const ERROR_CODE_FRANKING_PROOF_UNAVAILABLE: &str = "franking_proof_unavailable";
pub const ERROR_CODE_TURN_CREDENTIAL_EXPIRED: &str = "turn_credential_expired";
pub const ERROR_CODE_DELIVERY_BINDING_STALE: &str = "delivery_binding_stale";
pub const ERROR_CODE_DELIVERY_BINDING_HANDED_OVER: &str = "delivery_binding_handed_over";
pub const ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE: &str = "delivery_binding_unresolvable";
pub const ERROR_CODE_HISTORICAL_ONLY: &str = "historical_only";
pub const ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED: &str = "applet_registration_unauthorized";
pub const ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH: &str = "applet_install_plan_mismatch";
pub const ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED: &str = "applet_e2ee_join_unauthorized";
pub const ERROR_CODE_APPLET_REVOKED: &str = "applet_revoked";
pub const ERROR_CODE_INVALID_AVATAR_BLOB_REF: &str = "invalid_avatar_blob_ref";
pub const ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH: &str = "unsupported_profile_patch_path";
pub const ERROR_CODE_SESSION_GRANT_NOT_FOUND: &str = "session_grant_not_found";
pub const ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT: &str = "session_revoke_selector_conflict";
pub const ERROR_CODE_REVIEWER_CAPABILITY_REVOKED: &str = "reviewer_capability_revoked";
pub const ERROR_CODE_NOT_MEMBER: &str = "not_member";
pub const ERROR_CODE_CALL_NOT_FOUND: &str = "call_not_found";
pub const ERROR_CODE_CALL_EXPIRED: &str = "call_expired";
pub const ERROR_CODE_CALL_ALREADY_ANSWERED: &str = "call_already_answered";
pub const ERROR_CODE_MEDIA_PERMISSION_DENIED: &str = "media_permission_denied";
pub const ERROR_CODE_ICE_CONFIG_DENIED: &str = "ice_config_denied";
pub const ERROR_CODE_SFU_NOT_ALLOWED: &str = "sfu_not_allowed";
pub const ERROR_CODE_E2EE_REQUIRED: &str = "e2ee_required";
pub const ERROR_CODE_RECORDING_DENIED: &str = "recording_denied";
pub const ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF: &str = "morph_profile_widens_schema_ref";
pub const ERROR_CODE_MORPH_TYPE_IMMUTABLE: &str = "morph_type_immutable";
pub const ERROR_CODE_APPLET_ALREADY_REGISTERED: &str = "applet_already_registered";
pub const ERROR_CODE_APPLET_EFFECTIVE_SCOPE_MISMATCH: &str = "applet_effective_scope_mismatch";
pub const ERROR_CODE_APPLET_INSTALL_PROJECTION_INCOMPLETE: &str =
    "applet_install_projection_incomplete";
pub const ERROR_CODE_APPLET_INSTALL_REQUIRED: &str = "applet_install_required";
pub const ERROR_CODE_APPLET_NAMESPACE_CONFLICT: &str = "applet_namespace_conflict";
pub const ERROR_CODE_APPLET_PACKAGE_EXPIRED: &str = "applet_package_expired";
pub const ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISMATCH: &str =
    "applet_registration_epoch_evidence_mismatch";
pub const ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISSING: &str =
    "applet_registration_epoch_evidence_missing";
pub const ERROR_CODE_APPLET_REGISTRATION_EPOCH_SIGNING_KEY_MISMATCH: &str =
    "applet_registration_epoch_signing_key_mismatch";
pub const ERROR_CODE_APPLET_TRANSACTION_IN_PROGRESS: &str = "applet_transaction_in_progress";
pub const ERROR_CODE_BOT_ACTOR_REVOKED: &str = "bot_actor_revoked";
pub const ERROR_CODE_ENCLAVE_NO_UPSTREAM_PROXY_FOR_EXTERNAL: &str =
    "enclave_no_upstream_proxy_for_external";
pub const ERROR_CODE_ENCLAVE_NOT_TRUSTED: &str = "enclave_not_trusted";
pub const ERROR_CODE_EXTERNAL_INVITE_ACTOR_MISMATCH: &str = "external_invite_actor_mismatch";
pub const ERROR_CODE_EXTERNAL_USER_NO_MAIN_ACCESS: &str = "external_user_no_main_access";
pub const ERROR_CODE_UPSTREAM_UNAVAILABLE: &str = "upstream_unavailable";
pub const ERROR_CODE_AGENT_PROVISION_FANOUT_UNAVAILABLE: &str =
    "agent_provision_fanout_unavailable";
pub const ERROR_CODE_CANNOT_PAIR_CURRENT_DEVICE: &str = "cannot_pair_current_device";
pub const ERROR_CODE_CROSS_SIGNING_STATE_MISSING: &str = "cross_signing_state_missing";
pub const ERROR_CODE_DEVICE_ALREADY_AUTHORIZED: &str = "device_already_authorized";
pub const ERROR_CODE_DEVICE_NOT_AUTHORIZED: &str = "device_not_authorized";
pub const ERROR_CODE_DEVICE_REVOKED: &str = "device_revoked";
pub const ERROR_CODE_DISCOVERY_FAILED: &str = "discovery_failed";
pub const ERROR_CODE_FIRST_BACKUP_GATE_UNSATISFIED: &str = "first_backup_gate_unsatisfied";
pub const ERROR_CODE_FRESH_DEVICE_SCOPE_VIOLATION: &str = "fresh_device_scope_violation";
pub const ERROR_CODE_INVALID_AVATAR_URL: &str = "invalid_avatar_url";
pub const ERROR_CODE_RECOVERY_AUTHORIZATION_DEVICE_MISMATCH: &str =
    "recovery_authorization_device_mismatch";
pub const ERROR_CODE_RECOVERY_AUTHORIZATION_PRINCIPAL_MISMATCH: &str =
    "recovery_authorization_principal_mismatch";
pub const ERROR_CODE_RECOVERY_AUTHORIZATION_SESSION_MISMATCH: &str =
    "recovery_authorization_session_mismatch";
pub const ERROR_CODE_RECOVERY_CONTROL_EVENT_KIND_MISMATCH: &str =
    "recovery_control_event_kind_mismatch";
pub const ERROR_CODE_RECOVERY_CONTROL_EVENT_NOT_FOUND: &str = "recovery_control_event_not_found";
pub const ERROR_CODE_RECOVERY_LIST_UPDATE_DEVICE_MISMATCH: &str =
    "recovery_list_update_device_mismatch";
pub const ERROR_CODE_RECOVERY_LIST_UPDATE_PRINCIPAL_MISMATCH: &str =
    "recovery_list_update_principal_mismatch";
pub const ERROR_CODE_RECOVERY_POLICY_CONFLICT: &str = "recovery_policy_conflict";
pub const ERROR_CODE_RECOVERY_POLICY_DEVICE_NOT_AUTHORIZED: &str =
    "recovery_policy_device_not_authorized";
pub const ERROR_CODE_RECOVERY_POLICY_ID_MISMATCH: &str = "recovery_policy_id_mismatch";
pub const ERROR_CODE_RECOVERY_POLICY_MISSING: &str = "recovery_policy_missing";
pub const ERROR_CODE_RECOVERY_POLICY_REVOKED: &str = "recovery_policy_revoked";
pub const ERROR_CODE_RECOVERY_POLICY_TRUST_DOMAIN_MISMATCH: &str =
    "recovery_policy_trust_domain_mismatch";
pub const ERROR_CODE_RECOVERY_POLICY_VERSION_MISMATCH: &str = "recovery_policy_version_mismatch";
pub const ERROR_CODE_RECOVERY_PROOF_AUTHORITY_INVALID: &str = "recovery_proof_authority_invalid";
pub const ERROR_CODE_RECOVERY_PROOF_KIND_NOT_ALLOWED: &str = "recovery_proof_kind_not_allowed";
pub const ERROR_CODE_RECOVERY_PROOF_KIND_UNIMPLEMENTED: &str = "recovery_proof_kind_unimplemented";
pub const ERROR_CODE_RECOVERY_RECEIPT_CONFLICT: &str = "recovery_receipt_conflict";
pub const ERROR_CODE_RECOVERY_SESSION_CONFLICT: &str = "recovery_session_conflict";
pub const ERROR_CODE_RECOVERY_SESSION_ID_REUSED: &str = "recovery_session_id_reused";
pub const ERROR_CODE_RECOVERY_SESSION_NOT_PENDING: &str = "recovery_session_not_pending";
pub const ERROR_CODE_FEDERATION_ACTOR_ORIGIN_REJECTED: &str = "federation_actor_origin_rejected";
pub const ERROR_CODE_FEDERATION_INTEROP_TRACK_ONLY: &str = "federation_interop_track_only";
pub const ERROR_CODE_FEDERATION_ORIGIN_DENIED: &str = "federation_origin_denied";
pub const ERROR_CODE_FEDERATION_PRIVATE_READ_RAIL_LOCAL_ONLY: &str =
    "federation_private_read_rail_local_only";
pub const ERROR_CODE_REALM_FEDERATION_POLICY_CLOSED: &str = "realm_federation_policy_closed";
pub const ERROR_CODE_REALM_FEDERATION_POLICY_INVALID: &str = "realm_federation_policy_invalid";
pub const ERROR_CODE_REALM_FEDERATION_POLICY_QUARANTINE: &str =
    "realm_federation_policy_quarantine";
pub const ERROR_CODE_REALM_FEDERATION_POLICY_RESTRICTED: &str =
    "realm_federation_policy_restricted";
pub const ERROR_CODE_REALM_MODERATION_POLICY_DENIED: &str = "realm_moderation_policy_denied";
pub const ERROR_CODE_MIMI_E2EE_BOUNDARY_UNMARKED: &str = "mimi_e2ee_boundary_unmarked";
pub const ERROR_CODE_MIMI_PAYLOAD_DIGEST_MISMATCH: &str = "mimi_payload_digest_mismatch";
pub const ERROR_CODE_MIMI_PAYLOAD_INVALID: &str = "mimi_payload_invalid";
pub const ERROR_CODE_MIMI_REPORTER_RESOLUTION_REQUIRED: &str = "mimi_reporter_resolution_required";
pub const ERROR_CODE_STALE_PEER_STATE_UNAVAILABLE: &str = "stale_peer_state_unavailable";
pub const ERROR_CODE_FRANKING_TAMPERED: &str = "franking_tampered";
pub const ERROR_CODE_MLS_KEYPACKAGE_CLAIM_REQUEST_EXPIRED: &str =
    "mls_keypackage_claim_request_expired";
pub const ERROR_CODE_SNAPSHOT_CHUNK_DIGEST_MISMATCH: &str = "snapshot_chunk_digest_mismatch";

/// Canonical top-level error codes from error-code-registry.json, in registry order.
pub const KNOWN_ERROR_CODES: &[&str] = &[
    ERROR_CODE_BAD_JSON,
    ERROR_CODE_BAD_QUERY,
    ERROR_CODE_SCHEMA_VIOLATION,
    ERROR_CODE_MISSING_PARAM,
    ERROR_CODE_INVALID_PARAM,
    ERROR_CODE_INVALID_RESPONSE,
    ERROR_CODE_UNAUTHENTICATED,
    ERROR_CODE_AUTH_EXPIRED,
    ERROR_CODE_GRANT_ALREADY_CONSUMED,
    ERROR_CODE_SESSION_LOGGED_OUT,
    ERROR_CODE_AUDIENCE_MISMATCH,
    ERROR_CODE_SOFT_LOGGED_OUT,
    ERROR_CODE_ACCOUNT_LOCKED,
    ERROR_CODE_ACCOUNT_SUSPENDED,
    ERROR_CODE_ACCOUNT_DEACTIVATED,
    ERROR_CODE_ACCOUNT_ERASED,
    ERROR_CODE_DID_PROOF_REQUIRED,
    ERROR_CODE_INVALID_SIGNATURE,
    ERROR_CODE_HTTP_SIGNATURE_REQUIRED,
    ERROR_CODE_HTTP_SIGNATURE_INVALID,
    ERROR_CODE_SIGNATURE_WINDOW_INVALID,
    ERROR_CODE_DIRECTORY_NOT_AUTHORIZED,
    ERROR_CODE_ACCEPT_POLICY_DENIED,
    ERROR_CODE_SIGNATURE_INVALID,
    ERROR_CODE_SIGNATURE_STALE,
    ERROR_CODE_SOURCE_REFS_UNVERIFIABLE,
    ERROR_CODE_GOVERNANCE_KEY_INVALID,
    ERROR_CODE_TTL_OUT_OF_RANGE,
    ERROR_CODE_TAKEDOWN_IN_FORCE,
    ERROR_CODE_POLICY_REVISION_ROLLBACK,
    ERROR_CODE_CAPABILITY_DENIED,
    ERROR_CODE_REALM_FROZEN,
    ERROR_CODE_CLAIM_REQUIRED,
    ERROR_CODE_POLICY_VIOLATION,
    ERROR_CODE_POLICY_DENIED,
    ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED,
    ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED,
    ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE,
    ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE,
    ERROR_CODE_NOT_FOUND,
    ERROR_CODE_UNRECOGNIZED_ENDPOINT,
    ERROR_CODE_METHOD_NOT_ALLOWED,
    ERROR_CODE_CONFLICT,
    ERROR_CODE_CAS_CONFLICT,
    ERROR_CODE_CAUSAL_CONFLICT,
    ERROR_CODE_DEPENDENCY_MISSING,
    ERROR_CODE_DISCUSSION_TRACK_DISABLED,
    ERROR_CODE_EPOCH_MISMATCH,
    ERROR_CODE_DUPLICATE_CONFLICT,
    ERROR_CODE_RANK_EXHAUSTED,
    ERROR_CODE_HLC_LOGICAL_OVERFLOW,
    ERROR_CODE_PAYLOAD_TOO_LARGE,
    ERROR_CODE_DIGEST_MISMATCH,
    ERROR_CODE_AAD_DIGEST_MISMATCH,
    ERROR_CODE_PAYLOAD_DIGEST_MISMATCH,
    ERROR_CODE_KEY_UNAVAILABLE,
    ERROR_CODE_STATE_MISMATCH,
    ERROR_CODE_AUDIT_RECEIPT_INVALIDATED,
    ERROR_CODE_UNKNOWN_DID,
    ERROR_CODE_QUOTA_EXCEEDED,
    ERROR_CODE_LIMIT_EXCEEDED,
    ERROR_CODE_RATE_LIMITED,
    ERROR_CODE_TIMEOUT,
    ERROR_CODE_STALE_FRONTIER,
    ERROR_CODE_STALE_PEER,
    ERROR_CODE_AUTHORIZED_GRANT_REVOKED,
    ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH,
    ERROR_CODE_CURSOR_EXPIRED,
    ERROR_CODE_CURSOR_INTEGRITY_INVALID,
    ERROR_CODE_CURSOR_REVOKED,
    ERROR_CODE_CURSOR_UNRECOGNIZED,
    ERROR_CODE_ACTOR_SEQ_INVALID,
    ERROR_CODE_STALE_SEAL_REF,
    ERROR_CODE_SEAL_REF_UNKNOWN,
    ERROR_CODE_AUDIENCE_UNKNOWN,
    ERROR_CODE_BLOB_DIGEST_MISMATCH,
    ERROR_CODE_BLOB_EXPIRED,
    ERROR_CODE_BLOB_PRESIGN_INVALID,
    ERROR_CODE_BLOB_QUOTA_EXCEEDED,
    ERROR_CODE_CURSOR_INVALID,
    ERROR_CODE_DEVICE_ENROLLMENT_AUTHORITY_NOT_DESIGNATED,
    ERROR_CODE_DEVICE_UNKNOWN,
    ERROR_CODE_DID_ALREADY_EXISTS,
    ERROR_CODE_DID_NOT_FOUND,
    ERROR_CODE_DID_REVOKED,
    ERROR_CODE_FRONTIER_UNAVAILABLE,
    ERROR_CODE_HANDLE_UNVERIFIED,
    ERROR_CODE_KEY_REPLAY,
    ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED,
    ERROR_CODE_KEYPACKAGE_UNKNOWN,
    ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED,
    ERROR_CODE_POLICY_STALE,
    ERROR_CODE_POLICY_UNAVAILABLE,
    ERROR_CODE_PRINCIPAL_UNKNOWN,
    ERROR_CODE_PUSH_GATEWAY_UNREACHABLE,
    ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE,
    ERROR_CODE_PUSH_TARGET_UNKNOWN,
    ERROR_CODE_PUSH_TOKEN_INVALID,
    ERROR_CODE_PUSH_TOKEN_UNKNOWN,
    ERROR_CODE_QUARANTINE,
    ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED,
    ERROR_CODE_SNAPSHOT_UNAVAILABLE,
    ERROR_CODE_STREAM_DROPPED,
    ERROR_CODE_STREAM_RESYNC_REQUIRED,
    ERROR_CODE_TOO_LARGE,
    ERROR_CODE_UNSUPPORTED_DID_METHOD,
    ERROR_CODE_UNSUPPORTED_MEDIA_POLICY,
    ERROR_CODE_MEDIA_NEGOTIATION_FAILED,
    ERROR_CODE_UNSUPPORTED_FEATURE,
    ERROR_CODE_UNSUPPORTED_EVENT_KIND,
    ERROR_CODE_NOT_IMPLEMENTED,
    ERROR_CODE_PROJECTION_INCOMPLETE,
    ERROR_CODE_INTERNAL_ERROR,
    ERROR_CODE_TEMPORARILY_UNAVAILABLE,
    ERROR_CODE_SERVICE_UNAVAILABLE,
    ERROR_CODE_POLICY_COMBINATION_INVALID,
    ERROR_CODE_HISTORY_SHARING_POLICY_MISSING,
    ERROR_CODE_HISTORY_NOT_VISIBLE,
    ERROR_CODE_PREVIEW_POLICY_DENIED,
    ERROR_CODE_NOTARY_RECOVERY_MISSING,
    ERROR_CODE_UNSUPPORTED_LATTICE_TYPE,
    ERROR_CODE_PROFILE_UNSUPPORTED,
    ERROR_CODE_UNSUPPORTED_JOIN_RULE,
    ERROR_CODE_FAILED_PRECONDITION,
    ERROR_CODE_FAILED_PLANE,
    ERROR_CODE_FAILED_BOTTOM,
    ERROR_CODE_CONTACT_NOT_ACCEPTED,
    ERROR_CODE_CONTACT_CONSENT_MISSING,
    ERROR_CODE_PEER_UNRESOLVABLE,
    ERROR_CODE_CONTACT_REQUEST_NOT_PENDING,
    ERROR_CODE_CONTACT_REQUEST_EXPIRED,
    ERROR_CODE_UNSUPPORTED_DIGEST_ALGORITHM,
    ERROR_CODE_UNSUPPORTED_SIGNATURE_ALG,
    ERROR_CODE_UNSUPPORTED_HPKE_SUITE,
    ERROR_CODE_SEAL_INCOMPLETE,
    ERROR_CODE_FRANKING_PROOF_UNAVAILABLE,
    ERROR_CODE_TURN_CREDENTIAL_EXPIRED,
    ERROR_CODE_DELIVERY_BINDING_STALE,
    ERROR_CODE_DELIVERY_BINDING_HANDED_OVER,
    ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE,
    ERROR_CODE_HISTORICAL_ONLY,
    ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED,
    ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH,
    ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED,
    ERROR_CODE_APPLET_REVOKED,
    ERROR_CODE_INVALID_AVATAR_BLOB_REF,
    ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH,
    ERROR_CODE_SESSION_GRANT_NOT_FOUND,
    ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT,
    ERROR_CODE_REVIEWER_CAPABILITY_REVOKED,
    ERROR_CODE_NOT_MEMBER,
    ERROR_CODE_CALL_NOT_FOUND,
    ERROR_CODE_CALL_EXPIRED,
    ERROR_CODE_CALL_ALREADY_ANSWERED,
    ERROR_CODE_MEDIA_PERMISSION_DENIED,
    ERROR_CODE_ICE_CONFIG_DENIED,
    ERROR_CODE_SFU_NOT_ALLOWED,
    ERROR_CODE_E2EE_REQUIRED,
    ERROR_CODE_RECORDING_DENIED,
    ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF,
    ERROR_CODE_MORPH_TYPE_IMMUTABLE,
    ERROR_CODE_APPLET_ALREADY_REGISTERED,
    ERROR_CODE_APPLET_EFFECTIVE_SCOPE_MISMATCH,
    ERROR_CODE_APPLET_INSTALL_PROJECTION_INCOMPLETE,
    ERROR_CODE_APPLET_INSTALL_REQUIRED,
    ERROR_CODE_APPLET_NAMESPACE_CONFLICT,
    ERROR_CODE_APPLET_PACKAGE_EXPIRED,
    ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISMATCH,
    ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISSING,
    ERROR_CODE_APPLET_REGISTRATION_EPOCH_SIGNING_KEY_MISMATCH,
    ERROR_CODE_APPLET_TRANSACTION_IN_PROGRESS,
    ERROR_CODE_BOT_ACTOR_REVOKED,
    ERROR_CODE_ENCLAVE_NO_UPSTREAM_PROXY_FOR_EXTERNAL,
    ERROR_CODE_ENCLAVE_NOT_TRUSTED,
    ERROR_CODE_EXTERNAL_INVITE_ACTOR_MISMATCH,
    ERROR_CODE_EXTERNAL_USER_NO_MAIN_ACCESS,
    ERROR_CODE_UPSTREAM_UNAVAILABLE,
    ERROR_CODE_AGENT_PROVISION_FANOUT_UNAVAILABLE,
    ERROR_CODE_CANNOT_PAIR_CURRENT_DEVICE,
    ERROR_CODE_CROSS_SIGNING_STATE_MISSING,
    ERROR_CODE_DEVICE_ALREADY_AUTHORIZED,
    ERROR_CODE_DEVICE_NOT_AUTHORIZED,
    ERROR_CODE_DEVICE_REVOKED,
    ERROR_CODE_DISCOVERY_FAILED,
    ERROR_CODE_FIRST_BACKUP_GATE_UNSATISFIED,
    ERROR_CODE_FRESH_DEVICE_SCOPE_VIOLATION,
    ERROR_CODE_INVALID_AVATAR_URL,
    ERROR_CODE_RECOVERY_AUTHORIZATION_DEVICE_MISMATCH,
    ERROR_CODE_RECOVERY_AUTHORIZATION_PRINCIPAL_MISMATCH,
    ERROR_CODE_RECOVERY_AUTHORIZATION_SESSION_MISMATCH,
    ERROR_CODE_RECOVERY_CONTROL_EVENT_KIND_MISMATCH,
    ERROR_CODE_RECOVERY_CONTROL_EVENT_NOT_FOUND,
    ERROR_CODE_RECOVERY_LIST_UPDATE_DEVICE_MISMATCH,
    ERROR_CODE_RECOVERY_LIST_UPDATE_PRINCIPAL_MISMATCH,
    ERROR_CODE_RECOVERY_POLICY_CONFLICT,
    ERROR_CODE_RECOVERY_POLICY_DEVICE_NOT_AUTHORIZED,
    ERROR_CODE_RECOVERY_POLICY_ID_MISMATCH,
    ERROR_CODE_RECOVERY_POLICY_MISSING,
    ERROR_CODE_RECOVERY_POLICY_REVOKED,
    ERROR_CODE_RECOVERY_POLICY_TRUST_DOMAIN_MISMATCH,
    ERROR_CODE_RECOVERY_POLICY_VERSION_MISMATCH,
    ERROR_CODE_RECOVERY_PROOF_AUTHORITY_INVALID,
    ERROR_CODE_RECOVERY_PROOF_KIND_NOT_ALLOWED,
    ERROR_CODE_RECOVERY_PROOF_KIND_UNIMPLEMENTED,
    ERROR_CODE_RECOVERY_RECEIPT_CONFLICT,
    ERROR_CODE_RECOVERY_SESSION_CONFLICT,
    ERROR_CODE_RECOVERY_SESSION_ID_REUSED,
    ERROR_CODE_RECOVERY_SESSION_NOT_PENDING,
    ERROR_CODE_FEDERATION_ACTOR_ORIGIN_REJECTED,
    ERROR_CODE_FEDERATION_INTEROP_TRACK_ONLY,
    ERROR_CODE_FEDERATION_ORIGIN_DENIED,
    ERROR_CODE_FEDERATION_PRIVATE_READ_RAIL_LOCAL_ONLY,
    ERROR_CODE_REALM_FEDERATION_POLICY_CLOSED,
    ERROR_CODE_REALM_FEDERATION_POLICY_INVALID,
    ERROR_CODE_REALM_FEDERATION_POLICY_QUARANTINE,
    ERROR_CODE_REALM_FEDERATION_POLICY_RESTRICTED,
    ERROR_CODE_REALM_MODERATION_POLICY_DENIED,
    ERROR_CODE_MIMI_E2EE_BOUNDARY_UNMARKED,
    ERROR_CODE_MIMI_PAYLOAD_DIGEST_MISMATCH,
    ERROR_CODE_MIMI_PAYLOAD_INVALID,
    ERROR_CODE_MIMI_REPORTER_RESOLUTION_REQUIRED,
    ERROR_CODE_STALE_PEER_STATE_UNAVAILABLE,
    ERROR_CODE_FRANKING_TAMPERED,
    ERROR_CODE_MLS_KEYPACKAGE_CLAIM_REQUEST_EXPIRED,
    ERROR_CODE_SNAPSHOT_CHUNK_DIGEST_MISMATCH,
];
