use super::codes::*;
use super::status::error_code_http_status;

/// Strongly typed view over the canonical top-level error-code registry.
///
/// `#[non_exhaustive]`: the registry gains codes as the spec evolves and this
/// enum is regenerated to match; downstream `match` expressions MUST carry a
/// `_` arm and treat unrecognised codes fail-closed (as a denial/error, never
/// as an allow).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum ErrorCode {
    BadJson,
    BadQuery,
    SchemaViolation,
    DuplicateClauseClaim,
    KeyTransparencyProofMissing,
    MissingParam,
    InvalidParam,
    InvalidResponse,
    Unauthenticated,
    AuthExpired,
    GrantAlreadyConsumed,
    SessionLoggedOut,
    AudienceMismatch,
    SoftLoggedOut,
    AccountLocked,
    AccountSuspended,
    AccountDeactivated,
    AccountErased,
    DidProofRequired,
    InvalidSignature,
    HttpSignatureRequired,
    HttpSignatureInvalid,
    SignatureWindowInvalid,
    DirectoryNotAuthorized,
    AcceptPolicyDenied,
    SignatureInvalid,
    SignatureStale,
    SourceRefsUnverifiable,
    GovernanceKeyInvalid,
    TtlOutOfRange,
    TakedownInForce,
    PolicyRevisionRollback,
    CapabilityDenied,
    RealmFrozen,
    ClaimRequired,
    PolicyViolation,
    PolicyDenied,
    ReadReceiptComplianceFloorViolated,
    EphemeralKindNotPermitted,
    EphemeralTtlOutOfRange,
    EphemeralChannelUnavailable,
    NotFound,
    UnrecognizedEndpoint,
    MethodNotAllowed,
    Conflict,
    CasConflict,
    FailedBottom,
    FailedPlane,
    CausalConflict,
    DependencyMissing,
    DiscussionTrackDisabled,
    EpochMismatch,
    DuplicateConflict,
    RankExhausted,
    HlcLogicalOverflow,
    PayloadTooLarge,
    DigestMismatch,
    AadDigestMismatch,
    PayloadDigestMismatch,
    KeyUnavailable,
    StateMismatch,
    AuditReceiptInvalidated,
    UnknownDid,
    QuotaExceeded,
    LimitExceeded,
    RateLimited,
    Timeout,
    StaleFrontier,
    StalePeer,
    AuthorizedGrantRevoked,
    DeviceRecoverySskGenerationMismatch,
    CursorExpired,
    CursorIntegrityInvalid,
    CursorRevoked,
    CursorUnrecognized,
    ActorSeqInvalid,
    StaleSealRef,
    SealRefUnknown,
    AudienceUnknown,
    BlobDigestMismatch,
    BlobExpired,
    BlobPresignInvalid,
    BlobQuotaExceeded,
    CursorInvalid,
    DeviceEnrollmentAuthorityNotDesignated,
    DeviceUnknown,
    DidAlreadyExists,
    DidNotFound,
    DidRevoked,
    FrontierUnavailable,
    HandleUnverified,
    KeyReplay,
    KeypackageAlreadyConsumed,
    KeypackageUnknown,
    OneTimeKeysExhausted,
    PolicyStale,
    PolicyUnavailable,
    PrincipalUnknown,
    PushGatewayUnreachable,
    PushPayloadTooLarge,
    PushTargetUnknown,
    PushTokenInvalid,
    PushTokenUnknown,
    Quarantine,
    SnapshotAuthorityUnverified,
    SnapshotUnavailable,
    StreamDropped,
    StreamResyncRequired,
    TooLarge,
    UnsupportedDidMethod,
    UnsupportedMediaPolicy,
    MediaNegotiationFailed,
    UnsupportedFeature,
    UnsupportedEventKind,
    NotImplemented,
    ProjectionIncomplete,
    InternalError,
    TemporarilyUnavailable,
    ServiceUnavailable,
    PolicyCombinationInvalid,
    HistorySharingPolicyMissing,
    HistoryNotVisible,
    PreviewPolicyDenied,
    NotaryRecoveryMissing,
    UnsupportedLatticeType,
    ProfileUnsupported,
    UnsupportedJoinRule,
    FailedPrecondition,
    DirectConversationUnavailable,
    PeerUnresolvable,
    ContactRequestNotPending,
    ContactRequestExpired,
    UnsupportedDigestAlgorithm,
    UnsupportedSignatureAlg,
    UnsupportedHpkeSuite,
    SealIncomplete,
    FrankingProofUnavailable,
    TurnCredentialExpired,
    DeliveryBindingStale,
    DeliveryBindingHandedOver,
    DeliveryBindingUnresolvable,
    HistoricalOnly,
    AppletRegistrationUnauthorized,
    AppletInstallPlanMismatch,
    AppletE2eeJoinUnauthorized,
    AppletRevoked,
    InvalidAvatarBlobRef,
    UnsupportedProfilePatchPath,
    SessionGrantNotFound,
    SessionRevokeSelectorConflict,
    ReviewerCapabilityRevoked,
    NotMember,
    CallNotFound,
    CallExpired,
    CallAlreadyAnswered,
    MediaPermissionDenied,
    IceConfigDenied,
    SfuNotAllowed,
    E2eeRequired,
    RecordingDenied,
    MorphProfileWidensSchemaRef,
    MorphTypeImmutable,
    AppletAlreadyRegistered,
    AppletEffectiveScopeMismatch,
    AppletInstallProjectionIncomplete,
    AppletInstallRequired,
    AppletNamespaceConflict,
    AppletPackageExpired,
    AppletRegistrationEpochEvidenceMismatch,
    AppletRegistrationEpochEvidenceMissing,
    AppletRegistrationEpochSigningKeyMismatch,
    AppletTransactionInProgress,
    BotActorRevoked,
    EnclaveNoUpstreamProxyForExternal,
    EnclaveNotTrusted,
    ExternalInviteActorMismatch,
    ExternalUserNoMainAccess,
    UpstreamUnavailable,
    AgentProvisionFanoutUnavailable,
    CannotPairCurrentDevice,
    CrossSigningStateMissing,
    DeviceAlreadyAuthorized,
    DeviceNotAuthorized,
    DeviceRevoked,
    DiscoveryFailed,
    FirstBackupGateUnsatisfied,
    FreshDeviceScopeViolation,
    InvalidAvatarUrl,
    RecoveryAuthorizationDeviceMismatch,
    RecoveryAuthorizationPrincipalMismatch,
    RecoveryAuthorizationSessionMismatch,
    RecoveryControlEventKindMismatch,
    RecoveryControlEventNotFound,
    RecoveryListUpdateDeviceMismatch,
    RecoveryListUpdatePrincipalMismatch,
    RecoveryPolicyConflict,
    RecoveryPolicyDeviceNotAuthorized,
    RecoveryPolicyIdMismatch,
    RecoveryPolicyMissing,
    RecoveryPolicyRevoked,
    RecoveryPolicyTrustDomainMismatch,
    RecoveryPolicyVersionMismatch,
    RecoveryProofAuthorityInvalid,
    RecoveryProofKindNotAllowed,
    RecoveryProofKindUnimplemented,
    RecoveryReceiptConflict,
    RecoverySessionConflict,
    RecoverySessionIdReused,
    RecoverySessionNotPending,
    FederationActorOriginRejected,
    FederationInteropTrackOnly,
    FederationOriginDenied,
    FederationPrivateReadRailLocalOnly,
    RealmFederationPolicyClosed,
    RealmFederationPolicyInvalid,
    RealmFederationPolicyQuarantine,
    RealmFederationPolicyRestricted,
    RealmModerationPolicyDenied,
    MimiE2eeBoundaryUnmarked,
    MimiPayloadDigestMismatch,
    MimiPayloadInvalid,
    MimiReporterResolutionRequired,
    StalePeerStateUnavailable,
    FrankingTampered,
    MlsKeypackageClaimRequestExpired,
    SnapshotChunkDigestMismatch,
}

impl ErrorCode {
    pub const ALL: [Self; 226] = [
        Self::BadJson,
        Self::BadQuery,
        Self::SchemaViolation,
        Self::DuplicateClauseClaim,
        Self::KeyTransparencyProofMissing,
        Self::MissingParam,
        Self::InvalidParam,
        Self::InvalidResponse,
        Self::Unauthenticated,
        Self::AuthExpired,
        Self::GrantAlreadyConsumed,
        Self::SessionLoggedOut,
        Self::AudienceMismatch,
        Self::SoftLoggedOut,
        Self::AccountLocked,
        Self::AccountSuspended,
        Self::AccountDeactivated,
        Self::AccountErased,
        Self::DidProofRequired,
        Self::InvalidSignature,
        Self::HttpSignatureRequired,
        Self::HttpSignatureInvalid,
        Self::SignatureWindowInvalid,
        Self::DirectoryNotAuthorized,
        Self::AcceptPolicyDenied,
        Self::SignatureInvalid,
        Self::SignatureStale,
        Self::SourceRefsUnverifiable,
        Self::GovernanceKeyInvalid,
        Self::TtlOutOfRange,
        Self::TakedownInForce,
        Self::PolicyRevisionRollback,
        Self::CapabilityDenied,
        Self::RealmFrozen,
        Self::ClaimRequired,
        Self::PolicyViolation,
        Self::PolicyDenied,
        Self::ReadReceiptComplianceFloorViolated,
        Self::EphemeralKindNotPermitted,
        Self::EphemeralTtlOutOfRange,
        Self::EphemeralChannelUnavailable,
        Self::NotFound,
        Self::UnrecognizedEndpoint,
        Self::MethodNotAllowed,
        Self::Conflict,
        Self::CasConflict,
        Self::FailedBottom,
        Self::FailedPlane,
        Self::CausalConflict,
        Self::DependencyMissing,
        Self::DiscussionTrackDisabled,
        Self::EpochMismatch,
        Self::DuplicateConflict,
        Self::RankExhausted,
        Self::HlcLogicalOverflow,
        Self::PayloadTooLarge,
        Self::DigestMismatch,
        Self::AadDigestMismatch,
        Self::PayloadDigestMismatch,
        Self::KeyUnavailable,
        Self::StateMismatch,
        Self::AuditReceiptInvalidated,
        Self::UnknownDid,
        Self::QuotaExceeded,
        Self::LimitExceeded,
        Self::RateLimited,
        Self::Timeout,
        Self::StaleFrontier,
        Self::StalePeer,
        Self::AuthorizedGrantRevoked,
        Self::DeviceRecoverySskGenerationMismatch,
        Self::CursorExpired,
        Self::CursorIntegrityInvalid,
        Self::CursorRevoked,
        Self::CursorUnrecognized,
        Self::ActorSeqInvalid,
        Self::StaleSealRef,
        Self::SealRefUnknown,
        Self::AudienceUnknown,
        Self::BlobDigestMismatch,
        Self::BlobExpired,
        Self::BlobPresignInvalid,
        Self::BlobQuotaExceeded,
        Self::CursorInvalid,
        Self::DeviceEnrollmentAuthorityNotDesignated,
        Self::DeviceUnknown,
        Self::DidAlreadyExists,
        Self::DidNotFound,
        Self::DidRevoked,
        Self::FrontierUnavailable,
        Self::HandleUnverified,
        Self::KeyReplay,
        Self::KeypackageAlreadyConsumed,
        Self::KeypackageUnknown,
        Self::OneTimeKeysExhausted,
        Self::PolicyStale,
        Self::PolicyUnavailable,
        Self::PrincipalUnknown,
        Self::PushGatewayUnreachable,
        Self::PushPayloadTooLarge,
        Self::PushTargetUnknown,
        Self::PushTokenInvalid,
        Self::PushTokenUnknown,
        Self::Quarantine,
        Self::SnapshotAuthorityUnverified,
        Self::SnapshotUnavailable,
        Self::StreamDropped,
        Self::StreamResyncRequired,
        Self::TooLarge,
        Self::UnsupportedDidMethod,
        Self::UnsupportedMediaPolicy,
        Self::MediaNegotiationFailed,
        Self::UnsupportedFeature,
        Self::UnsupportedEventKind,
        Self::NotImplemented,
        Self::ProjectionIncomplete,
        Self::InternalError,
        Self::TemporarilyUnavailable,
        Self::ServiceUnavailable,
        Self::PolicyCombinationInvalid,
        Self::HistorySharingPolicyMissing,
        Self::HistoryNotVisible,
        Self::PreviewPolicyDenied,
        Self::NotaryRecoveryMissing,
        Self::UnsupportedLatticeType,
        Self::ProfileUnsupported,
        Self::UnsupportedJoinRule,
        Self::FailedPrecondition,
        Self::DirectConversationUnavailable,
        Self::PeerUnresolvable,
        Self::ContactRequestNotPending,
        Self::ContactRequestExpired,
        Self::UnsupportedDigestAlgorithm,
        Self::UnsupportedSignatureAlg,
        Self::UnsupportedHpkeSuite,
        Self::SealIncomplete,
        Self::FrankingProofUnavailable,
        Self::TurnCredentialExpired,
        Self::DeliveryBindingStale,
        Self::DeliveryBindingHandedOver,
        Self::DeliveryBindingUnresolvable,
        Self::HistoricalOnly,
        Self::AppletRegistrationUnauthorized,
        Self::AppletInstallPlanMismatch,
        Self::AppletE2eeJoinUnauthorized,
        Self::AppletRevoked,
        Self::InvalidAvatarBlobRef,
        Self::UnsupportedProfilePatchPath,
        Self::SessionGrantNotFound,
        Self::SessionRevokeSelectorConflict,
        Self::ReviewerCapabilityRevoked,
        Self::NotMember,
        Self::CallNotFound,
        Self::CallExpired,
        Self::CallAlreadyAnswered,
        Self::MediaPermissionDenied,
        Self::IceConfigDenied,
        Self::SfuNotAllowed,
        Self::E2eeRequired,
        Self::RecordingDenied,
        Self::MorphProfileWidensSchemaRef,
        Self::MorphTypeImmutable,
        Self::AppletAlreadyRegistered,
        Self::AppletEffectiveScopeMismatch,
        Self::AppletInstallProjectionIncomplete,
        Self::AppletInstallRequired,
        Self::AppletNamespaceConflict,
        Self::AppletPackageExpired,
        Self::AppletRegistrationEpochEvidenceMismatch,
        Self::AppletRegistrationEpochEvidenceMissing,
        Self::AppletRegistrationEpochSigningKeyMismatch,
        Self::AppletTransactionInProgress,
        Self::BotActorRevoked,
        Self::EnclaveNoUpstreamProxyForExternal,
        Self::EnclaveNotTrusted,
        Self::ExternalInviteActorMismatch,
        Self::ExternalUserNoMainAccess,
        Self::UpstreamUnavailable,
        Self::AgentProvisionFanoutUnavailable,
        Self::CannotPairCurrentDevice,
        Self::CrossSigningStateMissing,
        Self::DeviceAlreadyAuthorized,
        Self::DeviceNotAuthorized,
        Self::DeviceRevoked,
        Self::DiscoveryFailed,
        Self::FirstBackupGateUnsatisfied,
        Self::FreshDeviceScopeViolation,
        Self::InvalidAvatarUrl,
        Self::RecoveryAuthorizationDeviceMismatch,
        Self::RecoveryAuthorizationPrincipalMismatch,
        Self::RecoveryAuthorizationSessionMismatch,
        Self::RecoveryControlEventKindMismatch,
        Self::RecoveryControlEventNotFound,
        Self::RecoveryListUpdateDeviceMismatch,
        Self::RecoveryListUpdatePrincipalMismatch,
        Self::RecoveryPolicyConflict,
        Self::RecoveryPolicyDeviceNotAuthorized,
        Self::RecoveryPolicyIdMismatch,
        Self::RecoveryPolicyMissing,
        Self::RecoveryPolicyRevoked,
        Self::RecoveryPolicyTrustDomainMismatch,
        Self::RecoveryPolicyVersionMismatch,
        Self::RecoveryProofAuthorityInvalid,
        Self::RecoveryProofKindNotAllowed,
        Self::RecoveryProofKindUnimplemented,
        Self::RecoveryReceiptConflict,
        Self::RecoverySessionConflict,
        Self::RecoverySessionIdReused,
        Self::RecoverySessionNotPending,
        Self::FederationActorOriginRejected,
        Self::FederationInteropTrackOnly,
        Self::FederationOriginDenied,
        Self::FederationPrivateReadRailLocalOnly,
        Self::RealmFederationPolicyClosed,
        Self::RealmFederationPolicyInvalid,
        Self::RealmFederationPolicyQuarantine,
        Self::RealmFederationPolicyRestricted,
        Self::RealmModerationPolicyDenied,
        Self::MimiE2eeBoundaryUnmarked,
        Self::MimiPayloadDigestMismatch,
        Self::MimiPayloadInvalid,
        Self::MimiReporterResolutionRequired,
        Self::StalePeerStateUnavailable,
        Self::FrankingTampered,
        Self::MlsKeypackageClaimRequestExpired,
        Self::SnapshotChunkDigestMismatch,
    ];

    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BadJson => ERROR_CODE_BAD_JSON,
            Self::BadQuery => ERROR_CODE_BAD_QUERY,
            Self::SchemaViolation => ERROR_CODE_SCHEMA_VIOLATION,
            Self::DuplicateClauseClaim => ERROR_CODE_DUPLICATE_CLAUSE_CLAIM,
            Self::KeyTransparencyProofMissing => ERROR_CODE_KEY_TRANSPARENCY_PROOF_MISSING,
            Self::MissingParam => ERROR_CODE_MISSING_PARAM,
            Self::InvalidParam => ERROR_CODE_INVALID_PARAM,
            Self::InvalidResponse => ERROR_CODE_INVALID_RESPONSE,
            Self::Unauthenticated => ERROR_CODE_UNAUTHENTICATED,
            Self::AuthExpired => ERROR_CODE_AUTH_EXPIRED,
            Self::GrantAlreadyConsumed => ERROR_CODE_GRANT_ALREADY_CONSUMED,
            Self::SessionLoggedOut => ERROR_CODE_SESSION_LOGGED_OUT,
            Self::AudienceMismatch => ERROR_CODE_AUDIENCE_MISMATCH,
            Self::SoftLoggedOut => ERROR_CODE_SOFT_LOGGED_OUT,
            Self::AccountLocked => ERROR_CODE_ACCOUNT_LOCKED,
            Self::AccountSuspended => ERROR_CODE_ACCOUNT_SUSPENDED,
            Self::AccountDeactivated => ERROR_CODE_ACCOUNT_DEACTIVATED,
            Self::AccountErased => ERROR_CODE_ACCOUNT_ERASED,
            Self::DidProofRequired => ERROR_CODE_DID_PROOF_REQUIRED,
            Self::InvalidSignature => ERROR_CODE_INVALID_SIGNATURE,
            Self::HttpSignatureRequired => ERROR_CODE_HTTP_SIGNATURE_REQUIRED,
            Self::HttpSignatureInvalid => ERROR_CODE_HTTP_SIGNATURE_INVALID,
            Self::SignatureWindowInvalid => ERROR_CODE_SIGNATURE_WINDOW_INVALID,
            Self::DirectoryNotAuthorized => ERROR_CODE_DIRECTORY_NOT_AUTHORIZED,
            Self::AcceptPolicyDenied => ERROR_CODE_ACCEPT_POLICY_DENIED,
            Self::SignatureInvalid => ERROR_CODE_SIGNATURE_INVALID,
            Self::SignatureStale => ERROR_CODE_SIGNATURE_STALE,
            Self::SourceRefsUnverifiable => ERROR_CODE_SOURCE_REFS_UNVERIFIABLE,
            Self::GovernanceKeyInvalid => ERROR_CODE_GOVERNANCE_KEY_INVALID,
            Self::TtlOutOfRange => ERROR_CODE_TTL_OUT_OF_RANGE,
            Self::TakedownInForce => ERROR_CODE_TAKEDOWN_IN_FORCE,
            Self::PolicyRevisionRollback => ERROR_CODE_POLICY_REVISION_ROLLBACK,
            Self::CapabilityDenied => ERROR_CODE_CAPABILITY_DENIED,
            Self::RealmFrozen => ERROR_CODE_REALM_FROZEN,
            Self::ClaimRequired => ERROR_CODE_CLAIM_REQUIRED,
            Self::PolicyViolation => ERROR_CODE_POLICY_VIOLATION,
            Self::PolicyDenied => ERROR_CODE_POLICY_DENIED,
            Self::ReadReceiptComplianceFloorViolated => {
                ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED
            }
            Self::EphemeralKindNotPermitted => ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED,
            Self::EphemeralTtlOutOfRange => ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE,
            Self::EphemeralChannelUnavailable => ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE,
            Self::NotFound => ERROR_CODE_NOT_FOUND,
            Self::UnrecognizedEndpoint => ERROR_CODE_UNRECOGNIZED_ENDPOINT,
            Self::MethodNotAllowed => ERROR_CODE_METHOD_NOT_ALLOWED,
            Self::Conflict => ERROR_CODE_CONFLICT,
            Self::CasConflict => ERROR_CODE_CAS_CONFLICT,
            Self::FailedBottom => ERROR_CODE_FAILED_BOTTOM,
            Self::FailedPlane => ERROR_CODE_FAILED_PLANE,
            Self::CausalConflict => ERROR_CODE_CAUSAL_CONFLICT,
            Self::DependencyMissing => ERROR_CODE_DEPENDENCY_MISSING,
            Self::DiscussionTrackDisabled => ERROR_CODE_DISCUSSION_TRACK_DISABLED,
            Self::EpochMismatch => ERROR_CODE_EPOCH_MISMATCH,
            Self::DuplicateConflict => ERROR_CODE_DUPLICATE_CONFLICT,
            Self::RankExhausted => ERROR_CODE_RANK_EXHAUSTED,
            Self::HlcLogicalOverflow => ERROR_CODE_HLC_LOGICAL_OVERFLOW,
            Self::PayloadTooLarge => ERROR_CODE_PAYLOAD_TOO_LARGE,
            Self::DigestMismatch => ERROR_CODE_DIGEST_MISMATCH,
            Self::AadDigestMismatch => ERROR_CODE_AAD_DIGEST_MISMATCH,
            Self::PayloadDigestMismatch => ERROR_CODE_PAYLOAD_DIGEST_MISMATCH,
            Self::KeyUnavailable => ERROR_CODE_KEY_UNAVAILABLE,
            Self::StateMismatch => ERROR_CODE_STATE_MISMATCH,
            Self::AuditReceiptInvalidated => ERROR_CODE_AUDIT_RECEIPT_INVALIDATED,
            Self::UnknownDid => ERROR_CODE_UNKNOWN_DID,
            Self::QuotaExceeded => ERROR_CODE_QUOTA_EXCEEDED,
            Self::LimitExceeded => ERROR_CODE_LIMIT_EXCEEDED,
            Self::RateLimited => ERROR_CODE_RATE_LIMITED,
            Self::Timeout => ERROR_CODE_TIMEOUT,
            Self::StaleFrontier => ERROR_CODE_STALE_FRONTIER,
            Self::StalePeer => ERROR_CODE_STALE_PEER,
            Self::AuthorizedGrantRevoked => ERROR_CODE_AUTHORIZED_GRANT_REVOKED,
            Self::DeviceRecoverySskGenerationMismatch => {
                ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH
            }
            Self::CursorExpired => ERROR_CODE_CURSOR_EXPIRED,
            Self::CursorIntegrityInvalid => ERROR_CODE_CURSOR_INTEGRITY_INVALID,
            Self::CursorRevoked => ERROR_CODE_CURSOR_REVOKED,
            Self::CursorUnrecognized => ERROR_CODE_CURSOR_UNRECOGNIZED,
            Self::ActorSeqInvalid => ERROR_CODE_ACTOR_SEQ_INVALID,
            Self::StaleSealRef => ERROR_CODE_STALE_SEAL_REF,
            Self::SealRefUnknown => ERROR_CODE_SEAL_REF_UNKNOWN,
            Self::AudienceUnknown => ERROR_CODE_AUDIENCE_UNKNOWN,
            Self::BlobDigestMismatch => ERROR_CODE_BLOB_DIGEST_MISMATCH,
            Self::BlobExpired => ERROR_CODE_BLOB_EXPIRED,
            Self::BlobPresignInvalid => ERROR_CODE_BLOB_PRESIGN_INVALID,
            Self::BlobQuotaExceeded => ERROR_CODE_BLOB_QUOTA_EXCEEDED,
            Self::CursorInvalid => ERROR_CODE_CURSOR_INVALID,
            Self::DeviceEnrollmentAuthorityNotDesignated => {
                ERROR_CODE_DEVICE_ENROLLMENT_AUTHORITY_NOT_DESIGNATED
            }
            Self::DeviceUnknown => ERROR_CODE_DEVICE_UNKNOWN,
            Self::DidAlreadyExists => ERROR_CODE_DID_ALREADY_EXISTS,
            Self::DidNotFound => ERROR_CODE_DID_NOT_FOUND,
            Self::DidRevoked => ERROR_CODE_DID_REVOKED,
            Self::FrontierUnavailable => ERROR_CODE_FRONTIER_UNAVAILABLE,
            Self::HandleUnverified => ERROR_CODE_HANDLE_UNVERIFIED,
            Self::KeyReplay => ERROR_CODE_KEY_REPLAY,
            Self::KeypackageAlreadyConsumed => ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED,
            Self::KeypackageUnknown => ERROR_CODE_KEYPACKAGE_UNKNOWN,
            Self::OneTimeKeysExhausted => ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED,
            Self::PolicyStale => ERROR_CODE_POLICY_STALE,
            Self::PolicyUnavailable => ERROR_CODE_POLICY_UNAVAILABLE,
            Self::PrincipalUnknown => ERROR_CODE_PRINCIPAL_UNKNOWN,
            Self::PushGatewayUnreachable => ERROR_CODE_PUSH_GATEWAY_UNREACHABLE,
            Self::PushPayloadTooLarge => ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE,
            Self::PushTargetUnknown => ERROR_CODE_PUSH_TARGET_UNKNOWN,
            Self::PushTokenInvalid => ERROR_CODE_PUSH_TOKEN_INVALID,
            Self::PushTokenUnknown => ERROR_CODE_PUSH_TOKEN_UNKNOWN,
            Self::Quarantine => ERROR_CODE_QUARANTINE,
            Self::SnapshotAuthorityUnverified => ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED,
            Self::SnapshotUnavailable => ERROR_CODE_SNAPSHOT_UNAVAILABLE,
            Self::StreamDropped => ERROR_CODE_STREAM_DROPPED,
            Self::StreamResyncRequired => ERROR_CODE_STREAM_RESYNC_REQUIRED,
            Self::TooLarge => ERROR_CODE_TOO_LARGE,
            Self::UnsupportedDidMethod => ERROR_CODE_UNSUPPORTED_DID_METHOD,
            Self::UnsupportedMediaPolicy => ERROR_CODE_UNSUPPORTED_MEDIA_POLICY,
            Self::MediaNegotiationFailed => ERROR_CODE_MEDIA_NEGOTIATION_FAILED,
            Self::UnsupportedFeature => ERROR_CODE_UNSUPPORTED_FEATURE,
            Self::UnsupportedEventKind => ERROR_CODE_UNSUPPORTED_EVENT_KIND,
            Self::NotImplemented => ERROR_CODE_NOT_IMPLEMENTED,
            Self::ProjectionIncomplete => ERROR_CODE_PROJECTION_INCOMPLETE,
            Self::InternalError => ERROR_CODE_INTERNAL_ERROR,
            Self::TemporarilyUnavailable => ERROR_CODE_TEMPORARILY_UNAVAILABLE,
            Self::ServiceUnavailable => ERROR_CODE_SERVICE_UNAVAILABLE,
            Self::PolicyCombinationInvalid => ERROR_CODE_POLICY_COMBINATION_INVALID,
            Self::HistorySharingPolicyMissing => ERROR_CODE_HISTORY_SHARING_POLICY_MISSING,
            Self::HistoryNotVisible => ERROR_CODE_HISTORY_NOT_VISIBLE,
            Self::PreviewPolicyDenied => ERROR_CODE_PREVIEW_POLICY_DENIED,
            Self::NotaryRecoveryMissing => ERROR_CODE_NOTARY_RECOVERY_MISSING,
            Self::UnsupportedLatticeType => ERROR_CODE_UNSUPPORTED_LATTICE_TYPE,
            Self::ProfileUnsupported => ERROR_CODE_PROFILE_UNSUPPORTED,
            Self::UnsupportedJoinRule => ERROR_CODE_UNSUPPORTED_JOIN_RULE,
            Self::FailedPrecondition => ERROR_CODE_FAILED_PRECONDITION,
            Self::DirectConversationUnavailable => ERROR_CODE_DIRECT_CONVERSATION_UNAVAILABLE,
            Self::PeerUnresolvable => ERROR_CODE_PEER_UNRESOLVABLE,
            Self::ContactRequestNotPending => ERROR_CODE_CONTACT_REQUEST_NOT_PENDING,
            Self::ContactRequestExpired => ERROR_CODE_CONTACT_REQUEST_EXPIRED,
            Self::UnsupportedDigestAlgorithm => ERROR_CODE_UNSUPPORTED_DIGEST_ALGORITHM,
            Self::UnsupportedSignatureAlg => ERROR_CODE_UNSUPPORTED_SIGNATURE_ALG,
            Self::UnsupportedHpkeSuite => ERROR_CODE_UNSUPPORTED_HPKE_SUITE,
            Self::SealIncomplete => ERROR_CODE_SEAL_INCOMPLETE,
            Self::FrankingProofUnavailable => ERROR_CODE_FRANKING_PROOF_UNAVAILABLE,
            Self::TurnCredentialExpired => ERROR_CODE_TURN_CREDENTIAL_EXPIRED,
            Self::DeliveryBindingStale => ERROR_CODE_DELIVERY_BINDING_STALE,
            Self::DeliveryBindingHandedOver => ERROR_CODE_DELIVERY_BINDING_HANDED_OVER,
            Self::DeliveryBindingUnresolvable => ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE,
            Self::HistoricalOnly => ERROR_CODE_HISTORICAL_ONLY,
            Self::AppletRegistrationUnauthorized => ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED,
            Self::AppletInstallPlanMismatch => ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH,
            Self::AppletE2eeJoinUnauthorized => ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED,
            Self::AppletRevoked => ERROR_CODE_APPLET_REVOKED,
            Self::InvalidAvatarBlobRef => ERROR_CODE_INVALID_AVATAR_BLOB_REF,
            Self::UnsupportedProfilePatchPath => ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH,
            Self::SessionGrantNotFound => ERROR_CODE_SESSION_GRANT_NOT_FOUND,
            Self::SessionRevokeSelectorConflict => ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT,
            Self::ReviewerCapabilityRevoked => ERROR_CODE_REVIEWER_CAPABILITY_REVOKED,
            Self::NotMember => ERROR_CODE_NOT_MEMBER,
            Self::CallNotFound => ERROR_CODE_CALL_NOT_FOUND,
            Self::CallExpired => ERROR_CODE_CALL_EXPIRED,
            Self::CallAlreadyAnswered => ERROR_CODE_CALL_ALREADY_ANSWERED,
            Self::MediaPermissionDenied => ERROR_CODE_MEDIA_PERMISSION_DENIED,
            Self::IceConfigDenied => ERROR_CODE_ICE_CONFIG_DENIED,
            Self::SfuNotAllowed => ERROR_CODE_SFU_NOT_ALLOWED,
            Self::E2eeRequired => ERROR_CODE_E2EE_REQUIRED,
            Self::RecordingDenied => ERROR_CODE_RECORDING_DENIED,
            Self::MorphProfileWidensSchemaRef => ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF,
            Self::MorphTypeImmutable => ERROR_CODE_MORPH_TYPE_IMMUTABLE,
            Self::AppletAlreadyRegistered => ERROR_CODE_APPLET_ALREADY_REGISTERED,
            Self::AppletEffectiveScopeMismatch => ERROR_CODE_APPLET_EFFECTIVE_SCOPE_MISMATCH,
            Self::AppletInstallProjectionIncomplete => {
                ERROR_CODE_APPLET_INSTALL_PROJECTION_INCOMPLETE
            }
            Self::AppletInstallRequired => ERROR_CODE_APPLET_INSTALL_REQUIRED,
            Self::AppletNamespaceConflict => ERROR_CODE_APPLET_NAMESPACE_CONFLICT,
            Self::AppletPackageExpired => ERROR_CODE_APPLET_PACKAGE_EXPIRED,
            Self::AppletRegistrationEpochEvidenceMismatch => {
                ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISMATCH
            }
            Self::AppletRegistrationEpochEvidenceMissing => {
                ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISSING
            }
            Self::AppletRegistrationEpochSigningKeyMismatch => {
                ERROR_CODE_APPLET_REGISTRATION_EPOCH_SIGNING_KEY_MISMATCH
            }
            Self::AppletTransactionInProgress => ERROR_CODE_APPLET_TRANSACTION_IN_PROGRESS,
            Self::BotActorRevoked => ERROR_CODE_BOT_ACTOR_REVOKED,
            Self::EnclaveNoUpstreamProxyForExternal => {
                ERROR_CODE_ENCLAVE_NO_UPSTREAM_PROXY_FOR_EXTERNAL
            }
            Self::EnclaveNotTrusted => ERROR_CODE_ENCLAVE_NOT_TRUSTED,
            Self::ExternalInviteActorMismatch => ERROR_CODE_EXTERNAL_INVITE_ACTOR_MISMATCH,
            Self::ExternalUserNoMainAccess => ERROR_CODE_EXTERNAL_USER_NO_MAIN_ACCESS,
            Self::UpstreamUnavailable => ERROR_CODE_UPSTREAM_UNAVAILABLE,
            Self::AgentProvisionFanoutUnavailable => ERROR_CODE_AGENT_PROVISION_FANOUT_UNAVAILABLE,
            Self::CannotPairCurrentDevice => ERROR_CODE_CANNOT_PAIR_CURRENT_DEVICE,
            Self::CrossSigningStateMissing => ERROR_CODE_CROSS_SIGNING_STATE_MISSING,
            Self::DeviceAlreadyAuthorized => ERROR_CODE_DEVICE_ALREADY_AUTHORIZED,
            Self::DeviceNotAuthorized => ERROR_CODE_DEVICE_NOT_AUTHORIZED,
            Self::DeviceRevoked => ERROR_CODE_DEVICE_REVOKED,
            Self::DiscoveryFailed => ERROR_CODE_DISCOVERY_FAILED,
            Self::FirstBackupGateUnsatisfied => ERROR_CODE_FIRST_BACKUP_GATE_UNSATISFIED,
            Self::FreshDeviceScopeViolation => ERROR_CODE_FRESH_DEVICE_SCOPE_VIOLATION,
            Self::InvalidAvatarUrl => ERROR_CODE_INVALID_AVATAR_URL,
            Self::RecoveryAuthorizationDeviceMismatch => {
                ERROR_CODE_RECOVERY_AUTHORIZATION_DEVICE_MISMATCH
            }
            Self::RecoveryAuthorizationPrincipalMismatch => {
                ERROR_CODE_RECOVERY_AUTHORIZATION_PRINCIPAL_MISMATCH
            }
            Self::RecoveryAuthorizationSessionMismatch => {
                ERROR_CODE_RECOVERY_AUTHORIZATION_SESSION_MISMATCH
            }
            Self::RecoveryControlEventKindMismatch => {
                ERROR_CODE_RECOVERY_CONTROL_EVENT_KIND_MISMATCH
            }
            Self::RecoveryControlEventNotFound => ERROR_CODE_RECOVERY_CONTROL_EVENT_NOT_FOUND,
            Self::RecoveryListUpdateDeviceMismatch => {
                ERROR_CODE_RECOVERY_LIST_UPDATE_DEVICE_MISMATCH
            }
            Self::RecoveryListUpdatePrincipalMismatch => {
                ERROR_CODE_RECOVERY_LIST_UPDATE_PRINCIPAL_MISMATCH
            }
            Self::RecoveryPolicyConflict => ERROR_CODE_RECOVERY_POLICY_CONFLICT,
            Self::RecoveryPolicyDeviceNotAuthorized => {
                ERROR_CODE_RECOVERY_POLICY_DEVICE_NOT_AUTHORIZED
            }
            Self::RecoveryPolicyIdMismatch => ERROR_CODE_RECOVERY_POLICY_ID_MISMATCH,
            Self::RecoveryPolicyMissing => ERROR_CODE_RECOVERY_POLICY_MISSING,
            Self::RecoveryPolicyRevoked => ERROR_CODE_RECOVERY_POLICY_REVOKED,
            Self::RecoveryPolicyTrustDomainMismatch => {
                ERROR_CODE_RECOVERY_POLICY_TRUST_DOMAIN_MISMATCH
            }
            Self::RecoveryPolicyVersionMismatch => ERROR_CODE_RECOVERY_POLICY_VERSION_MISMATCH,
            Self::RecoveryProofAuthorityInvalid => ERROR_CODE_RECOVERY_PROOF_AUTHORITY_INVALID,
            Self::RecoveryProofKindNotAllowed => ERROR_CODE_RECOVERY_PROOF_KIND_NOT_ALLOWED,
            Self::RecoveryProofKindUnimplemented => ERROR_CODE_RECOVERY_PROOF_KIND_UNIMPLEMENTED,
            Self::RecoveryReceiptConflict => ERROR_CODE_RECOVERY_RECEIPT_CONFLICT,
            Self::RecoverySessionConflict => ERROR_CODE_RECOVERY_SESSION_CONFLICT,
            Self::RecoverySessionIdReused => ERROR_CODE_RECOVERY_SESSION_ID_REUSED,
            Self::RecoverySessionNotPending => ERROR_CODE_RECOVERY_SESSION_NOT_PENDING,
            Self::FederationActorOriginRejected => ERROR_CODE_FEDERATION_ACTOR_ORIGIN_REJECTED,
            Self::FederationInteropTrackOnly => ERROR_CODE_FEDERATION_INTEROP_TRACK_ONLY,
            Self::FederationOriginDenied => ERROR_CODE_FEDERATION_ORIGIN_DENIED,
            Self::FederationPrivateReadRailLocalOnly => {
                ERROR_CODE_FEDERATION_PRIVATE_READ_RAIL_LOCAL_ONLY
            }
            Self::RealmFederationPolicyClosed => ERROR_CODE_REALM_FEDERATION_POLICY_CLOSED,
            Self::RealmFederationPolicyInvalid => ERROR_CODE_REALM_FEDERATION_POLICY_INVALID,
            Self::RealmFederationPolicyQuarantine => ERROR_CODE_REALM_FEDERATION_POLICY_QUARANTINE,
            Self::RealmFederationPolicyRestricted => ERROR_CODE_REALM_FEDERATION_POLICY_RESTRICTED,
            Self::RealmModerationPolicyDenied => ERROR_CODE_REALM_MODERATION_POLICY_DENIED,
            Self::MimiE2eeBoundaryUnmarked => ERROR_CODE_MIMI_E2EE_BOUNDARY_UNMARKED,
            Self::MimiPayloadDigestMismatch => ERROR_CODE_MIMI_PAYLOAD_DIGEST_MISMATCH,
            Self::MimiPayloadInvalid => ERROR_CODE_MIMI_PAYLOAD_INVALID,
            Self::MimiReporterResolutionRequired => ERROR_CODE_MIMI_REPORTER_RESOLUTION_REQUIRED,
            Self::StalePeerStateUnavailable => ERROR_CODE_STALE_PEER_STATE_UNAVAILABLE,
            Self::FrankingTampered => ERROR_CODE_FRANKING_TAMPERED,
            Self::MlsKeypackageClaimRequestExpired => {
                ERROR_CODE_MLS_KEYPACKAGE_CLAIM_REQUEST_EXPIRED
            }
            Self::SnapshotChunkDigestMismatch => ERROR_CODE_SNAPSHOT_CHUNK_DIGEST_MISMATCH,
        }
    }

    pub fn from_wire(value: &str) -> Option<Self> {
        Some(match value {
            ERROR_CODE_BAD_JSON => Self::BadJson,
            ERROR_CODE_BAD_QUERY => Self::BadQuery,
            ERROR_CODE_SCHEMA_VIOLATION => Self::SchemaViolation,
            ERROR_CODE_DUPLICATE_CLAUSE_CLAIM => Self::DuplicateClauseClaim,
            ERROR_CODE_KEY_TRANSPARENCY_PROOF_MISSING => Self::KeyTransparencyProofMissing,
            ERROR_CODE_MISSING_PARAM => Self::MissingParam,
            ERROR_CODE_INVALID_PARAM => Self::InvalidParam,
            ERROR_CODE_INVALID_RESPONSE => Self::InvalidResponse,
            ERROR_CODE_UNAUTHENTICATED => Self::Unauthenticated,
            ERROR_CODE_AUTH_EXPIRED => Self::AuthExpired,
            ERROR_CODE_GRANT_ALREADY_CONSUMED => Self::GrantAlreadyConsumed,
            ERROR_CODE_SESSION_LOGGED_OUT => Self::SessionLoggedOut,
            ERROR_CODE_AUDIENCE_MISMATCH => Self::AudienceMismatch,
            ERROR_CODE_SOFT_LOGGED_OUT => Self::SoftLoggedOut,
            ERROR_CODE_ACCOUNT_LOCKED => Self::AccountLocked,
            ERROR_CODE_ACCOUNT_SUSPENDED => Self::AccountSuspended,
            ERROR_CODE_ACCOUNT_DEACTIVATED => Self::AccountDeactivated,
            ERROR_CODE_ACCOUNT_ERASED => Self::AccountErased,
            ERROR_CODE_DID_PROOF_REQUIRED => Self::DidProofRequired,
            ERROR_CODE_INVALID_SIGNATURE => Self::InvalidSignature,
            ERROR_CODE_HTTP_SIGNATURE_REQUIRED => Self::HttpSignatureRequired,
            ERROR_CODE_HTTP_SIGNATURE_INVALID => Self::HttpSignatureInvalid,
            ERROR_CODE_SIGNATURE_WINDOW_INVALID => Self::SignatureWindowInvalid,
            ERROR_CODE_DIRECTORY_NOT_AUTHORIZED => Self::DirectoryNotAuthorized,
            ERROR_CODE_ACCEPT_POLICY_DENIED => Self::AcceptPolicyDenied,
            ERROR_CODE_SIGNATURE_INVALID => Self::SignatureInvalid,
            ERROR_CODE_SIGNATURE_STALE => Self::SignatureStale,
            ERROR_CODE_SOURCE_REFS_UNVERIFIABLE => Self::SourceRefsUnverifiable,
            ERROR_CODE_GOVERNANCE_KEY_INVALID => Self::GovernanceKeyInvalid,
            ERROR_CODE_TTL_OUT_OF_RANGE => Self::TtlOutOfRange,
            ERROR_CODE_TAKEDOWN_IN_FORCE => Self::TakedownInForce,
            ERROR_CODE_POLICY_REVISION_ROLLBACK => Self::PolicyRevisionRollback,
            ERROR_CODE_CAPABILITY_DENIED => Self::CapabilityDenied,
            ERROR_CODE_REALM_FROZEN => Self::RealmFrozen,
            ERROR_CODE_CLAIM_REQUIRED => Self::ClaimRequired,
            ERROR_CODE_POLICY_VIOLATION => Self::PolicyViolation,
            ERROR_CODE_POLICY_DENIED => Self::PolicyDenied,
            ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED => {
                Self::ReadReceiptComplianceFloorViolated
            }
            ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED => Self::EphemeralKindNotPermitted,
            ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE => Self::EphemeralTtlOutOfRange,
            ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE => Self::EphemeralChannelUnavailable,
            ERROR_CODE_NOT_FOUND => Self::NotFound,
            ERROR_CODE_UNRECOGNIZED_ENDPOINT => Self::UnrecognizedEndpoint,
            ERROR_CODE_METHOD_NOT_ALLOWED => Self::MethodNotAllowed,
            ERROR_CODE_CONFLICT => Self::Conflict,
            ERROR_CODE_CAS_CONFLICT => Self::CasConflict,
            ERROR_CODE_FAILED_BOTTOM => Self::FailedBottom,
            ERROR_CODE_FAILED_PLANE => Self::FailedPlane,
            ERROR_CODE_CAUSAL_CONFLICT => Self::CausalConflict,
            ERROR_CODE_DEPENDENCY_MISSING => Self::DependencyMissing,
            ERROR_CODE_DISCUSSION_TRACK_DISABLED => Self::DiscussionTrackDisabled,
            ERROR_CODE_EPOCH_MISMATCH => Self::EpochMismatch,
            ERROR_CODE_DUPLICATE_CONFLICT => Self::DuplicateConflict,
            ERROR_CODE_RANK_EXHAUSTED => Self::RankExhausted,
            ERROR_CODE_HLC_LOGICAL_OVERFLOW => Self::HlcLogicalOverflow,
            ERROR_CODE_PAYLOAD_TOO_LARGE => Self::PayloadTooLarge,
            ERROR_CODE_DIGEST_MISMATCH => Self::DigestMismatch,
            ERROR_CODE_AAD_DIGEST_MISMATCH => Self::AadDigestMismatch,
            ERROR_CODE_PAYLOAD_DIGEST_MISMATCH => Self::PayloadDigestMismatch,
            ERROR_CODE_KEY_UNAVAILABLE => Self::KeyUnavailable,
            ERROR_CODE_STATE_MISMATCH => Self::StateMismatch,
            ERROR_CODE_AUDIT_RECEIPT_INVALIDATED => Self::AuditReceiptInvalidated,
            ERROR_CODE_UNKNOWN_DID => Self::UnknownDid,
            ERROR_CODE_QUOTA_EXCEEDED => Self::QuotaExceeded,
            ERROR_CODE_LIMIT_EXCEEDED => Self::LimitExceeded,
            ERROR_CODE_RATE_LIMITED => Self::RateLimited,
            ERROR_CODE_TIMEOUT => Self::Timeout,
            ERROR_CODE_STALE_FRONTIER => Self::StaleFrontier,
            ERROR_CODE_STALE_PEER => Self::StalePeer,
            ERROR_CODE_AUTHORIZED_GRANT_REVOKED => Self::AuthorizedGrantRevoked,
            ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH => {
                Self::DeviceRecoverySskGenerationMismatch
            }
            ERROR_CODE_CURSOR_EXPIRED => Self::CursorExpired,
            ERROR_CODE_CURSOR_INTEGRITY_INVALID => Self::CursorIntegrityInvalid,
            ERROR_CODE_CURSOR_REVOKED => Self::CursorRevoked,
            ERROR_CODE_CURSOR_UNRECOGNIZED => Self::CursorUnrecognized,
            ERROR_CODE_ACTOR_SEQ_INVALID => Self::ActorSeqInvalid,
            ERROR_CODE_STALE_SEAL_REF => Self::StaleSealRef,
            ERROR_CODE_SEAL_REF_UNKNOWN => Self::SealRefUnknown,
            ERROR_CODE_AUDIENCE_UNKNOWN => Self::AudienceUnknown,
            ERROR_CODE_BLOB_DIGEST_MISMATCH => Self::BlobDigestMismatch,
            ERROR_CODE_BLOB_EXPIRED => Self::BlobExpired,
            ERROR_CODE_BLOB_PRESIGN_INVALID => Self::BlobPresignInvalid,
            ERROR_CODE_BLOB_QUOTA_EXCEEDED => Self::BlobQuotaExceeded,
            ERROR_CODE_CURSOR_INVALID => Self::CursorInvalid,
            ERROR_CODE_DEVICE_ENROLLMENT_AUTHORITY_NOT_DESIGNATED => {
                Self::DeviceEnrollmentAuthorityNotDesignated
            }
            ERROR_CODE_DEVICE_UNKNOWN => Self::DeviceUnknown,
            ERROR_CODE_DID_ALREADY_EXISTS => Self::DidAlreadyExists,
            ERROR_CODE_DID_NOT_FOUND => Self::DidNotFound,
            ERROR_CODE_DID_REVOKED => Self::DidRevoked,
            ERROR_CODE_FRONTIER_UNAVAILABLE => Self::FrontierUnavailable,
            ERROR_CODE_HANDLE_UNVERIFIED => Self::HandleUnverified,
            ERROR_CODE_KEY_REPLAY => Self::KeyReplay,
            ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED => Self::KeypackageAlreadyConsumed,
            ERROR_CODE_KEYPACKAGE_UNKNOWN => Self::KeypackageUnknown,
            ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED => Self::OneTimeKeysExhausted,
            ERROR_CODE_POLICY_STALE => Self::PolicyStale,
            ERROR_CODE_POLICY_UNAVAILABLE => Self::PolicyUnavailable,
            ERROR_CODE_PRINCIPAL_UNKNOWN => Self::PrincipalUnknown,
            ERROR_CODE_PUSH_GATEWAY_UNREACHABLE => Self::PushGatewayUnreachable,
            ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE => Self::PushPayloadTooLarge,
            ERROR_CODE_PUSH_TARGET_UNKNOWN => Self::PushTargetUnknown,
            ERROR_CODE_PUSH_TOKEN_INVALID => Self::PushTokenInvalid,
            ERROR_CODE_PUSH_TOKEN_UNKNOWN => Self::PushTokenUnknown,
            ERROR_CODE_QUARANTINE => Self::Quarantine,
            ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED => Self::SnapshotAuthorityUnverified,
            ERROR_CODE_SNAPSHOT_UNAVAILABLE => Self::SnapshotUnavailable,
            ERROR_CODE_STREAM_DROPPED => Self::StreamDropped,
            ERROR_CODE_STREAM_RESYNC_REQUIRED => Self::StreamResyncRequired,
            ERROR_CODE_TOO_LARGE => Self::TooLarge,
            ERROR_CODE_UNSUPPORTED_DID_METHOD => Self::UnsupportedDidMethod,
            ERROR_CODE_UNSUPPORTED_MEDIA_POLICY => Self::UnsupportedMediaPolicy,
            ERROR_CODE_MEDIA_NEGOTIATION_FAILED => Self::MediaNegotiationFailed,
            ERROR_CODE_UNSUPPORTED_FEATURE => Self::UnsupportedFeature,
            ERROR_CODE_UNSUPPORTED_EVENT_KIND => Self::UnsupportedEventKind,
            ERROR_CODE_NOT_IMPLEMENTED => Self::NotImplemented,
            ERROR_CODE_PROJECTION_INCOMPLETE => Self::ProjectionIncomplete,
            ERROR_CODE_INTERNAL_ERROR => Self::InternalError,
            ERROR_CODE_TEMPORARILY_UNAVAILABLE => Self::TemporarilyUnavailable,
            ERROR_CODE_SERVICE_UNAVAILABLE => Self::ServiceUnavailable,
            ERROR_CODE_POLICY_COMBINATION_INVALID => Self::PolicyCombinationInvalid,
            ERROR_CODE_HISTORY_SHARING_POLICY_MISSING => Self::HistorySharingPolicyMissing,
            ERROR_CODE_HISTORY_NOT_VISIBLE => Self::HistoryNotVisible,
            ERROR_CODE_PREVIEW_POLICY_DENIED => Self::PreviewPolicyDenied,
            ERROR_CODE_NOTARY_RECOVERY_MISSING => Self::NotaryRecoveryMissing,
            ERROR_CODE_UNSUPPORTED_LATTICE_TYPE => Self::UnsupportedLatticeType,
            ERROR_CODE_PROFILE_UNSUPPORTED => Self::ProfileUnsupported,
            ERROR_CODE_UNSUPPORTED_JOIN_RULE => Self::UnsupportedJoinRule,
            ERROR_CODE_FAILED_PRECONDITION => Self::FailedPrecondition,
            ERROR_CODE_DIRECT_CONVERSATION_UNAVAILABLE => Self::DirectConversationUnavailable,
            ERROR_CODE_PEER_UNRESOLVABLE => Self::PeerUnresolvable,
            ERROR_CODE_CONTACT_REQUEST_NOT_PENDING => Self::ContactRequestNotPending,
            ERROR_CODE_CONTACT_REQUEST_EXPIRED => Self::ContactRequestExpired,
            ERROR_CODE_UNSUPPORTED_DIGEST_ALGORITHM => Self::UnsupportedDigestAlgorithm,
            ERROR_CODE_UNSUPPORTED_SIGNATURE_ALG => Self::UnsupportedSignatureAlg,
            ERROR_CODE_UNSUPPORTED_HPKE_SUITE => Self::UnsupportedHpkeSuite,
            ERROR_CODE_SEAL_INCOMPLETE => Self::SealIncomplete,
            ERROR_CODE_FRANKING_PROOF_UNAVAILABLE => Self::FrankingProofUnavailable,
            ERROR_CODE_TURN_CREDENTIAL_EXPIRED => Self::TurnCredentialExpired,
            ERROR_CODE_DELIVERY_BINDING_STALE => Self::DeliveryBindingStale,
            ERROR_CODE_DELIVERY_BINDING_HANDED_OVER => Self::DeliveryBindingHandedOver,
            ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE => Self::DeliveryBindingUnresolvable,
            ERROR_CODE_HISTORICAL_ONLY => Self::HistoricalOnly,
            ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED => Self::AppletRegistrationUnauthorized,
            ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH => Self::AppletInstallPlanMismatch,
            ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED => Self::AppletE2eeJoinUnauthorized,
            ERROR_CODE_APPLET_REVOKED => Self::AppletRevoked,
            ERROR_CODE_INVALID_AVATAR_BLOB_REF => Self::InvalidAvatarBlobRef,
            ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH => Self::UnsupportedProfilePatchPath,
            ERROR_CODE_SESSION_GRANT_NOT_FOUND => Self::SessionGrantNotFound,
            ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT => Self::SessionRevokeSelectorConflict,
            ERROR_CODE_REVIEWER_CAPABILITY_REVOKED => Self::ReviewerCapabilityRevoked,
            ERROR_CODE_NOT_MEMBER => Self::NotMember,
            ERROR_CODE_CALL_NOT_FOUND => Self::CallNotFound,
            ERROR_CODE_CALL_EXPIRED => Self::CallExpired,
            ERROR_CODE_CALL_ALREADY_ANSWERED => Self::CallAlreadyAnswered,
            ERROR_CODE_MEDIA_PERMISSION_DENIED => Self::MediaPermissionDenied,
            ERROR_CODE_ICE_CONFIG_DENIED => Self::IceConfigDenied,
            ERROR_CODE_SFU_NOT_ALLOWED => Self::SfuNotAllowed,
            ERROR_CODE_E2EE_REQUIRED => Self::E2eeRequired,
            ERROR_CODE_RECORDING_DENIED => Self::RecordingDenied,
            ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF => Self::MorphProfileWidensSchemaRef,
            ERROR_CODE_MORPH_TYPE_IMMUTABLE => Self::MorphTypeImmutable,
            ERROR_CODE_APPLET_ALREADY_REGISTERED => Self::AppletAlreadyRegistered,
            ERROR_CODE_APPLET_EFFECTIVE_SCOPE_MISMATCH => Self::AppletEffectiveScopeMismatch,
            ERROR_CODE_APPLET_INSTALL_PROJECTION_INCOMPLETE => {
                Self::AppletInstallProjectionIncomplete
            }
            ERROR_CODE_APPLET_INSTALL_REQUIRED => Self::AppletInstallRequired,
            ERROR_CODE_APPLET_NAMESPACE_CONFLICT => Self::AppletNamespaceConflict,
            ERROR_CODE_APPLET_PACKAGE_EXPIRED => Self::AppletPackageExpired,
            ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISMATCH => {
                Self::AppletRegistrationEpochEvidenceMismatch
            }
            ERROR_CODE_APPLET_REGISTRATION_EPOCH_EVIDENCE_MISSING => {
                Self::AppletRegistrationEpochEvidenceMissing
            }
            ERROR_CODE_APPLET_REGISTRATION_EPOCH_SIGNING_KEY_MISMATCH => {
                Self::AppletRegistrationEpochSigningKeyMismatch
            }
            ERROR_CODE_APPLET_TRANSACTION_IN_PROGRESS => Self::AppletTransactionInProgress,
            ERROR_CODE_BOT_ACTOR_REVOKED => Self::BotActorRevoked,
            ERROR_CODE_ENCLAVE_NO_UPSTREAM_PROXY_FOR_EXTERNAL => {
                Self::EnclaveNoUpstreamProxyForExternal
            }
            ERROR_CODE_ENCLAVE_NOT_TRUSTED => Self::EnclaveNotTrusted,
            ERROR_CODE_EXTERNAL_INVITE_ACTOR_MISMATCH => Self::ExternalInviteActorMismatch,
            ERROR_CODE_EXTERNAL_USER_NO_MAIN_ACCESS => Self::ExternalUserNoMainAccess,
            ERROR_CODE_UPSTREAM_UNAVAILABLE => Self::UpstreamUnavailable,
            ERROR_CODE_AGENT_PROVISION_FANOUT_UNAVAILABLE => Self::AgentProvisionFanoutUnavailable,
            ERROR_CODE_CANNOT_PAIR_CURRENT_DEVICE => Self::CannotPairCurrentDevice,
            ERROR_CODE_CROSS_SIGNING_STATE_MISSING => Self::CrossSigningStateMissing,
            ERROR_CODE_DEVICE_ALREADY_AUTHORIZED => Self::DeviceAlreadyAuthorized,
            ERROR_CODE_DEVICE_NOT_AUTHORIZED => Self::DeviceNotAuthorized,
            ERROR_CODE_DEVICE_REVOKED => Self::DeviceRevoked,
            ERROR_CODE_DISCOVERY_FAILED => Self::DiscoveryFailed,
            ERROR_CODE_FIRST_BACKUP_GATE_UNSATISFIED => Self::FirstBackupGateUnsatisfied,
            ERROR_CODE_FRESH_DEVICE_SCOPE_VIOLATION => Self::FreshDeviceScopeViolation,
            ERROR_CODE_INVALID_AVATAR_URL => Self::InvalidAvatarUrl,
            ERROR_CODE_RECOVERY_AUTHORIZATION_DEVICE_MISMATCH => {
                Self::RecoveryAuthorizationDeviceMismatch
            }
            ERROR_CODE_RECOVERY_AUTHORIZATION_PRINCIPAL_MISMATCH => {
                Self::RecoveryAuthorizationPrincipalMismatch
            }
            ERROR_CODE_RECOVERY_AUTHORIZATION_SESSION_MISMATCH => {
                Self::RecoveryAuthorizationSessionMismatch
            }
            ERROR_CODE_RECOVERY_CONTROL_EVENT_KIND_MISMATCH => {
                Self::RecoveryControlEventKindMismatch
            }
            ERROR_CODE_RECOVERY_CONTROL_EVENT_NOT_FOUND => Self::RecoveryControlEventNotFound,
            ERROR_CODE_RECOVERY_LIST_UPDATE_DEVICE_MISMATCH => {
                Self::RecoveryListUpdateDeviceMismatch
            }
            ERROR_CODE_RECOVERY_LIST_UPDATE_PRINCIPAL_MISMATCH => {
                Self::RecoveryListUpdatePrincipalMismatch
            }
            ERROR_CODE_RECOVERY_POLICY_CONFLICT => Self::RecoveryPolicyConflict,
            ERROR_CODE_RECOVERY_POLICY_DEVICE_NOT_AUTHORIZED => {
                Self::RecoveryPolicyDeviceNotAuthorized
            }
            ERROR_CODE_RECOVERY_POLICY_ID_MISMATCH => Self::RecoveryPolicyIdMismatch,
            ERROR_CODE_RECOVERY_POLICY_MISSING => Self::RecoveryPolicyMissing,
            ERROR_CODE_RECOVERY_POLICY_REVOKED => Self::RecoveryPolicyRevoked,
            ERROR_CODE_RECOVERY_POLICY_TRUST_DOMAIN_MISMATCH => {
                Self::RecoveryPolicyTrustDomainMismatch
            }
            ERROR_CODE_RECOVERY_POLICY_VERSION_MISMATCH => Self::RecoveryPolicyVersionMismatch,
            ERROR_CODE_RECOVERY_PROOF_AUTHORITY_INVALID => Self::RecoveryProofAuthorityInvalid,
            ERROR_CODE_RECOVERY_PROOF_KIND_NOT_ALLOWED => Self::RecoveryProofKindNotAllowed,
            ERROR_CODE_RECOVERY_PROOF_KIND_UNIMPLEMENTED => Self::RecoveryProofKindUnimplemented,
            ERROR_CODE_RECOVERY_RECEIPT_CONFLICT => Self::RecoveryReceiptConflict,
            ERROR_CODE_RECOVERY_SESSION_CONFLICT => Self::RecoverySessionConflict,
            ERROR_CODE_RECOVERY_SESSION_ID_REUSED => Self::RecoverySessionIdReused,
            ERROR_CODE_RECOVERY_SESSION_NOT_PENDING => Self::RecoverySessionNotPending,
            ERROR_CODE_FEDERATION_ACTOR_ORIGIN_REJECTED => Self::FederationActorOriginRejected,
            ERROR_CODE_FEDERATION_INTEROP_TRACK_ONLY => Self::FederationInteropTrackOnly,
            ERROR_CODE_FEDERATION_ORIGIN_DENIED => Self::FederationOriginDenied,
            ERROR_CODE_FEDERATION_PRIVATE_READ_RAIL_LOCAL_ONLY => {
                Self::FederationPrivateReadRailLocalOnly
            }
            ERROR_CODE_REALM_FEDERATION_POLICY_CLOSED => Self::RealmFederationPolicyClosed,
            ERROR_CODE_REALM_FEDERATION_POLICY_INVALID => Self::RealmFederationPolicyInvalid,
            ERROR_CODE_REALM_FEDERATION_POLICY_QUARANTINE => Self::RealmFederationPolicyQuarantine,
            ERROR_CODE_REALM_FEDERATION_POLICY_RESTRICTED => Self::RealmFederationPolicyRestricted,
            ERROR_CODE_REALM_MODERATION_POLICY_DENIED => Self::RealmModerationPolicyDenied,
            ERROR_CODE_MIMI_E2EE_BOUNDARY_UNMARKED => Self::MimiE2eeBoundaryUnmarked,
            ERROR_CODE_MIMI_PAYLOAD_DIGEST_MISMATCH => Self::MimiPayloadDigestMismatch,
            ERROR_CODE_MIMI_PAYLOAD_INVALID => Self::MimiPayloadInvalid,
            ERROR_CODE_MIMI_REPORTER_RESOLUTION_REQUIRED => Self::MimiReporterResolutionRequired,
            ERROR_CODE_STALE_PEER_STATE_UNAVAILABLE => Self::StalePeerStateUnavailable,
            ERROR_CODE_FRANKING_TAMPERED => Self::FrankingTampered,
            ERROR_CODE_MLS_KEYPACKAGE_CLAIM_REQUEST_EXPIRED => {
                Self::MlsKeypackageClaimRequestExpired
            }
            ERROR_CODE_SNAPSHOT_CHUNK_DIGEST_MISMATCH => Self::SnapshotChunkDigestMismatch,
            _ => return None,
        })
    }

    pub fn http_status(self) -> u16 {
        match error_code_http_status(self.as_str()) {
            Some(status) => status,
            None => {
                // The variant table and the status table drifted apart. That
                // is a generator bug, not a runtime condition: surface it
                // loudly in debug builds and degrade to 500 in release
                // instead of panicking in the error-reporting path.
                debug_assert!(
                    false,
                    "error code `{}` is missing from the HTTP status registry",
                    self.as_str()
                );
                500
            }
        }
    }
}
