use super::codes::*;
use super::status::error_code_http_status;

// ── Typed `ErrorCode` enum ────────────────────────────────────────────────
//
// Strongly-typed view over [`KNOWN_ERROR_CODES`]. Mirrors the wire-form
// snake_case strings exactly through [`ErrorCode::as_str`] / [`ErrorCode::from_wire`].
//
// Adding a new error code to the registry MUST be paired with a new
// [`ErrorCode`] variant + an entry in [`ErrorCode::ALL`]. The
// `error_code_enum_matches_registry` test in this module catches drift
// in either direction.

/// Strongly-typed view over the canonical Cokret error code registry.
///
/// Every variant corresponds to one entry in [`KNOWN_ERROR_CODES`].
/// Round-trip helpers:
///
/// - [`ErrorCode::as_str`] → wire-form snake_case string (same value as the matching `ERROR_CODE_*`
///   constant).
/// - [`ErrorCode::from_wire`] → parse a wire string back into the typed variant. Returns `None` for
///   any code not in the registry.
/// - [`ErrorCode::http_status`] → registered HTTP status, identical to what
///   [`error_code_http_status`] returns for the same wire string.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum ErrorCode {
    BadJson,
    BadQuery,
    SchemaViolation,
    MissingParam,
    InvalidParam,
    InvalidResponse,
    Unauthenticated,
    AuthExpired,
    SoftLoggedOut,
    InvalidSignature,
    CapabilityDenied,
    RealmFrozen,
    ClaimRequired,
    NotFound,
    UnrecognizedEndpoint,
    MethodNotAllowed,
    Conflict,
    CasConflict,
    CausalConflict,
    DependencyMissing,
    DiscussionTrackDisabled,
    /// C14 / read-receipts §2.5: Sync Service drops `ck.receipt.read` when
    /// the effective Space `disclosure="disabled"` policy is in force.
    PolicyViolation,
    EpochMismatch,
    DuplicateConflict,
    RankExhausted,
    HlcLogicalOverflow,
    PayloadTooLarge,
    DigestMismatch,
    AadDigestMismatch,
    PayloadDigestMismatch,
    KeyUnavailable,
    StateMismatch,
    AuditReceiptInvalidated,
    UnknownDid,
    QuotaExceeded,
    LimitExceeded,
    RateLimited,
    Timeout,
    StaleFrontier,
    CursorExpired,
    UnsupportedFeature,
    UnsupportedEventKind,
    ProjectionIncomplete,
    InternalError,
    TemporarilyUnavailable,
    PolicyCombinationInvalid,
    HistorySharingPolicyMissing,
    HistoryNotVisible,
    PreviewPolicyDenied,
    NotaryRecoveryMissing,
    UnsupportedLatticeType,
    ProfileUnsupported,
    CursorIntegrityInvalid,
    FailedPrecondition,
    UnsupportedHash,
    SealIncomplete,
    FrankingProofUnavailable,
    TurnCredentialExpired,
    StalePeer,
    // ── Round R2/R3 (2026-05-20).
    RelaxedWindowExceedsCeiling,
    E2eeRelaxedDisallowedInComplianceProfile,
    CrossDomainReplayRejected,
    ResetEventIdMismatch,
    AppealOverturnMissingLift,
    AppealSelfReviewForbidden,
    RealmTerminalState,
    AuditPurposeMismatch,
    LegalHoldActive,
    BlobRedacted,
    MediaPlaintextServiceNotAuthorised,
    MlsGovernanceBindingStale,
    ExpiredInviteToken,
    LateRecoveryRejectedMembership,
    // ── Round 4 (2026-05-20).
    DeliveryBindingStale,
    DeliveryBindingHandedOver,
    HistoricalOnly,
    // ── Directory ingest (2026-05-22).
    DirectoryNotAuthorized,
    AcceptPolicyDenied,
    SignatureInvalid,
    SignatureStale,
    SourceRefsUnverifiable,
    GovernanceKeyInvalid,
    TtlOutOfRange,
    TakedownInForce,
    PolicyRevisionRollback,
    // ── Spec main (2026-05-23).
    DidProofRequired,
    ReadReceiptComplianceFloorViolated,
    EphemeralKindNotPermitted,
    EphemeralTtlOutOfRange,
    EphemeralChannelUnavailable,
    AuthorizedGrantRevoked,
    DeviceRecoverySskGenerationMismatch,
    CursorRevoked,
    // ── Key-backup hardening (B-C, spec head 37ce729).
    SeriesChainBroken,
    SeriesSeqNotMonotonic,
    SeriesPredecessorNotFound,
    RecoveryPolicyMismatch,
    ShareCommitmentMismatch,
    BackupFrontierStale,
    BackupPostResetStale,
    RecoveryEvidenceUnbound,
    UnsupportedAeadProfile,
    AttestationMissing,
    // ── R3 spec-sync (2026-05-27, cokret-spec b47ff6ec).
    PairingRequestExpired,
    ProofInvalid,
    VerificationMethodPrincipalMismatch,
    AgentPaused,
    AgentDeactivated,
    ApprovalAlreadyConsumed,
    SidecarCreateDenied,
    ActorKindReducerManaged,
    FocusMismatch,
    UnknownFocusType,
    TokenIssuerUnauthorised,
    ParticipantBindingInvalid,
    ParticipantIdentityUnrecognised,
    SessionFocusAlreadyCommitted,
    E2eeKeySourceUnauthorised,
    RecordingArtifactPipelineBypassed,
    FocusUnavailableForClient,
    RecoveryWitnessRevokeLagging,
    HandleHomographForbidden,
    // ── Registry backfill (2026-06-08).
    PolicyDenied,
    CursorUnrecognized,
    ActorSeqInvalid,
    StaleSealRef,
    SealRefUnknown,
    AudienceUnknown,
    BlobDigestMismatch,
    BlobExpired,
    BlobPresignInvalid,
    BlobQuotaExceeded,
    CursorInvalid,
    DeviceUnknown,
    DidAlreadyExists,
    DidNotFound,
    DidRevoked,
    FrontierUnavailable,
    HandleUnverified,
    KeyReplay,
    KeypackageAlreadyConsumed,
    KeypackageUnknown,
    OneTimeKeysExhausted,
    PolicyStale,
    PolicyUnavailable,
    PrincipalUnknown,
    PushGatewayUnreachable,
    PushPayloadTooLarge,
    PushTargetUnknown,
    PushTokenInvalid,
    PushTokenUnknown,
    Quarantine,
    SnapshotAuthorityUnverified,
    ReducerProfileMismatch,
    SnapshotUnavailable,
    StreamDropped,
    StreamResyncRequired,
    TooLarge,
    UnsupportedDidMethod,
    UnsupportedMediaPolicy,
    NotImplemented,
    ServiceUnavailable,
    UnsupportedJoinRule,
    ContactNotAccepted,
    ContactConsentMissing,
    ContactRequestNotPending,
    ContactRequestExpired,
    DeliveryBindingUnresolvable,
    AppletRegistrationUnauthorized,
    AppletInstallPlanMismatch,
    AppletE2eeJoinUnauthorized,
    AppletRevoked,
    InvalidAvatarBlobRef,
    UnsupportedProfilePatchPath,
    SessionGrantNotFound,
    SessionRevokeSelectorConflict,
    ReviewerCapabilityRevoked,
    NotMember,
    CallNotFound,
    CallExpired,
    CallAlreadyAnswered,
    MediaPermissionDenied,
    IceConfigDenied,
    SfuNotAllowed,
    E2eeRequired,
    RecordingDenied,
    MorphProfileWidensSchemaRef,
    MorphTypeImmutable,
    TranscriptionDenied,
    TranscriptionArtifactPipelineBypassed,
    RecordingConsentRequired,
    CallModerationUnauthorised,
    CallParticipantRemoved,
    CallSummaryInvalid,
}

impl ErrorCode {
    /// All variants in registry order.
    pub const ALL: &'static [Self] = &[
        Self::BadJson,
        Self::BadQuery,
        Self::SchemaViolation,
        Self::MissingParam,
        Self::InvalidParam,
        Self::InvalidResponse,
        Self::Unauthenticated,
        Self::AuthExpired,
        Self::SoftLoggedOut,
        Self::InvalidSignature,
        Self::CapabilityDenied,
        Self::RealmFrozen,
        Self::ClaimRequired,
        Self::NotFound,
        Self::UnrecognizedEndpoint,
        Self::MethodNotAllowed,
        Self::Conflict,
        Self::CasConflict,
        Self::CausalConflict,
        Self::DependencyMissing,
        Self::DiscussionTrackDisabled,
        Self::PolicyViolation,
        Self::EpochMismatch,
        Self::DuplicateConflict,
        Self::RankExhausted,
        Self::HlcLogicalOverflow,
        Self::PayloadTooLarge,
        Self::DigestMismatch,
        Self::AadDigestMismatch,
        Self::PayloadDigestMismatch,
        Self::KeyUnavailable,
        Self::StateMismatch,
        Self::AuditReceiptInvalidated,
        Self::UnknownDid,
        Self::QuotaExceeded,
        Self::LimitExceeded,
        Self::RateLimited,
        Self::Timeout,
        Self::StaleFrontier,
        Self::CursorExpired,
        Self::UnsupportedFeature,
        Self::UnsupportedEventKind,
        Self::ProjectionIncomplete,
        Self::InternalError,
        Self::TemporarilyUnavailable,
        Self::PolicyCombinationInvalid,
        Self::HistorySharingPolicyMissing,
        Self::HistoryNotVisible,
        Self::PreviewPolicyDenied,
        Self::NotaryRecoveryMissing,
        Self::UnsupportedLatticeType,
        Self::ProfileUnsupported,
        Self::CursorIntegrityInvalid,
        Self::FailedPrecondition,
        Self::UnsupportedHash,
        Self::SealIncomplete,
        Self::FrankingProofUnavailable,
        Self::TurnCredentialExpired,
        Self::StalePeer,
        Self::RelaxedWindowExceedsCeiling,
        Self::E2eeRelaxedDisallowedInComplianceProfile,
        Self::CrossDomainReplayRejected,
        Self::ResetEventIdMismatch,
        Self::AppealOverturnMissingLift,
        Self::AppealSelfReviewForbidden,
        Self::RealmTerminalState,
        Self::AuditPurposeMismatch,
        Self::LegalHoldActive,
        Self::BlobRedacted,
        Self::MediaPlaintextServiceNotAuthorised,
        Self::MlsGovernanceBindingStale,
        Self::ExpiredInviteToken,
        Self::LateRecoveryRejectedMembership,
        Self::DeliveryBindingStale,
        Self::DeliveryBindingHandedOver,
        Self::HistoricalOnly,
        Self::DirectoryNotAuthorized,
        Self::AcceptPolicyDenied,
        Self::SignatureInvalid,
        Self::SignatureStale,
        Self::SourceRefsUnverifiable,
        Self::GovernanceKeyInvalid,
        Self::TtlOutOfRange,
        Self::TakedownInForce,
        Self::PolicyRevisionRollback,
        Self::DidProofRequired,
        Self::ReadReceiptComplianceFloorViolated,
        Self::EphemeralKindNotPermitted,
        Self::EphemeralTtlOutOfRange,
        Self::EphemeralChannelUnavailable,
        Self::AuthorizedGrantRevoked,
        Self::DeviceRecoverySskGenerationMismatch,
        Self::CursorRevoked,
        Self::SeriesChainBroken,
        Self::SeriesSeqNotMonotonic,
        Self::SeriesPredecessorNotFound,
        Self::RecoveryPolicyMismatch,
        Self::ShareCommitmentMismatch,
        Self::BackupFrontierStale,
        Self::BackupPostResetStale,
        Self::RecoveryEvidenceUnbound,
        Self::UnsupportedAeadProfile,
        Self::AttestationMissing,
        // ── R3 spec-sync (2026-05-27).
        Self::PairingRequestExpired,
        Self::ProofInvalid,
        Self::VerificationMethodPrincipalMismatch,
        Self::AgentPaused,
        Self::AgentDeactivated,
        Self::ApprovalAlreadyConsumed,
        Self::SidecarCreateDenied,
        Self::ActorKindReducerManaged,
        Self::FocusMismatch,
        Self::UnknownFocusType,
        Self::TokenIssuerUnauthorised,
        Self::ParticipantBindingInvalid,
        Self::ParticipantIdentityUnrecognised,
        Self::SessionFocusAlreadyCommitted,
        Self::E2eeKeySourceUnauthorised,
        Self::RecordingArtifactPipelineBypassed,
        Self::FocusUnavailableForClient,
        Self::RecoveryWitnessRevokeLagging,
        Self::HandleHomographForbidden,
        // ── Registry backfill (2026-06-08).
        Self::PolicyDenied,
        Self::CursorUnrecognized,
        Self::ActorSeqInvalid,
        Self::StaleSealRef,
        Self::SealRefUnknown,
        Self::AudienceUnknown,
        Self::BlobDigestMismatch,
        Self::BlobExpired,
        Self::BlobPresignInvalid,
        Self::BlobQuotaExceeded,
        Self::CursorInvalid,
        Self::DeviceUnknown,
        Self::DidAlreadyExists,
        Self::DidNotFound,
        Self::DidRevoked,
        Self::FrontierUnavailable,
        Self::HandleUnverified,
        Self::KeyReplay,
        Self::KeypackageAlreadyConsumed,
        Self::KeypackageUnknown,
        Self::OneTimeKeysExhausted,
        Self::PolicyStale,
        Self::PolicyUnavailable,
        Self::PrincipalUnknown,
        Self::PushGatewayUnreachable,
        Self::PushPayloadTooLarge,
        Self::PushTargetUnknown,
        Self::PushTokenInvalid,
        Self::PushTokenUnknown,
        Self::Quarantine,
        Self::SnapshotAuthorityUnverified,
        Self::ReducerProfileMismatch,
        Self::SnapshotUnavailable,
        Self::StreamDropped,
        Self::StreamResyncRequired,
        Self::TooLarge,
        Self::UnsupportedDidMethod,
        Self::UnsupportedMediaPolicy,
        Self::NotImplemented,
        Self::ServiceUnavailable,
        Self::UnsupportedJoinRule,
        Self::ContactNotAccepted,
        Self::ContactConsentMissing,
        Self::ContactRequestNotPending,
        Self::ContactRequestExpired,
        Self::DeliveryBindingUnresolvable,
        Self::AppletRegistrationUnauthorized,
        Self::AppletInstallPlanMismatch,
        Self::AppletE2eeJoinUnauthorized,
        Self::AppletRevoked,
        Self::InvalidAvatarBlobRef,
        Self::UnsupportedProfilePatchPath,
        Self::SessionGrantNotFound,
        Self::SessionRevokeSelectorConflict,
        Self::ReviewerCapabilityRevoked,
        Self::NotMember,
        Self::CallNotFound,
        Self::CallExpired,
        Self::CallAlreadyAnswered,
        Self::MediaPermissionDenied,
        Self::IceConfigDenied,
        Self::SfuNotAllowed,
        Self::E2eeRequired,
        Self::RecordingDenied,
        Self::MorphProfileWidensSchemaRef,
        Self::MorphTypeImmutable,
        Self::TranscriptionDenied,
        Self::TranscriptionArtifactPipelineBypassed,
        Self::RecordingConsentRequired,
        Self::CallModerationUnauthorised,
        Self::CallParticipantRemoved,
        Self::CallSummaryInvalid,
    ];

    /// Canonical wire-form code (snake_case string).
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BadJson => ERROR_CODE_BAD_JSON,
            Self::BadQuery => ERROR_CODE_BAD_QUERY,
            Self::SchemaViolation => ERROR_CODE_SCHEMA_VIOLATION,
            Self::MissingParam => ERROR_CODE_MISSING_PARAM,
            Self::InvalidParam => ERROR_CODE_INVALID_PARAM,
            Self::InvalidResponse => ERROR_CODE_INVALID_RESPONSE,
            Self::Unauthenticated => ERROR_CODE_UNAUTHENTICATED,
            Self::AuthExpired => ERROR_CODE_AUTH_EXPIRED,
            Self::SoftLoggedOut => ERROR_CODE_SOFT_LOGGED_OUT,
            Self::InvalidSignature => ERROR_CODE_INVALID_SIGNATURE,
            Self::CapabilityDenied => ERROR_CODE_CAPABILITY_DENIED,
            Self::RealmFrozen => ERROR_CODE_REALM_FROZEN,
            Self::ClaimRequired => ERROR_CODE_CLAIM_REQUIRED,
            Self::NotFound => ERROR_CODE_NOT_FOUND,
            Self::UnrecognizedEndpoint => ERROR_CODE_UNRECOGNIZED_ENDPOINT,
            Self::MethodNotAllowed => ERROR_CODE_METHOD_NOT_ALLOWED,
            Self::Conflict => ERROR_CODE_CONFLICT,
            Self::CasConflict => ERROR_CODE_CAS_CONFLICT,
            Self::CausalConflict => ERROR_CODE_CAUSAL_CONFLICT,
            Self::DependencyMissing => ERROR_CODE_DEPENDENCY_MISSING,
            Self::DiscussionTrackDisabled => ERROR_CODE_DISCUSSION_TRACK_DISABLED,
            Self::PolicyViolation => ERROR_CODE_POLICY_VIOLATION,
            Self::EpochMismatch => ERROR_CODE_EPOCH_MISMATCH,
            Self::DuplicateConflict => ERROR_CODE_DUPLICATE_CONFLICT,
            Self::RankExhausted => ERROR_CODE_RANK_EXHAUSTED,
            Self::HlcLogicalOverflow => ERROR_CODE_HLC_LOGICAL_OVERFLOW,
            Self::PayloadTooLarge => ERROR_CODE_PAYLOAD_TOO_LARGE,
            Self::DigestMismatch => ERROR_CODE_DIGEST_MISMATCH,
            Self::AadDigestMismatch => ERROR_CODE_AAD_DIGEST_MISMATCH,
            Self::PayloadDigestMismatch => ERROR_CODE_PAYLOAD_DIGEST_MISMATCH,
            Self::KeyUnavailable => ERROR_CODE_KEY_UNAVAILABLE,
            Self::StateMismatch => ERROR_CODE_STATE_MISMATCH,
            Self::AuditReceiptInvalidated => ERROR_CODE_AUDIT_RECEIPT_INVALIDATED,
            Self::UnknownDid => ERROR_CODE_UNKNOWN_DID,
            Self::QuotaExceeded => ERROR_CODE_QUOTA_EXCEEDED,
            Self::LimitExceeded => ERROR_CODE_LIMIT_EXCEEDED,
            Self::RateLimited => ERROR_CODE_RATE_LIMITED,
            Self::Timeout => ERROR_CODE_TIMEOUT,
            Self::StaleFrontier => ERROR_CODE_STALE_FRONTIER,
            Self::CursorExpired => ERROR_CODE_CURSOR_EXPIRED,
            Self::UnsupportedFeature => ERROR_CODE_UNSUPPORTED_FEATURE,
            Self::UnsupportedEventKind => ERROR_CODE_UNSUPPORTED_EVENT_KIND,
            Self::ProjectionIncomplete => ERROR_CODE_PROJECTION_INCOMPLETE,
            Self::InternalError => ERROR_CODE_INTERNAL_ERROR,
            Self::TemporarilyUnavailable => ERROR_CODE_TEMPORARILY_UNAVAILABLE,
            Self::PolicyCombinationInvalid => ERROR_CODE_POLICY_COMBINATION_INVALID,
            Self::HistorySharingPolicyMissing => ERROR_CODE_HISTORY_SHARING_POLICY_MISSING,
            Self::HistoryNotVisible => ERROR_CODE_HISTORY_NOT_VISIBLE,
            Self::PreviewPolicyDenied => ERROR_CODE_PREVIEW_POLICY_DENIED,
            Self::NotaryRecoveryMissing => ERROR_CODE_NOTARY_RECOVERY_MISSING,
            Self::UnsupportedLatticeType => ERROR_CODE_UNSUPPORTED_LATTICE_TYPE,
            Self::ProfileUnsupported => ERROR_CODE_PROFILE_UNSUPPORTED,
            Self::CursorIntegrityInvalid => ERROR_CODE_CURSOR_INTEGRITY_INVALID,
            Self::FailedPrecondition => ERROR_CODE_FAILED_PRECONDITION,
            Self::UnsupportedHash => ERROR_CODE_UNSUPPORTED_HASH,
            Self::SealIncomplete => ERROR_CODE_SEAL_INCOMPLETE,
            Self::FrankingProofUnavailable => ERROR_CODE_FRANKING_PROOF_UNAVAILABLE,
            Self::TurnCredentialExpired => ERROR_CODE_TURN_CREDENTIAL_EXPIRED,
            Self::StalePeer => ERROR_CODE_STALE_PEER,
            Self::RelaxedWindowExceedsCeiling => ERROR_CODE_RELAXED_WINDOW_EXCEEDS_CEILING,
            Self::E2eeRelaxedDisallowedInComplianceProfile => {
                ERROR_CODE_E2EE_RELAXED_DISALLOWED_IN_COMPLIANCE_PROFILE
            }
            Self::CrossDomainReplayRejected => ERROR_CODE_CROSS_DOMAIN_REPLAY_REJECTED,
            Self::ResetEventIdMismatch => ERROR_CODE_RESET_EVENT_ID_MISMATCH,
            Self::AppealOverturnMissingLift => ERROR_CODE_APPEAL_OVERTURN_MISSING_LIFT,
            Self::AppealSelfReviewForbidden => ERROR_CODE_APPEAL_SELF_REVIEW_FORBIDDEN,
            Self::RealmTerminalState => ERROR_CODE_REALM_TERMINAL_STATE,
            Self::AuditPurposeMismatch => ERROR_CODE_AUDIT_PURPOSE_MISMATCH,
            Self::LegalHoldActive => ERROR_CODE_LEGAL_HOLD_ACTIVE,
            Self::BlobRedacted => ERROR_CODE_BLOB_REDACTED,
            Self::MediaPlaintextServiceNotAuthorised => {
                ERROR_CODE_MEDIA_PLAINTEXT_SERVICE_NOT_AUTHORISED
            }
            Self::MlsGovernanceBindingStale => ERROR_CODE_MLS_GOVERNANCE_BINDING_STALE,
            Self::ExpiredInviteToken => ERROR_CODE_EXPIRED_INVITE_TOKEN,
            Self::LateRecoveryRejectedMembership => ERROR_CODE_LATE_RECOVERY_REJECTED_MEMBERSHIP,
            Self::DeliveryBindingStale => ERROR_CODE_DELIVERY_BINDING_STALE,
            Self::DeliveryBindingHandedOver => ERROR_CODE_DELIVERY_BINDING_HANDED_OVER,
            Self::HistoricalOnly => ERROR_CODE_HISTORICAL_ONLY,
            Self::DirectoryNotAuthorized => ERROR_CODE_DIRECTORY_NOT_AUTHORIZED,
            Self::AcceptPolicyDenied => ERROR_CODE_ACCEPT_POLICY_DENIED,
            Self::SignatureInvalid => ERROR_CODE_SIGNATURE_INVALID,
            Self::SignatureStale => ERROR_CODE_SIGNATURE_STALE,
            Self::SourceRefsUnverifiable => ERROR_CODE_SOURCE_REFS_UNVERIFIABLE,
            Self::GovernanceKeyInvalid => ERROR_CODE_GOVERNANCE_KEY_INVALID,
            Self::TtlOutOfRange => ERROR_CODE_TTL_OUT_OF_RANGE,
            Self::TakedownInForce => ERROR_CODE_TAKEDOWN_IN_FORCE,
            Self::PolicyRevisionRollback => ERROR_CODE_POLICY_REVISION_ROLLBACK,
            Self::DidProofRequired => ERROR_CODE_DID_PROOF_REQUIRED,
            Self::ReadReceiptComplianceFloorViolated => {
                ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED
            }
            Self::EphemeralKindNotPermitted => ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED,
            Self::EphemeralTtlOutOfRange => ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE,
            Self::EphemeralChannelUnavailable => ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE,
            Self::AuthorizedGrantRevoked => ERROR_CODE_AUTHORIZED_GRANT_REVOKED,
            Self::DeviceRecoverySskGenerationMismatch => {
                ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH
            }
            Self::CursorRevoked => ERROR_CODE_CURSOR_REVOKED,
            Self::SeriesChainBroken => ERROR_CODE_SERIES_CHAIN_BROKEN,
            Self::SeriesSeqNotMonotonic => ERROR_CODE_SERIES_SEQ_NOT_MONOTONIC,
            Self::SeriesPredecessorNotFound => ERROR_CODE_SERIES_PREDECESSOR_NOT_FOUND,
            Self::RecoveryPolicyMismatch => ERROR_CODE_RECOVERY_POLICY_MISMATCH,
            Self::ShareCommitmentMismatch => ERROR_CODE_SHARE_COMMITMENT_MISMATCH,
            Self::BackupFrontierStale => ERROR_CODE_BACKUP_FRONTIER_STALE,
            Self::BackupPostResetStale => ERROR_CODE_BACKUP_POST_RESET_STALE,
            Self::RecoveryEvidenceUnbound => ERROR_CODE_RECOVERY_EVIDENCE_UNBOUND,
            Self::UnsupportedAeadProfile => ERROR_CODE_UNSUPPORTED_AEAD_PROFILE,
            Self::AttestationMissing => ERROR_CODE_ATTESTATION_MISSING,
            // ── R3 spec-sync (2026-05-27).
            Self::PairingRequestExpired => ERROR_CODE_PAIRING_REQUEST_EXPIRED,
            Self::ProofInvalid => ERROR_CODE_PROOF_INVALID,
            Self::VerificationMethodPrincipalMismatch => {
                ERROR_CODE_VERIFICATION_METHOD_PRINCIPAL_MISMATCH
            }
            Self::AgentPaused => ERROR_CODE_AGENT_PAUSED,
            Self::AgentDeactivated => ERROR_CODE_AGENT_DEACTIVATED,
            Self::ApprovalAlreadyConsumed => ERROR_CODE_APPROVAL_ALREADY_CONSUMED,
            Self::SidecarCreateDenied => ERROR_CODE_SIDECAR_CREATE_DENIED,
            Self::ActorKindReducerManaged => ERROR_CODE_ACTOR_KIND_REDUCER_MANAGED,
            Self::FocusMismatch => ERROR_CODE_FOCUS_MISMATCH,
            Self::UnknownFocusType => ERROR_CODE_UNKNOWN_FOCUS_TYPE,
            Self::TokenIssuerUnauthorised => ERROR_CODE_TOKEN_ISSUER_UNAUTHORISED,
            Self::ParticipantBindingInvalid => ERROR_CODE_PARTICIPANT_BINDING_INVALID,
            Self::ParticipantIdentityUnrecognised => ERROR_CODE_PARTICIPANT_IDENTITY_UNRECOGNISED,
            Self::SessionFocusAlreadyCommitted => ERROR_CODE_SESSION_FOCUS_ALREADY_COMMITTED,
            Self::E2eeKeySourceUnauthorised => ERROR_CODE_E2EE_KEY_SOURCE_UNAUTHORISED,
            Self::RecordingArtifactPipelineBypassed => {
                ERROR_CODE_RECORDING_ARTIFACT_PIPELINE_BYPASSED
            }
            Self::FocusUnavailableForClient => ERROR_CODE_FOCUS_UNAVAILABLE_FOR_CLIENT,
            Self::RecoveryWitnessRevokeLagging => ERROR_CODE_RECOVERY_WITNESS_REVOKE_LAGGING,
            Self::HandleHomographForbidden => ERROR_CODE_HANDLE_HOMOGRAPH_FORBIDDEN,
            // ── Registry backfill (2026-06-08).
            Self::PolicyDenied => ERROR_CODE_POLICY_DENIED,
            Self::CursorUnrecognized => ERROR_CODE_CURSOR_UNRECOGNIZED,
            Self::ActorSeqInvalid => ERROR_CODE_ACTOR_SEQ_INVALID,
            Self::StaleSealRef => ERROR_CODE_STALE_SEAL_REF,
            Self::SealRefUnknown => ERROR_CODE_SEAL_REF_UNKNOWN,
            Self::AudienceUnknown => ERROR_CODE_AUDIENCE_UNKNOWN,
            Self::BlobDigestMismatch => ERROR_CODE_BLOB_DIGEST_MISMATCH,
            Self::BlobExpired => ERROR_CODE_BLOB_EXPIRED,
            Self::BlobPresignInvalid => ERROR_CODE_BLOB_PRESIGN_INVALID,
            Self::BlobQuotaExceeded => ERROR_CODE_BLOB_QUOTA_EXCEEDED,
            Self::CursorInvalid => ERROR_CODE_CURSOR_INVALID,
            Self::DeviceUnknown => ERROR_CODE_DEVICE_UNKNOWN,
            Self::DidAlreadyExists => ERROR_CODE_DID_ALREADY_EXISTS,
            Self::DidNotFound => ERROR_CODE_DID_NOT_FOUND,
            Self::DidRevoked => ERROR_CODE_DID_REVOKED,
            Self::FrontierUnavailable => ERROR_CODE_FRONTIER_UNAVAILABLE,
            Self::HandleUnverified => ERROR_CODE_HANDLE_UNVERIFIED,
            Self::KeyReplay => ERROR_CODE_KEY_REPLAY,
            Self::KeypackageAlreadyConsumed => ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED,
            Self::KeypackageUnknown => ERROR_CODE_KEYPACKAGE_UNKNOWN,
            Self::OneTimeKeysExhausted => ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED,
            Self::PolicyStale => ERROR_CODE_POLICY_STALE,
            Self::PolicyUnavailable => ERROR_CODE_POLICY_UNAVAILABLE,
            Self::PrincipalUnknown => ERROR_CODE_PRINCIPAL_UNKNOWN,
            Self::PushGatewayUnreachable => ERROR_CODE_PUSH_GATEWAY_UNREACHABLE,
            Self::PushPayloadTooLarge => ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE,
            Self::PushTargetUnknown => ERROR_CODE_PUSH_TARGET_UNKNOWN,
            Self::PushTokenInvalid => ERROR_CODE_PUSH_TOKEN_INVALID,
            Self::PushTokenUnknown => ERROR_CODE_PUSH_TOKEN_UNKNOWN,
            Self::Quarantine => ERROR_CODE_QUARANTINE,
            Self::SnapshotAuthorityUnverified => ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED,
            Self::ReducerProfileMismatch => ERROR_CODE_REDUCER_PROFILE_MISMATCH,
            Self::SnapshotUnavailable => ERROR_CODE_SNAPSHOT_UNAVAILABLE,
            Self::StreamDropped => ERROR_CODE_STREAM_DROPPED,
            Self::StreamResyncRequired => ERROR_CODE_STREAM_RESYNC_REQUIRED,
            Self::TooLarge => ERROR_CODE_TOO_LARGE,
            Self::UnsupportedDidMethod => ERROR_CODE_UNSUPPORTED_DID_METHOD,
            Self::UnsupportedMediaPolicy => ERROR_CODE_UNSUPPORTED_MEDIA_POLICY,
            Self::NotImplemented => ERROR_CODE_NOT_IMPLEMENTED,
            Self::ServiceUnavailable => ERROR_CODE_SERVICE_UNAVAILABLE,
            Self::UnsupportedJoinRule => ERROR_CODE_UNSUPPORTED_JOIN_RULE,
            Self::ContactNotAccepted => ERROR_CODE_CONTACT_NOT_ACCEPTED,
            Self::ContactConsentMissing => ERROR_CODE_CONTACT_CONSENT_MISSING,
            Self::ContactRequestNotPending => ERROR_CODE_CONTACT_REQUEST_NOT_PENDING,
            Self::ContactRequestExpired => ERROR_CODE_CONTACT_REQUEST_EXPIRED,
            Self::DeliveryBindingUnresolvable => ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE,
            Self::AppletRegistrationUnauthorized => ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED,
            Self::AppletInstallPlanMismatch => ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH,
            Self::AppletE2eeJoinUnauthorized => ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED,
            Self::AppletRevoked => ERROR_CODE_APPLET_REVOKED,
            Self::InvalidAvatarBlobRef => ERROR_CODE_INVALID_AVATAR_BLOB_REF,
            Self::UnsupportedProfilePatchPath => ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH,
            Self::SessionGrantNotFound => ERROR_CODE_SESSION_GRANT_NOT_FOUND,
            Self::SessionRevokeSelectorConflict => ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT,
            Self::ReviewerCapabilityRevoked => ERROR_CODE_REVIEWER_CAPABILITY_REVOKED,
            Self::NotMember => ERROR_CODE_NOT_MEMBER,
            Self::CallNotFound => ERROR_CODE_CALL_NOT_FOUND,
            Self::CallExpired => ERROR_CODE_CALL_EXPIRED,
            Self::CallAlreadyAnswered => ERROR_CODE_CALL_ALREADY_ANSWERED,
            Self::MediaPermissionDenied => ERROR_CODE_MEDIA_PERMISSION_DENIED,
            Self::IceConfigDenied => ERROR_CODE_ICE_CONFIG_DENIED,
            Self::SfuNotAllowed => ERROR_CODE_SFU_NOT_ALLOWED,
            Self::E2eeRequired => ERROR_CODE_E2EE_REQUIRED,
            Self::RecordingDenied => ERROR_CODE_RECORDING_DENIED,
            Self::MorphProfileWidensSchemaRef => ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF,
            Self::MorphTypeImmutable => ERROR_CODE_MORPH_TYPE_IMMUTABLE,
            Self::TranscriptionDenied => ERROR_CODE_TRANSCRIPTION_DENIED,
            Self::TranscriptionArtifactPipelineBypassed => {
                ERROR_CODE_TRANSCRIPTION_ARTIFACT_PIPELINE_BYPASSED
            }
            Self::RecordingConsentRequired => ERROR_CODE_RECORDING_CONSENT_REQUIRED,
            Self::CallModerationUnauthorised => ERROR_CODE_CALL_MODERATION_UNAUTHORISED,
            Self::CallParticipantRemoved => ERROR_CODE_CALL_PARTICIPANT_REMOVED,
            Self::CallSummaryInvalid => ERROR_CODE_CALL_SUMMARY_INVALID,
        }
    }

    /// Registered HTTP status, identical to what
    /// [`error_code_http_status`] returns for the same wire string.
    /// Panics only if the constant table and the HTTP-status mapping
    /// drift; the `every_variant_has_http_status` test catches this.
    pub fn http_status(self) -> u16 {
        error_code_http_status(self.as_str())
            .expect("every ErrorCode variant has a registered HTTP status")
    }

    /// Parse a wire-form code back into its typed variant.
    pub fn from_wire(code: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|c| c.as_str() == code)
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
