use super::codes::*;

/// Return `true` when `code` is a registered canonical error code.
pub fn is_known_error_code(code: &str) -> bool {
    KNOWN_ERROR_CODES.contains(&code)
}

/// Return the HTTP status binding for `code` per `error-code-registry.json`.
/// `None` when `code` is not registered (callers SHOULD reject the response).
pub fn error_code_http_status(code: &str) -> Option<u16> {
    Some(match code {
        ERROR_CODE_BAD_JSON
        | ERROR_CODE_BAD_QUERY
        | ERROR_CODE_MISSING_PARAM
        | ERROR_CODE_INVALID_PARAM
        | ERROR_CODE_INVALID_RESPONSE
        | ERROR_CODE_CURSOR_INTEGRITY_INVALID
        | ERROR_CODE_RELAXED_WINDOW_EXCEEDS_CEILING
        | ERROR_CODE_RESET_EVENT_ID_MISMATCH
        | ERROR_CODE_EXPIRED_INVITE_TOKEN
        | ERROR_CODE_SIGNATURE_INVALID
        | ERROR_CODE_SIGNATURE_STALE
        | ERROR_CODE_SOURCE_REFS_UNVERIFIABLE
        | ERROR_CODE_GOVERNANCE_KEY_INVALID
        | ERROR_CODE_TTL_OUT_OF_RANGE
        | ERROR_CODE_EPHEMERAL_TTL_OUT_OF_RANGE
        | ERROR_CODE_CURSOR_UNRECOGNIZED
        | ERROR_CODE_BLOB_PRESIGN_INVALID
        | ERROR_CODE_CURSOR_INVALID
        | ERROR_CODE_PUSH_TOKEN_INVALID => 400,
        ERROR_CODE_UNAUTHENTICATED
        | ERROR_CODE_AUTH_EXPIRED
        | ERROR_CODE_SOFT_LOGGED_OUT
        | ERROR_CODE_INVALID_SIGNATURE
        | ERROR_CODE_TURN_CREDENTIAL_EXPIRED
        | ERROR_CODE_ATTESTATION_MISSING
        | ERROR_CODE_DID_PROOF_REQUIRED
        | ERROR_CODE_PROOF_INVALID
        | ERROR_CODE_VERIFICATION_METHOD_PRINCIPAL_MISMATCH
        | ERROR_CODE_TOKEN_ISSUER_UNAUTHORISED => 401,
        ERROR_CODE_CAPABILITY_DENIED
        | ERROR_CODE_DIRECTORY_NOT_AUTHORIZED
        | ERROR_CODE_ACCEPT_POLICY_DENIED
        | ERROR_CODE_REALM_FROZEN
        | ERROR_CODE_CLAIM_REQUIRED
        | ERROR_CODE_POLICY_VIOLATION
        | ERROR_CODE_QUOTA_EXCEEDED
        | ERROR_CODE_E2EE_RELAXED_DISALLOWED_IN_COMPLIANCE_PROFILE
        | ERROR_CODE_APPEAL_SELF_REVIEW_FORBIDDEN
        | ERROR_CODE_LEGAL_HOLD_ACTIVE
        | ERROR_CODE_BLOB_REDACTED
        | ERROR_CODE_MEDIA_PLAINTEXT_SERVICE_NOT_AUTHORISED
        | ERROR_CODE_LATE_RECOVERY_REJECTED_MEMBERSHIP
        | ERROR_CODE_EPHEMERAL_KIND_NOT_PERMITTED
        | ERROR_CODE_AGENT_PAUSED
        | ERROR_CODE_AGENT_DEACTIVATED
        | ERROR_CODE_SIDECAR_CREATE_DENIED
        | ERROR_CODE_E2EE_KEY_SOURCE_UNAUTHORISED
        | ERROR_CODE_RECORDING_ARTIFACT_PIPELINE_BYPASSED
        | ERROR_CODE_HISTORY_NOT_VISIBLE
        | ERROR_CODE_PREVIEW_POLICY_DENIED
        | ERROR_CODE_HANDLE_HOMOGRAPH_FORBIDDEN
        | ERROR_CODE_POLICY_DENIED
        | ERROR_CODE_BLOB_QUOTA_EXCEEDED
        | ERROR_CODE_HANDLE_UNVERIFIED
        | ERROR_CODE_SNAPSHOT_AUTHORITY_UNVERIFIED
        | ERROR_CODE_APPLET_REGISTRATION_UNAUTHORIZED
        | ERROR_CODE_APPLET_E2EE_JOIN_UNAUTHORIZED
        | ERROR_CODE_APPLET_REVOKED
        | ERROR_CODE_REVIEWER_CAPABILITY_REVOKED
        | ERROR_CODE_NOT_MEMBER
        | ERROR_CODE_MEDIA_PERMISSION_DENIED
        | ERROR_CODE_ICE_CONFIG_DENIED
        | ERROR_CODE_SFU_NOT_ALLOWED
        | ERROR_CODE_E2EE_REQUIRED
        | ERROR_CODE_RECORDING_DENIED
        | ERROR_CODE_TRANSCRIPTION_DENIED
        | ERROR_CODE_TRANSCRIPTION_ARTIFACT_PIPELINE_BYPASSED
        | ERROR_CODE_CALL_MODERATION_UNAUTHORISED
        | ERROR_CODE_CALL_PARTICIPANT_REMOVED => 403,
        ERROR_CODE_NOT_FOUND
        | ERROR_CODE_UNRECOGNIZED_ENDPOINT
        | ERROR_CODE_SEAL_REF_UNKNOWN
        | ERROR_CODE_AUDIENCE_UNKNOWN
        | ERROR_CODE_DEVICE_UNKNOWN
        | ERROR_CODE_DID_NOT_FOUND
        | ERROR_CODE_KEYPACKAGE_UNKNOWN
        | ERROR_CODE_PRINCIPAL_UNKNOWN
        | ERROR_CODE_PUSH_TARGET_UNKNOWN
        | ERROR_CODE_PUSH_TOKEN_UNKNOWN
        | ERROR_CODE_SESSION_GRANT_NOT_FOUND
        | ERROR_CODE_CALL_NOT_FOUND => 404,
        ERROR_CODE_METHOD_NOT_ALLOWED => 405,
        ERROR_CODE_CONFLICT
        | ERROR_CODE_CAS_CONFLICT
        | ERROR_CODE_CAUSAL_CONFLICT
        | ERROR_CODE_DEPENDENCY_MISSING
        | ERROR_CODE_DISCUSSION_TRACK_DISABLED
        | ERROR_CODE_EPOCH_MISMATCH
        | ERROR_CODE_DUPLICATE_CONFLICT
        | ERROR_CODE_RANK_EXHAUSTED
        | ERROR_CODE_KEY_UNAVAILABLE
        | ERROR_CODE_STATE_MISMATCH
        | ERROR_CODE_AUDIT_RECEIPT_INVALIDATED
        | ERROR_CODE_STALE_FRONTIER
        | ERROR_CODE_PROJECTION_INCOMPLETE
        | ERROR_CODE_FAILED_PRECONDITION
        | ERROR_CODE_SEAL_INCOMPLETE
        | ERROR_CODE_STALE_PEER
        | ERROR_CODE_CROSS_DOMAIN_REPLAY_REJECTED
        | ERROR_CODE_APPEAL_OVERTURN_MISSING_LIFT
        | ERROR_CODE_REALM_TERMINAL_STATE
        | ERROR_CODE_AUDIT_PURPOSE_MISMATCH
        | ERROR_CODE_MLS_GOVERNANCE_BINDING_STALE
        | ERROR_CODE_DELIVERY_BINDING_STALE
        | ERROR_CODE_DELIVERY_BINDING_HANDED_OVER
        | ERROR_CODE_TAKEDOWN_IN_FORCE
        | ERROR_CODE_POLICY_REVISION_ROLLBACK
        | ERROR_CODE_AUTHORIZED_GRANT_REVOKED
        | ERROR_CODE_DEVICE_RECOVERY_SSK_GENERATION_MISMATCH
        | ERROR_CODE_SERIES_CHAIN_BROKEN
        | ERROR_CODE_SERIES_SEQ_NOT_MONOTONIC
        | ERROR_CODE_SERIES_PREDECESSOR_NOT_FOUND
        | ERROR_CODE_RECOVERY_POLICY_MISMATCH
        | ERROR_CODE_BACKUP_FRONTIER_STALE
        | ERROR_CODE_BACKUP_POST_RESET_STALE
        | ERROR_CODE_APPROVAL_ALREADY_CONSUMED
        | ERROR_CODE_ACTOR_KIND_REDUCER_MANAGED
        | ERROR_CODE_FOCUS_MISMATCH
        | ERROR_CODE_SESSION_FOCUS_ALREADY_COMMITTED
        | ERROR_CODE_FOCUS_UNAVAILABLE_FOR_CLIENT
        | ERROR_CODE_RECOVERY_WITNESS_REVOKE_LAGGING
        | ERROR_CODE_ACTOR_SEQ_INVALID
        | ERROR_CODE_STALE_SEAL_REF
        | ERROR_CODE_DID_ALREADY_EXISTS
        | ERROR_CODE_KEY_REPLAY
        | ERROR_CODE_KEYPACKAGE_ALREADY_CONSUMED
        | ERROR_CODE_ONE_TIME_KEYS_EXHAUSTED
        | ERROR_CODE_POLICY_STALE
        | ERROR_CODE_QUARANTINE
        | ERROR_CODE_REDUCER_PROFILE_MISMATCH
        | ERROR_CODE_STREAM_DROPPED
        | ERROR_CODE_STREAM_RESYNC_REQUIRED
        | ERROR_CODE_CONTACT_NOT_ACCEPTED
        | ERROR_CODE_CONTACT_CONSENT_MISSING
        | ERROR_CODE_CONTACT_REQUEST_NOT_PENDING
        | ERROR_CODE_CONTACT_REQUEST_EXPIRED
        | ERROR_CODE_DELIVERY_BINDING_UNRESOLVABLE
        | ERROR_CODE_APPLET_INSTALL_PLAN_MISMATCH
        | ERROR_CODE_RECORDING_CONSENT_REQUIRED
        | ERROR_CODE_CALL_SUMMARY_INVALID
        | ERROR_CODE_CALL_ALREADY_ANSWERED => 409,
        ERROR_CODE_HISTORICAL_ONLY => 200,
        ERROR_CODE_CURSOR_EXPIRED
        | ERROR_CODE_CURSOR_REVOKED
        | ERROR_CODE_BLOB_EXPIRED
        | ERROR_CODE_DID_REVOKED
        | ERROR_CODE_CALL_EXPIRED => 410,
        ERROR_CODE_PAYLOAD_TOO_LARGE
        | ERROR_CODE_PUSH_PAYLOAD_TOO_LARGE
        | ERROR_CODE_TOO_LARGE
        | ERROR_CODE_LIMIT_EXCEEDED => 413,
        ERROR_CODE_SCHEMA_VIOLATION
        | ERROR_CODE_DIGEST_MISMATCH
        | ERROR_CODE_AAD_DIGEST_MISMATCH
        | ERROR_CODE_PAYLOAD_DIGEST_MISMATCH
        | ERROR_CODE_UNKNOWN_DID
        | ERROR_CODE_POLICY_COMBINATION_INVALID
        | ERROR_CODE_HISTORY_SHARING_POLICY_MISSING
        | ERROR_CODE_NOTARY_RECOVERY_MISSING
        | ERROR_CODE_UNSUPPORTED_LATTICE_TYPE
        | ERROR_CODE_UNSUPPORTED_HASH
        | ERROR_CODE_SHARE_COMMITMENT_MISMATCH
        | ERROR_CODE_RECOVERY_EVIDENCE_UNBOUND
        | ERROR_CODE_READ_RECEIPT_COMPLIANCE_FLOOR_VIOLATED
        | ERROR_CODE_PAIRING_REQUEST_EXPIRED
        | ERROR_CODE_UNKNOWN_FOCUS_TYPE
        | ERROR_CODE_PARTICIPANT_BINDING_INVALID
        | ERROR_CODE_PARTICIPANT_IDENTITY_UNRECOGNISED
        | ERROR_CODE_PROFILE_UNSUPPORTED
        | ERROR_CODE_BLOB_DIGEST_MISMATCH
        | ERROR_CODE_UNSUPPORTED_DID_METHOD
        | ERROR_CODE_UNSUPPORTED_MEDIA_POLICY
        | ERROR_CODE_UNSUPPORTED_JOIN_RULE
        | ERROR_CODE_INVALID_AVATAR_BLOB_REF
        | ERROR_CODE_UNSUPPORTED_PROFILE_PATCH_PATH
        | ERROR_CODE_SESSION_REVOKE_SELECTOR_CONFLICT
        | ERROR_CODE_MORPH_PROFILE_WIDENS_SCHEMA_REF
        | ERROR_CODE_MORPH_TYPE_IMMUTABLE => 422,
        ERROR_CODE_RATE_LIMITED => 429,
        ERROR_CODE_INTERNAL_ERROR => 500,
        ERROR_CODE_HLC_LOGICAL_OVERFLOW
        | ERROR_CODE_TEMPORARILY_UNAVAILABLE
        | ERROR_CODE_FRANKING_PROOF_UNAVAILABLE
        | ERROR_CODE_EPHEMERAL_CHANNEL_UNAVAILABLE
        | ERROR_CODE_FRONTIER_UNAVAILABLE
        | ERROR_CODE_POLICY_UNAVAILABLE
        | ERROR_CODE_PUSH_GATEWAY_UNREACHABLE
        | ERROR_CODE_SNAPSHOT_UNAVAILABLE
        | ERROR_CODE_SERVICE_UNAVAILABLE => 503,
        ERROR_CODE_TIMEOUT => 504,
        ERROR_CODE_UNSUPPORTED_FEATURE
        | ERROR_CODE_UNSUPPORTED_EVENT_KIND
        | ERROR_CODE_UNSUPPORTED_AEAD_PROFILE
        | ERROR_CODE_NOT_IMPLEMENTED => 501,
        _ => return None,
    })
}
