use std::path::PathBuf;

use super::*;

fn local_spec_artifacts_dir() -> Option<PathBuf> {
    if let Some(dir) = crate::schema::default_spec_artifacts_dir() {
        return Some(dir);
    }
    let candidate = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .join("arkret-spec")
        .join("spec")
        .join("v1")
        .join("artifacts");
    candidate.is_dir().then_some(candidate)
}

/// Generator gate (closes the manual-mirror drift class behind SDK-SPEC-01/02/03):
/// every `ERROR_CODE_*` constant declared in `codes.rs` MUST be a registered
/// top-level code, and every registered top-level code MUST have a constant.
/// `codes.rs` is generated by `tools/generate-sdk-error-codes.ps1`; this test
/// fails if a hand-edit reintroduces an orphan constant (a `reason_code` mislabeled
/// as `ERROR_CODE_*`, or a wire code with no registry entry) or drops one.
#[test]
fn error_code_constants_exactly_match_registry_codes() {
    let source = include_str!("../../../wire-base/src/error_codes/codes.rs");
    let mut declared: Vec<String> = Vec::new();
    for line in source.lines() {
        let line = line.trim_start();
        let Some(rest) = line.strip_prefix("pub const ERROR_CODE_") else {
            continue;
        };
        // The value is the quoted literal somewhere on this line (single-line
        // form) or, for wrapped declarations, on the next line; both forms keep
        // the literal inside double quotes, so extract it directly from `rest`
        // when present, else from the declaration as a whole.
        let value = rest
            .split_once('"')
            .and_then(|(_, after)| after.split_once('"').map(|(v, _)| v.to_owned()));
        if let Some(value) = value {
            declared.push(value);
        }
    }
    // Wrapped declarations put the literal on the following line; pick those up.
    let mut lines = source.lines();
    while let Some(line) = lines.next() {
        let trimmed = line.trim_start();
        if !(trimmed.starts_with("pub const ERROR_CODE_") && trimmed.ends_with("&str =")) {
            continue;
        }
        let Some(next) = lines.next() else {
            continue;
        };
        if let Some(value) = next
            .trim_start()
            .split_once('"')
            .and_then(|(_, after)| after.split_once('"').map(|(v, _)| v.to_owned()))
        {
            declared.push(value);
        }
    }

    let declared: std::collections::BTreeSet<String> = declared.into_iter().collect();
    let registry: std::collections::BTreeSet<String> = crate::schema::embedded_error_code_codes()
        .expect("embedded error-code-registry codes must load")
        .into_iter()
        .collect();

    let orphans: Vec<&String> = declared.difference(&registry).collect();
    assert!(
        orphans.is_empty(),
        "codes.rs declares ERROR_CODE_* constants absent from \
         error-code-registry.json codes (regenerate via \
         tools/generate-sdk-error-codes.ps1): {orphans:?}",
    );
    let missing: Vec<&String> = registry.difference(&declared).collect();
    assert!(
        missing.is_empty(),
        "error-code-registry.json codes missing an ERROR_CODE_* constant \
         (regenerate via tools/generate-sdk-error-codes.ps1): {missing:?}",
    );
}

#[test]
fn every_known_error_code_has_http_status() {
    for code in KNOWN_ERROR_CODES {
        assert!(
            error_code_http_status(code).is_some(),
            "known error code {code:?} has no HTTP status mapping",
        );
    }
}

#[test]
fn known_error_codes_match_embedded_registry() {
    let embedded = crate::schema::embedded_error_code_codes()
        .expect("embedded error-code-registry codes must load");
    assert_eq!(KNOWN_ERROR_CODES, embedded.as_slice());
}

#[test]
fn known_error_codes_match_live_registry_when_available() {
    let Some(artifacts_dir) = local_spec_artifacts_dir() else {
        return;
    };
    let registry_path = artifacts_dir
        .join("registry")
        .join("error-code-registry.json");
    let text = std::fs::read_to_string(&registry_path)
        .unwrap_or_else(|error| panic!("failed to read {}: {error}", registry_path.display()));
    let registry: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|error| panic!("failed to parse {}: {error}", registry_path.display()));
    let live: Vec<String> = registry
        .get("codes")
        .and_then(serde_json::Value::as_array)
        .expect("live error-code-registry missing codes array")
        .iter()
        .map(|entry| {
            entry
                .get("code")
                .and_then(serde_json::Value::as_str)
                .expect("live error-code-registry code entry missing code")
                .to_owned()
        })
        .collect();
    assert_eq!(KNOWN_ERROR_CODES, live.as_slice());
}

/// `ErrorCode::ALL` MUST contain one variant per entry in
/// `KNOWN_ERROR_CODES`.
#[test]
fn error_code_enum_matches_registry() {
    assert_eq!(ErrorCode::ALL.len(), KNOWN_ERROR_CODES.len());
    for code in ErrorCode::ALL {
        let wire = code.as_str();
        assert!(
            is_known_error_code(wire),
            "ErrorCode::{:?} → {wire:?} missing from KNOWN_ERROR_CODES",
            code
        );
        assert_eq!(
            ErrorCode::from_wire(wire),
            Some(code),
            "round-trip mismatch for ErrorCode::{:?}",
            code,
        );
    }
    for wire in KNOWN_ERROR_CODES {
        assert!(
            ErrorCode::from_wire(wire).is_some(),
            "registry wire {wire:?} has no ErrorCode variant",
        );
    }
}

/// Every variant MUST resolve to an HTTP status via
/// `error_code_http_status`. Catches drift between the registry
/// table and the HTTP-status `match` arm.
#[test]
fn every_variant_has_http_status() {
    for code in ErrorCode::ALL {
        let status = code.http_status();
        assert!(
            (100..=599).contains(&status),
            "ErrorCode::{:?} returned status {status}",
            code,
        );
    }
}

/// Resolve subordinate reason codes from the live spec checkout when
/// available, falling back to the embedded snapshot.
fn registry_reason_codes() -> Vec<String> {
    if let Some(artifacts_dir) = local_spec_artifacts_dir() {
        let registry_path = artifacts_dir
            .join("registry")
            .join("error-code-registry.json");
        if let Ok(text) = std::fs::read_to_string(&registry_path) {
            let registry: serde_json::Value = serde_json::from_str(&text).unwrap_or_else(|error| {
                panic!("failed to parse {}: {error}", registry_path.display())
            });
            let identifiers: Vec<String> = registry
                .get("reason_codes")
                .and_then(serde_json::Value::as_array)
                .expect("live error-code-registry missing reason_codes")
                .iter()
                .map(|entry| {
                    entry
                        .get("code")
                        .and_then(serde_json::Value::as_str)
                        .expect("live reason-code entry missing code")
                        .to_owned()
                })
                .collect();
            assert!(
                !identifiers.is_empty(),
                "live error-code-registry.json declared no reason_codes",
            );
            return identifiers;
        }
    }
    crate::schema::embedded_error_code_reason_codes()
        .expect("embedded error-code-registry reason codes must load")
}

/// The generated reason-code module is an exact, ordered registry mirror.
#[test]
fn known_reason_codes_exactly_match_registry() {
    assert_eq!(KNOWN_REASON_CODES, registry_reason_codes().as_slice());
}
