param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\arkret-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\schema\src\generated\profile_requirements.rs")
)

. (Join-Path $PSScriptRoot 'utf8-byte-order.ps1')

# Emits crates/schema/src/generated/profile_requirements.rs from
# arkret-spec/spec/v1/artifacts/profiles/conformance-profiles.json.
#
# Mirrors the style of tools/generate-sdk-event-kinds.ps1 but produces a
# richer module exposing per-profile inheritance, required operations / event
# kinds / schemas / fixtures / features / capability actions / cells /
# constraint kinds together with a structured validator.
#
# The artifact field `required_endpoints` is surfaced as `required_operations`
# to match the rest of the Arkret SDK vocabulary (operation registry, etc).
# Constraint kinds aggregate `required_constraint_kinds` and
# `required_constraint_subkinds` from the artifact.

$profilesPath = Join-Path $ArtifactsDir "profiles\conformance-profiles.json"
if (!(Test-Path -LiteralPath $profilesPath)) {
    throw "conformance profile artifact not found: $profilesPath"
}

$raw = Get-Content -LiteralPath $profilesPath -Raw
$artifact = $raw | ConvertFrom-Json
$digest = (Get-FileHash -LiteralPath $profilesPath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($null -eq $artifact.profile_requirements) {
    throw "conformance profile artifact missing top-level 'profile_requirements' object"
}

function Get-StringArray {
    param($Source, [string]$Field)
    if ($null -eq $Source) { return ,@() }
    $value = $Source.$Field
    if ($null -eq $value) { return ,@() }
    $arr = @($value | ForEach-Object { [string]$_ })
    return ,$arr
}

# PSCustomObject -> UTF-8-byte-sorted profile_id list.
$profileIds = Sort-Utf8ByteLexicographic -Values @(
    $artifact.profile_requirements.PSObject.Properties.Name
)

function Format-RustStrSlice {
    param([string[]]$Values, [int]$Indent)
    $pad = ' ' * $Indent
    if ($Values.Count -eq 0) {
        return "&[]"
    }
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("&[")
    [void]$sb.Append([Environment]::NewLine)
    foreach ($v in $Values) {
        $escaped = $v.Replace('\', '\\').Replace('"', '\"')
        [void]$sb.Append($pad)
        [void]$sb.Append('    "')
        [void]$sb.Append($escaped)
        [void]$sb.Append('",')
        [void]$sb.Append([Environment]::NewLine)
    }
    [void]$sb.Append($pad)
    [void]$sb.Append(']')
    return $sb.ToString()
}

function Escape-RustString {
    param([string]$Value)
    return $Value.Replace('\', '\\').Replace('"', '\"')
}

function Format-NonEventGrantAuthorityRules {
    param($Rules, [int]$Indent)
    if ($null -eq $Rules) {
        return "&[]"
    }
    $items = @($Rules)
    if ($items.Count -eq 0) {
        return "&[]"
    }
    $pad = ' ' * $Indent
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append("&[")
    [void]$sb.Append([Environment]::NewLine)
    foreach ($rule in $items) {
        [void]$sb.Append($pad)
        [void]$sb.Append("    NonEventGrantAuthorityRule {")
        [void]$sb.Append([Environment]::NewLine)
        foreach ($field in @(
            'issuer_action',
            'grantable_action',
            'required_registration_event_kind',
            'required_claimed_profile',
            'required_constraint_kind',
            'required_constraint_subkind',
            'subject_binding',
            'scope_binding',
            'epoch_binding',
            'requested_action_binding'
        )) {
            $value = Escape-RustString -Value ([string]$rule.$field)
            [void]$sb.Append($pad)
            [void]$sb.Append("        ${field}: `"$value`",")
            [void]$sb.Append([Environment]::NewLine)
        }
        $ownerAllowed = if ($rule.issuer_owner_authority_allowed) { "true" } else { "false" }
        [void]$sb.Append($pad)
        [void]$sb.Append("        issuer_owner_authority_allowed: $ownerAllowed,")
        [void]$sb.Append([Environment]::NewLine)
        [void]$sb.Append($pad)
        [void]$sb.Append("    },")
        [void]$sb.Append([Environment]::NewLine)
    }
    [void]$sb.Append($pad)
    [void]$sb.Append(']')
    return $sb.ToString()
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("//! Generated conformance profile requirements + validator.") | Out-Null
$lines.Add("//!") | Out-Null
$lines.Add("//! @generated by tools/generate-sdk-profile-requirements.ps1 from") | Out-Null
$lines.Add("//! arkret-spec/spec/v1/artifacts/profiles/conformance-profiles.json; do not edit by hand.") | Out-Null
$lines.Add("//! Input version: $($artifact.version); sha256=$digest; requirements=$($profileIds.Count).") | Out-Null
$lines.Add("//!") | Out-Null
$lines.Add('//! `required_operations` corresponds to the artifact field `required_endpoints`.') | Out-Null
$lines.Add('//! `required_constraint_kinds` is the sorted union of the artifact fields') | Out-Null
$lines.Add('//! `required_constraint_kinds`, `required_constraint_subkinds`, and any') | Out-Null
$lines.Add('//! explicit `required_constraint_kinds` entries.') | Out-Null
$lines.Add('//! Additional profile-gate fields are surfaced verbatim so services and') | Out-Null
$lines.Add('//! conformance tests do not need to parse the JSON artifact directly.') | Out-Null
$lines.Add("") | Out-Null
$lines.Add("use std::collections::BTreeMap;") | Out-Null
$lines.Add("use std::sync::LazyLock;") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("/// Closed machine rule authorizing one non-event capability grant surface.") | Out-Null
$lines.Add("#[derive(Clone, Copy, Debug, PartialEq, Eq)]") | Out-Null
$lines.Add("pub struct NonEventGrantAuthorityRule {") | Out-Null
$lines.Add("    pub issuer_action: &'static str,") | Out-Null
$lines.Add("    /// When true the issuer side additionally accepts Realm effective owner") | Out-Null
$lines.Add("    /// authority (authority-root controller or an active co-owner grant) in") | Out-Null
$lines.Add("    /// place of literally holding `issuer_action`. Every other gate in this") | Out-Null
$lines.Add("    /// rule still applies unchanged.") | Out-Null
$lines.Add("    pub issuer_owner_authority_allowed: bool,") | Out-Null
$lines.Add("    pub grantable_action: &'static str,") | Out-Null
$lines.Add("    pub required_registration_event_kind: &'static str,") | Out-Null
$lines.Add("    pub required_claimed_profile: &'static str,") | Out-Null
$lines.Add("    pub required_constraint_kind: &'static str,") | Out-Null
$lines.Add("    pub required_constraint_subkind: &'static str,") | Out-Null
$lines.Add("    pub subject_binding: &'static str,") | Out-Null
$lines.Add("    pub scope_binding: &'static str,") | Out-Null
$lines.Add("    pub epoch_binding: &'static str,") | Out-Null
$lines.Add("    pub requested_action_binding: &'static str,") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("/// Frozen requirement set for a conformance profile.") | Out-Null
$lines.Add("#[derive(Clone, Copy, Debug, PartialEq, Eq)]") | Out-Null
$lines.Add("pub struct ProfileRequirements {") | Out-Null
$lines.Add("    pub profile_id: &'static str,") | Out-Null
$lines.Add("    pub inherits: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_operations: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_event_kinds: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_schemas: &'static [&'static str],") | Out-Null
$lines.Add("    pub rejected_event_kinds: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_fixtures: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_capability_actions: &'static [&'static str],") | Out-Null
$lines.Add('    /// Sorted union of top-level `required_features` and') | Out-Null
$lines.Add('    /// `feature_discovery.required` from the profile artifact.') | Out-Null
$lines.Add("    pub required_features: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_cell_namespaces: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_cells: &'static [&'static str],") | Out-Null
$lines.Add("    pub required_constraint_kinds: &'static [&'static str],") | Out-Null
$lines.Add("    /// Profile-gated actions this profile registers as owner-grantable") | Out-Null
$lines.Add("    /// (`capabilities.md` section 3.2). Absent from this list means a Realm") | Out-Null
$lines.Add("    /// owner cannot sign a grant for the action even while the profile is") | Out-Null
$lines.Add("    /// active; being listed does not waive the profile's own gates.") | Out-Null
$lines.Add("    pub non_event_grant_authority_rules: &'static [NonEventGrantAuthorityRule],") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("/// Profile requirements as a sorted map keyed by profile_id.") | Out-Null
$lines.Add("pub static PROFILE_REQUIREMENTS: LazyLock<BTreeMap<&'static str, ProfileRequirements>> =") | Out-Null
$lines.Add("    LazyLock::new(|| {") | Out-Null
$lines.Add("        let mut map: BTreeMap<&'static str, ProfileRequirements> = BTreeMap::new();") | Out-Null

foreach ($profileId in $profileIds) {
    $entry = $artifact.profile_requirements.$profileId
    $inherits = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'inherits')
    $required_operations = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_endpoints')
    $required_event_kinds = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_event_kinds')
    $required_schemas = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_schemas')
    $rejected_event_kinds = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'rejected_event_kinds')
    $required_fixtures = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_fixtures')
    $required_capability_actions = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_capability_actions')
    [string[]]$required_features_input = @()
    $required_features_input += Get-StringArray -Source $entry -Field 'required_features'
    $required_features_input += Get-StringArray -Source $entry.feature_discovery -Field 'required'
    $required_features = Sort-Utf8ByteLexicographic -Values $required_features_input
    $required_cell_namespaces = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_cell_namespaces')
    $required_cells = Sort-Utf8ByteLexicographic -Values (Get-StringArray -Source $entry -Field 'required_cells')
    $constraint_kinds = Get-StringArray -Source $entry -Field 'required_constraint_kinds'
    $constraint_subkinds = Get-StringArray -Source $entry -Field 'required_constraint_subkinds'
    $constraint_kinds_field = Get-StringArray -Source $entry -Field 'required_constraint_kinds'
    $combined = [string[]]@()
    $combined += $constraint_kinds
    $combined += $constraint_subkinds
    $combined += $constraint_kinds_field
    $required_constraint_kinds = Sort-Utf8ByteLexicographic -Values $combined
    $non_event_grant_authority_rules = $entry.non_event_grant_authority_rules

    $escapedId = $profileId.Replace('\', '\\').Replace('"', '\"')
    $lines.Add("        map.insert(") | Out-Null
    $lines.Add("            `"$escapedId`",") | Out-Null
    $lines.Add("            ProfileRequirements {") | Out-Null
    $lines.Add("                profile_id: `"$escapedId`",") | Out-Null
    $lines.Add("                inherits: " + (Format-RustStrSlice -Values $inherits -Indent 16) + ",") | Out-Null
    $lines.Add("                required_operations: " + (Format-RustStrSlice -Values $required_operations -Indent 16) + ",") | Out-Null
    $lines.Add("                required_event_kinds: " + (Format-RustStrSlice -Values $required_event_kinds -Indent 16) + ",") | Out-Null
    $lines.Add("                required_schemas: " + (Format-RustStrSlice -Values $required_schemas -Indent 16) + ",") | Out-Null
    $lines.Add("                rejected_event_kinds: " + (Format-RustStrSlice -Values $rejected_event_kinds -Indent 16) + ",") | Out-Null
    $lines.Add("                required_fixtures: " + (Format-RustStrSlice -Values $required_fixtures -Indent 16) + ",") | Out-Null
    $lines.Add("                required_capability_actions: " + (Format-RustStrSlice -Values $required_capability_actions -Indent 16) + ",") | Out-Null
    $lines.Add("                required_features: " + (Format-RustStrSlice -Values $required_features -Indent 16) + ",") | Out-Null
    $lines.Add("                required_cell_namespaces: " + (Format-RustStrSlice -Values $required_cell_namespaces -Indent 16) + ",") | Out-Null
    $lines.Add("                required_cells: " + (Format-RustStrSlice -Values $required_cells -Indent 16) + ",") | Out-Null
    $lines.Add("                required_constraint_kinds: " + (Format-RustStrSlice -Values $required_constraint_kinds -Indent 16) + ",") | Out-Null
    $lines.Add("                non_event_grant_authority_rules: " + (Format-NonEventGrantAuthorityRules -Rules $non_event_grant_authority_rules -Indent 16) + ",") | Out-Null
    $lines.Add("            },") | Out-Null
    $lines.Add("        );") | Out-Null
}

$lines.Add("        map") | Out-Null
$lines.Add("    });") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("/// Sorted list of all profile_ids that have a generated requirement entry.") | Out-Null
$lines.Add("pub fn known_profile_ids() -> Vec<&'static str> {") | Out-Null
$lines.Add("    PROFILE_REQUIREMENTS.keys().copied().collect()") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Returns the requirements for `profile_id` if it is a known v1 profile.') | Out-Null
$lines.Add("pub fn requirements_for(profile_id: &str) -> Option<&'static ProfileRequirements> {") | Out-Null
$lines.Add("    PROFILE_REQUIREMENTS.get(profile_id)") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Returns the exact non-event grant authority rule registered by a profile.') | Out-Null
$lines.Add("pub fn non_event_grant_authority_rule(") | Out-Null
$lines.Add("    profile_id: &str,") | Out-Null
$lines.Add("    grantable_action: &str,") | Out-Null
$lines.Add(") -> Option<&'static NonEventGrantAuthorityRule> {") | Out-Null
$lines.Add("    requirements_for(profile_id)?") | Out-Null
$lines.Add("        .non_event_grant_authority_rules") | Out-Null
$lines.Add("        .iter()") | Out-Null
$lines.Add("        .find(|rule| rule.grantable_action == grantable_action)") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Structured failure produced by [`validate_profile_requirements`].') | Out-Null
$lines.Add('#[derive(Clone, Debug, PartialEq, Eq)]') | Out-Null
$lines.Add('pub enum ProfileRequirementsError {') | Out-Null
$lines.Add('    /// `profile_id` is not a v1 profile recognised by the generated table.') | Out-Null
$lines.Add('    UnknownProfile { profile_id: String },') | Out-Null
$lines.Add('    /// The profile is known but the caller has not implemented every required') | Out-Null
$lines.Add('    /// operation / event kind / schema. The vectors are owned, sorted and') | Out-Null
$lines.Add('    /// deduplicated.') | Out-Null
$lines.Add("    MissingRequirements {") | Out-Null
$lines.Add("        profile_id: String,") | Out-Null
$lines.Add("        missing_operations: Vec<String>,") | Out-Null
$lines.Add("        missing_event_kinds: Vec<String>,") | Out-Null
$lines.Add("        missing_schemas: Vec<String>,") | Out-Null
$lines.Add("    },") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("impl std::fmt::Display for ProfileRequirementsError {") | Out-Null
$lines.Add("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {") | Out-Null
$lines.Add("        match self {") | Out-Null
$lines.Add("            Self::UnknownProfile { profile_id } => {") | Out-Null
$lines.Add("                write!(f, `"unknown conformance profile: {profile_id}`")") | Out-Null
$lines.Add("            }") | Out-Null
$lines.Add("            Self::MissingRequirements {") | Out-Null
$lines.Add("                profile_id,") | Out-Null
$lines.Add("                missing_operations,") | Out-Null
$lines.Add("                missing_event_kinds,") | Out-Null
$lines.Add("                missing_schemas,") | Out-Null
$lines.Add("            } => write!(") | Out-Null
$lines.Add("                f,") | Out-Null
$lines.Add("                `"profile {profile_id} missing requirements: ops={missing_operations:?} event_kinds={missing_event_kinds:?} schemas={missing_schemas:?}`"") | Out-Null
$lines.Add("            ),") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("impl std::error::Error for ProfileRequirementsError {}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("/// Structured report describing how a caller's implemented surface compares") | Out-Null
$lines.Add("/// against a profile's generated requirement set. Consumed by") | Out-Null
$lines.Add('/// `soland describe` / `inkson claim` / `cotest gate` so each surface presents') | Out-Null
$lines.Add('/// the same compliance answer.') | Out-Null
$lines.Add("#[derive(Clone, Debug, PartialEq, Eq)]") | Out-Null
$lines.Add("pub struct ProfileComplianceReport {") | Out-Null
$lines.Add("    pub profile_id: String,") | Out-Null
$lines.Add("    pub satisfied_operations: Vec<String>,") | Out-Null
$lines.Add("    pub missing_operations: Vec<String>,") | Out-Null
$lines.Add("    pub satisfied_event_kinds: Vec<String>,") | Out-Null
$lines.Add("    pub missing_event_kinds: Vec<String>,") | Out-Null
$lines.Add("    pub satisfied_schemas: Vec<String>,") | Out-Null
$lines.Add("    pub missing_schemas: Vec<String>,") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("impl ProfileComplianceReport {") | Out-Null
$lines.Add("    /// True iff the caller satisfies every requirement.") | Out-Null
$lines.Add("    pub fn is_compliant(&self) -> bool {") | Out-Null
$lines.Add("        self.missing_operations.is_empty()") | Out-Null
$lines.Add("            && self.missing_event_kinds.is_empty()") | Out-Null
$lines.Add("            && self.missing_schemas.is_empty()") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Validates that `implemented_*` covers every requirement of `profile_id`.') | Out-Null
$lines.Add('///') | Out-Null
$lines.Add('/// Returns `ProfileRequirementsError::UnknownProfile` if `profile_id` is not in') | Out-Null
$lines.Add('/// the generated table, or `ProfileRequirementsError::MissingRequirements` with') | Out-Null
$lines.Add('/// sorted-deduplicated diff lists if at least one requirement is unmet.') | Out-Null
$lines.Add("pub fn validate_profile_requirements(") | Out-Null
$lines.Add("    profile_id: &str,") | Out-Null
$lines.Add("    implemented_operations: &[&str],") | Out-Null
$lines.Add("    implemented_event_kinds: &[&str],") | Out-Null
$lines.Add("    implemented_schemas: &[&str],") | Out-Null
$lines.Add(") -> Result<(), ProfileRequirementsError> {") | Out-Null
$lines.Add("    let Some(req) = PROFILE_REQUIREMENTS.get(profile_id) else {") | Out-Null
$lines.Add("        return Err(ProfileRequirementsError::UnknownProfile {") | Out-Null
$lines.Add("            profile_id: profile_id.to_owned(),") | Out-Null
$lines.Add("        });") | Out-Null
$lines.Add("    };") | Out-Null
$lines.Add("    let impl_ops: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_operations.iter().copied().collect();") | Out-Null
$lines.Add("    let impl_kinds: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_event_kinds.iter().copied().collect();") | Out-Null
$lines.Add("    let impl_schemas: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_schemas.iter().copied().collect();") | Out-Null
$lines.Add("    let missing_operations: Vec<String> = req") | Out-Null
$lines.Add("        .required_operations") | Out-Null
$lines.Add("        .iter()") | Out-Null
$lines.Add("        .filter(|op| !impl_ops.contains(*op))") | Out-Null
$lines.Add("        .map(|s| (*s).to_owned())") | Out-Null
$lines.Add("        .collect();") | Out-Null
$lines.Add("    let missing_event_kinds: Vec<String> = req") | Out-Null
$lines.Add("        .required_event_kinds") | Out-Null
$lines.Add("        .iter()") | Out-Null
$lines.Add("        .filter(|kind| !impl_kinds.contains(*kind))") | Out-Null
$lines.Add("        .map(|s| (*s).to_owned())") | Out-Null
$lines.Add("        .collect();") | Out-Null
$lines.Add("    let missing_schemas: Vec<String> = req") | Out-Null
$lines.Add("        .required_schemas") | Out-Null
$lines.Add("        .iter()") | Out-Null
$lines.Add("        .filter(|s| !impl_schemas.contains(*s))") | Out-Null
$lines.Add("        .map(|s| (*s).to_owned())") | Out-Null
$lines.Add("        .collect();") | Out-Null
$lines.Add("    if missing_operations.is_empty()") | Out-Null
$lines.Add("        && missing_event_kinds.is_empty()") | Out-Null
$lines.Add("        && missing_schemas.is_empty()") | Out-Null
$lines.Add("    {") | Out-Null
$lines.Add("        Ok(())") | Out-Null
$lines.Add("    } else {") | Out-Null
$lines.Add("        Err(ProfileRequirementsError::MissingRequirements {") | Out-Null
$lines.Add("            profile_id: profile_id.to_owned(),") | Out-Null
$lines.Add("            missing_operations,") | Out-Null
$lines.Add("            missing_event_kinds,") | Out-Null
$lines.Add("            missing_schemas,") | Out-Null
$lines.Add("        })") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// High-level helper: returns a [`ProfileComplianceReport`] describing exactly') | Out-Null
$lines.Add('/// which requirements are satisfied vs missing. Returns') | Out-Null
$lines.Add('/// `ProfileRequirementsError::UnknownProfile` when `profile_id` is not in the') | Out-Null
$lines.Add('/// generated table; never returns `MissingRequirements` (the report itself') | Out-Null
$lines.Add('/// captures the diff regardless of compliance).') | Out-Null
$lines.Add("pub fn profile_compliance_report(") | Out-Null
$lines.Add("    profile_id: &str,") | Out-Null
$lines.Add("    implemented_operations: &[&str],") | Out-Null
$lines.Add("    implemented_event_kinds: &[&str],") | Out-Null
$lines.Add("    implemented_schemas: &[&str],") | Out-Null
$lines.Add(") -> Result<ProfileComplianceReport, ProfileRequirementsError> {") | Out-Null
$lines.Add("    let Some(req) = PROFILE_REQUIREMENTS.get(profile_id) else {") | Out-Null
$lines.Add("        return Err(ProfileRequirementsError::UnknownProfile {") | Out-Null
$lines.Add("            profile_id: profile_id.to_owned(),") | Out-Null
$lines.Add("        });") | Out-Null
$lines.Add("    };") | Out-Null
$lines.Add("    let impl_ops: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_operations.iter().copied().collect();") | Out-Null
$lines.Add("    let impl_kinds: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_event_kinds.iter().copied().collect();") | Out-Null
$lines.Add("    let impl_schemas: std::collections::BTreeSet<&str> =") | Out-Null
$lines.Add("        implemented_schemas.iter().copied().collect();") | Out-Null
$lines.Add("    let mut satisfied_operations = Vec::new();") | Out-Null
$lines.Add("    let mut missing_operations = Vec::new();") | Out-Null
$lines.Add("    for op in req.required_operations {") | Out-Null
$lines.Add("        if impl_ops.contains(op) {") | Out-Null
$lines.Add("            satisfied_operations.push((*op).to_owned());") | Out-Null
$lines.Add("        } else {") | Out-Null
$lines.Add("            missing_operations.push((*op).to_owned());") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("    let mut satisfied_event_kinds = Vec::new();") | Out-Null
$lines.Add("    let mut missing_event_kinds = Vec::new();") | Out-Null
$lines.Add("    for kind in req.required_event_kinds {") | Out-Null
$lines.Add("        if impl_kinds.contains(kind) {") | Out-Null
$lines.Add("            satisfied_event_kinds.push((*kind).to_owned());") | Out-Null
$lines.Add("        } else {") | Out-Null
$lines.Add("            missing_event_kinds.push((*kind).to_owned());") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("    let mut satisfied_schemas = Vec::new();") | Out-Null
$lines.Add("    let mut missing_schemas = Vec::new();") | Out-Null
$lines.Add("    for schema in req.required_schemas {") | Out-Null
$lines.Add("        if impl_schemas.contains(schema) {") | Out-Null
$lines.Add("            satisfied_schemas.push((*schema).to_owned());") | Out-Null
$lines.Add("        } else {") | Out-Null
$lines.Add("            missing_schemas.push((*schema).to_owned());") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("    Ok(ProfileComplianceReport {") | Out-Null
$lines.Add("        profile_id: profile_id.to_owned(),") | Out-Null
$lines.Add("        satisfied_operations,") | Out-Null
$lines.Add("        missing_operations,") | Out-Null
$lines.Add("        satisfied_event_kinds,") | Out-Null
$lines.Add("        missing_event_kinds,") | Out-Null
$lines.Add("        satisfied_schemas,") | Out-Null
$lines.Add("        missing_schemas,") | Out-Null
$lines.Add("    })") | Out-Null
$lines.Add("}") | Out-Null

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline
& rustfmt +nightly --edition 2024 $OutputPath
if ($LASTEXITCODE -ne 0) { throw "rustfmt failed for $OutputPath" }
Write-Host "Wrote $OutputPath ($($profileIds.Count) profiles)"
