#!/usr/bin/env python3
"""Generate the executable cell-family lattice bindings from the spec registry."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


LATTICE_VARIANTS = {
    "or_set": "OrSet",
    "cas_register": "CasRegister",
    "fsm": "Fsm",
    "ordered_log": "OrderedLog",
    "mv_register": "MvRegister",
    "counter": "Counter",
}

BOTTOM_VARIANTS = {
    "reject": "Reject",
    "expose": "Expose",
    "inert": "Inert",
}


def cell_family_constant(family: str) -> str:
    body = family.removeprefix("ak.component.")
    return re.sub(r"[^A-Za-z0-9]+", "_", body).upper()


def collect_bindings(registry: dict) -> dict[str, tuple[str, str]]:
    event_kinds = registry.get("event_kinds")
    if not isinstance(event_kinds, list):
        raise ValueError("event-kind registry must contain an event_kinds array")

    bindings: dict[str, tuple[str, str]] = {}
    for event in event_kinds:
        if not isinstance(event, dict):
            raise ValueError("event-kind registry entries must be objects")
        if event.get("status") != "active":
            continue
        raw_writes = event.get("cell_writes")
        if raw_writes is not None and not isinstance(raw_writes, list):
            raise ValueError(
                f"{event.get('event_kind')} has a non-array cell_writes member"
            )
        writes = list(raw_writes or [])
        if event.get("cell_family") is not None:
            writes.append(
                {
                    "cell_family": event.get("cell_family"),
                    "lattice": event.get("lattice"),
                    "bottom": event.get("bottom"),
                }
            )
        for write in writes:
            if not isinstance(write, dict):
                raise ValueError(
                    f"{event.get('event_kind')} has a non-object cell write"
                )
            family = write.get("cell_family")
            lattice = write.get("lattice")
            bottom = write.get("bottom")
            if family is None and lattice is None and bottom is None:
                # Dynamic writes carry a full cell_ref in the payload and
                # resolve through the target family's separately registered binding.
                continue
            if not all(isinstance(value, str) for value in (family, lattice, bottom)):
                raise ValueError(
                    f"{event.get('event_kind')} has an incomplete cell lattice binding"
                )
            binding = (lattice, bottom)
            previous = bindings.setdefault(family, binding)
            if previous != binding:
                raise ValueError(
                    f"{family} has conflicting bindings: {previous} and {binding}"
                )
    return bindings


def render(source_path: Path, registry: dict) -> str:
    source_digest = hashlib.sha256(source_path.read_bytes()).hexdigest()
    bindings = collect_bindings(registry)
    rows = []
    for family, (lattice, bottom) in sorted(bindings.items()):
        try:
            lattice_variant = LATTICE_VARIANTS[lattice]
            bottom_variant = BOTTOM_VARIANTS[bottom]
        except KeyError as error:
            raise ValueError(f"unsupported registry value: {error.args[0]}") from error
        rows.append(
            "    ("
            f"CellFamilyId::{cell_family_constant(family)}, "
            f"LatticeKind::{lattice_variant}, BottomMode::{bottom_variant}),"
        )
    return "\n".join(
        [
            "// @generated by tools/generate-sdk-lattice-bindings.py; do not edit.",
            f"// Source sha256: {source_digest}",
            "",
            "use arkret_state::lattice::LatticeKind;",
            "use arkret_state::state::BottomMode;",
            "use arkret_wire::CellFamilyId;",
            "",
            "pub(crate) const SPEC_LATTICE_BINDINGS: &[(&str, LatticeKind, BottomMode)] = &[",
            *rows,
            "];",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifacts-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    source_path = args.artifacts_dir / "registry" / "event-kind-registry.json"
    registry = json.loads(source_path.read_text(encoding="utf-8"))
    output = render(source_path, registry)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({len(collect_bindings(registry))} bindings)")


if __name__ == "__main__":
    main()
