param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\cokret-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\error\codes.rs")
)

# Emits crates/core/src/error/codes.rs from
# cokret-spec/spec/v1/artifacts/registry/error-code-registry.json.
#
# One `pub const ERROR_CODE_<UPPER>: &str = "<code>"` per top-level `codes`
# entry (canonical wire error codes), in registry order, plus the
# `KNOWN_ERROR_CODES` slice listing every constant in the same order.
#
# Only the top-level `codes` array is emitted here. `reason_codes` (the
# `failed_precondition` sub-reasons) are hand-curated in reasons.rs as
# `REASON_*` constants; mixing them in here as `ERROR_CODE_*` is exactly the
# drift this generator exists to prevent.

$registryPath = Join-Path $ArtifactsDir "registry\error-code-registry.json"
if (!(Test-Path -LiteralPath $registryPath)) {
    throw "error-code registry artifact not found: $registryPath"
}

$artifact = (Get-Content -LiteralPath $registryPath -Raw) | ConvertFrom-Json
if ($null -eq $artifact.codes) {
    throw "error-code-registry.json missing top-level 'codes' array"
}

$codes = @($artifact.codes | ForEach-Object { [string]$_.code })

function ConvertTo-ConstName {
    param([string]$Code)
    "ERROR_CODE_" + ($Code.ToUpperInvariant() -replace '[.\-]', '_')
}

$entries = New-Object System.Collections.Generic.List[object]
$seen = @{}
foreach ($code in $codes) {
    $name = ConvertTo-ConstName -Code $code
    if ($seen.ContainsKey($name)) {
        throw "error-code constant collision: '$name' from both '$($seen[$name])' and '$code'"
    }
    $seen[$name] = $code
    $entries.Add([PSCustomObject]@{ Name = $name; Code = $code }) | Out-Null
}

$dq = [char]34
$lines = New-Object System.Collections.Generic.List[string]
function Add-Line { param([string]$s) $script:lines.Add($s) | Out-Null }

Add-Line '// @generated by tools/generate-sdk-error-codes.ps1 from'
Add-Line '// cokret-spec/spec/v1/artifacts/registry/error-code-registry.json; do not edit by hand.'
Add-Line '//'
Add-Line '// One constant per canonical top-level error code. The failed_precondition'
Add-Line '// sub-reasons live in reasons.rs as REASON_* constants; they are NOT top-level'
Add-Line '// wire codes and must never be declared here as ERROR_CODE_*.'
Add-Line ''
foreach ($e in $entries) {
    $value = $dq + $e.Code + $dq
    $head = 'pub const ' + $e.Name + ': &str = '
    $decl = $head + $value + ';'
    if ($decl.Length -le 100) {
        Add-Line $decl
    } else {
        Add-Line ($head.TrimEnd())
        Add-Line ('    ' + $value + ';')
    }
}
Add-Line ''
Add-Line '/// Canonical top-level error codes from error-code-registry.json, in registry order.'
Add-Line 'pub const KNOWN_ERROR_CODES: &[&str] = &['
foreach ($e in $entries) {
    Add-Line ('    ' + $e.Name + ',')
}
Add-Line '];'

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline
Write-Host "Wrote $OutputPath ($($entries.Count) error codes)"
