param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\arkret-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\generated\event_kinds.rs")
)

# Emits crates/core/src/generated/event_kinds.rs from
# arkret-spec/spec/v1/artifacts/registry/event-kind-registry.json.
#
# Outputs the strongly-typed `EventKind` enum: one PascalCase variant per
# active `ak.*` kind in the registry, plus an `Unknown(String)` catch-all that
# carries any other wire string verbatim for forward compatibility (an older
# build deserialising a newer ak.* kind keeps the bytes instead of failing the
# parse; the spec's "unknown standard kind is schema_violation" rule is enforced
# at the validation layer, not at deserialisation).

$registryPath = Join-Path $ArtifactsDir "registry\event-kind-registry.json"
if (!(Test-Path -LiteralPath $registryPath)) {
    throw "event-kind registry artifact not found: $registryPath"
}

$artifact = (Get-Content -LiteralPath $registryPath -Raw) | ConvertFrom-Json
if ($null -eq $artifact.event_kinds) {
    throw "event-kind-registry.json missing top-level 'event_kinds' array"
}

function ConvertTo-Variant {
    param([string]$Kind)
    $body = $Kind -replace '^ak\.', ''
    $segs = $body -split '[._]'
    ($segs | ForEach-Object {
        if ($_.Length -eq 0) { '' } else { $_.Substring(0, 1).ToUpper() + $_.Substring(1) }
    }) -join ''
}

# Active kinds only, sorted by wire string in .NET Ordinal order so match arms
# and the variant list are deterministic and byte-ordered.
$kinds = @($artifact.event_kinds | Where-Object { $_.status -eq 'active' } | ForEach-Object { [string]$_.event_kind })
$arr = $kinds
[System.Array]::Sort($arr, [System.StringComparer]::Ordinal)

$entries = New-Object System.Collections.Generic.List[object]
$seenVariants = @{}
foreach ($k in $arr) {
    $variant = ConvertTo-Variant -Kind $k
    if ($seenVariants.ContainsKey($variant)) {
        throw "event-kind variant collision: '$variant' produced by both '$($seenVariants[$variant])' and '$k'"
    }
    $seenVariants[$variant] = $k
    $entries.Add([PSCustomObject]@{ Kind = $k; Variant = $variant }) | Out-Null
}

$lines = New-Object System.Collections.Generic.List[string]
$add = { param($s) $lines.Add($s) | Out-Null }

& $add "//! Generated strongly-typed Arkret event-kind enum."
& $add "//!"
& $add "//! @generated by tools/generate-sdk-event-kinds.ps1 from"
& $add "//! arkret-spec/spec/v1/artifacts/registry/event-kind-registry.json; do not edit by hand."
& $add ""
& $add "use serde::{Deserialize, Deserializer, Serialize, Serializer};"
& $add ""
& $add "use crate::events::kinds::{"
& $add "    EventClass, EventWireScope, classify_event_kind, event_wire_scope,"
& $add "    is_reducer_input_event_kind,"
& $add "};"
& $add ""
& $add '/// Count of standard `ak.*` event kinds the registry declares active.'
& $add "/// Excludes the [`EventKind::Unknown`] catch-all."
& $add "pub const EVENT_KIND_COUNT: usize = $($entries.Count);"
& $add ""
& $add '/// Strongly-typed Arkret event kind. One variant per active `ak.*` kind in'
& $add "/// ``event-kind-registry.json``, plus [`EventKind::Unknown`] which preserves"
& $add "/// any other wire string verbatim for forward compatibility."
& $add "///"
& $add "/// Serialises / deserialises as the bare wire string. Deserialising an"
& $add "/// unrecognised kind yields [`EventKind::Unknown`] rather than an error;"
& $add "/// rejecting unknown standard kinds is the validation layer's job."
& $add "///"
& $add "/// ``#[non_exhaustive]``: the registry gains kinds as the spec evolves and this"
& $add "/// enum is regenerated to match; downstream ``match`` expressions MUST carry a"
& $add "/// ``_`` arm with fail-closed semantics."
& $add "#[derive(Clone, Debug, PartialEq, Eq, Hash)]"
& $add "#[non_exhaustive]"
& $add "pub enum EventKind {"
foreach ($e in $entries) {
    & $add "    /// ``$($e.Kind)``"
    & $add "    $($e.Variant),"
}
& $add "    /// Forward-compatibility catch-all for any kind not in the registry at"
& $add "    /// build time. Carries the raw wire string."
& $add "    Unknown(String),"
& $add "}"
& $add ""
& $add "impl EventKind {"
& $add "    /// Canonical wire-form string for this kind."
& $add "    pub fn as_str(&self) -> &str {"
& $add "        match self {"
foreach ($e in $entries) {
    & $add "            Self::$($e.Variant) => `"$($e.Kind)`","
}
& $add "            Self::Unknown(raw) => raw.as_str(),"
& $add "        }"
& $add "    }"
& $add ""
& $add "    /// Parse a wire string into an [`EventKind`]. Unrecognised kinds become"
& $add "    /// [`EventKind::Unknown`] (forward compatible)."
& $add "    pub fn from_wire(value: &str) -> Self {"
& $add "        match value {"
foreach ($e in $entries) {
    & $add "            `"$($e.Kind)`" => Self::$($e.Variant),"
}
& $add "            _ => Self::Unknown(value.to_owned()),"
& $add "        }"
& $add "    }"
& $add ""
& $add "    /// Parse a wire string, returning `None` for any kind not declared in the"
& $add "    /// registry (vendor / unknown). Mirrors the previous wrapper semantics."
& $add "    pub fn try_new(value: &str) -> Option<Self> {"
& $add "        match Self::from_wire(value) {"
& $add "            Self::Unknown(_) => None,"
& $add "            known => Some(known),"
& $add "        }"
& $add "    }"
& $add ""
& $add "    /// Construct from one of the `pub const *: &str` declarations in"
& $add "    /// [`crate::events::kinds`]. Same membership check as [`Self::try_new`]."
& $add "    pub fn from_const(value: &'static str) -> Option<Self> {"
& $add "        Self::try_new(value)"
& $add "    }"
& $add ""
& $add '    /// `true` for any registry-declared kind; `false` for [`Self::Unknown`].'
& $add "    pub fn is_standard(&self) -> bool {"
& $add "        !matches!(self, Self::Unknown(_))"
& $add "    }"
& $add ""
& $add "    /// Broad class for routing / indexing."
& $add "    pub fn class(&self) -> EventClass {"
& $add "        classify_event_kind(self.as_str())"
& $add "    }"
& $add ""
& $add "    /// Wire scope (durable / actor-private / ephemeral)."
& $add "    pub fn wire_scope(&self) -> EventWireScope {"
& $add "        event_wire_scope(self.as_str())"
& $add "    }"
& $add ""
& $add "    /// Whether this kind is a reducer-input durable event."
& $add "    pub fn is_reducer_input(&self) -> bool {"
& $add "        is_reducer_input_event_kind(self.as_str())"
& $add "    }"
& $add "}"
& $add ""
& $add "impl std::fmt::Display for EventKind {"
& $add "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {"
& $add "        f.write_str(self.as_str())"
& $add "    }"
& $add "}"
& $add ""
& $add "impl AsRef<str> for EventKind {"
& $add "    fn as_ref(&self) -> &str {"
& $add "        self.as_str()"
& $add "    }"
& $add "}"
& $add ""
& $add "impl std::str::FromStr for EventKind {"
& $add "    type Err = std::convert::Infallible;"
& $add ""
& $add "    fn from_str(value: &str) -> Result<Self, Self::Err> {"
& $add "        Ok(Self::from_wire(value))"
& $add "    }"
& $add "}"
& $add ""
& $add "impl From<&str> for EventKind {"
& $add "    fn from(value: &str) -> Self {"
& $add "        Self::from_wire(value)"
& $add "    }"
& $add "}"
& $add ""
& $add "impl From<String> for EventKind {"
& $add "    fn from(value: String) -> Self {"
& $add "        Self::from_wire(&value)"
& $add "    }"
& $add "}"
& $add ""
& $add "impl From<&String> for EventKind {"
& $add "    fn from(value: &String) -> Self {"
& $add "        Self::from_wire(value)"
& $add "    }"
& $add "}"
& $add ""
& $add "impl PartialEq<str> for EventKind {"
& $add "    fn eq(&self, other: &str) -> bool {"
& $add "        self.as_str() == other"
& $add "    }"
& $add "}"
& $add ""
& $add "impl PartialEq<&str> for EventKind {"
& $add "    fn eq(&self, other: &&str) -> bool {"
& $add "        self.as_str() == *other"
& $add "    }"
& $add "}"
& $add ""
& $add "impl PartialEq<String> for EventKind {"
& $add "    fn eq(&self, other: &String) -> bool {"
& $add "        self.as_str() == other.as_str()"
& $add "    }"
& $add "}"
& $add ""
& $add "impl PartialEq<EventKind> for str {"
& $add "    fn eq(&self, other: &EventKind) -> bool {"
& $add "        self == other.as_str()"
& $add "    }"
& $add "}"
& $add ""
& $add "impl Serialize for EventKind {"
& $add "    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {"
& $add "        serializer.serialize_str(self.as_str())"
& $add "    }"
& $add "}"
& $add ""
& $add "impl<'de> Deserialize<'de> for EventKind {"
& $add "    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {"
& $add "        let raw = String::deserialize(deserializer)?;"
& $add "        Ok(Self::from_wire(&raw))"
& $add "    }"
& $add "}"

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline
& rustfmt +nightly --edition 2024 $OutputPath
if ($LASTEXITCODE -ne 0) { throw "rustfmt failed for $OutputPath" }
Write-Host "Wrote $OutputPath ($($entries.Count) variants)"
