#!/usr/bin/env python3
"""Generate the executable cell-family state-model bindings from the spec registry."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


STATE_MODEL_VARIANTS = {
    "causal_register": "CausalRegister",
    "or_set": "OrSet",
    "ordered_log": "OrderedLog",
    "counter": "Counter",
    "sequenced_state": "SequencedState",
}

BOTTOM_VARIANTS = {
    "reject": "Reject",
    "expose": "Expose",
    "inert": "Inert",
}


def cell_family_constant(family: str) -> str:
    body = family.removeprefix("ak.component.")
    return re.sub(r"[^A-Za-z0-9]+", "_", body).upper()


def collect_bindings(
    registry: dict,
) -> dict[str, tuple[str, str, str, str | None]]:
    event_kinds = registry.get("event_kinds")
    if not isinstance(event_kinds, list):
        raise ValueError("event-kind registry must contain an event_kinds array")

    bindings: dict[str, tuple[str, str, str, str | None]] = {}
    for event in event_kinds:
        if not isinstance(event, dict):
            raise ValueError("event-kind registry entries must be objects")
        if event.get("status") != "active":
            continue
        raw_writes = event.get("cell_writes")
        if raw_writes is not None and not isinstance(raw_writes, list):
            raise ValueError(
                f"{event.get('event_kind')} has a non-array cell_writes member"
            )
        writes = list(raw_writes or [])
        for write in writes:
            if not isinstance(write, dict):
                raise ValueError(
                    f"{event.get('event_kind')} has a non-object cell write"
                )
            family = write.get("cell_family")
            state_model = write.get("state_model")
            execution = write.get("execution")
            value_shape = write.get("value_shape")
            bottom = write.get("bottom")
            if family is None and state_model is None and execution is None:
                # Dynamic writes carry a full cell_ref in the payload and
                # resolve through the target family's separately registered binding.
                continue
            if not all(
                isinstance(value, str)
                for value in (family, state_model, execution, value_shape)
            ):
                raise ValueError(
                    f"{event.get('event_kind')} has an incomplete cell state-model binding"
                )
            if execution == "security" and state_model != "sequenced_state":
                raise ValueError(f"{family} security write must use sequenced_state")
            if execution == "security" and bottom is not None:
                raise ValueError(f"{family} security write must not declare bottom")
            if execution == "data" and state_model == "sequenced_state":
                raise ValueError(f"{family} data write cannot use sequenced_state")
            if execution == "data" and bottom not in BOTTOM_VARIANTS:
                raise ValueError(f"{family} data write must declare a supported bottom")
            binding = (execution, state_model, value_shape, bottom)
            previous = bindings.setdefault(family, binding)
            if previous != binding:
                raise ValueError(
                    f"{family} has conflicting bindings: {previous} and {binding}"
                )
    return bindings


def render(source_path: Path, registry: dict) -> str:
    source_digest = hashlib.sha256(source_path.read_bytes()).hexdigest()
    bindings = collect_bindings(registry)
    rows = []
    for family, (execution, state_model, value_shape, bottom) in sorted(bindings.items()):
        try:
            state_model_variant = STATE_MODEL_VARIANTS[state_model]
        except KeyError as error:
            raise ValueError(f"unsupported registry value: {error.args[0]}") from error
        execution_variant = execution.title()
        value_shape_variant = value_shape.title()
        bottom_value = (
            f"Some(EventCellBottom::{BOTTOM_VARIANTS[bottom]})"
            if bottom is not None
            else "None"
        )
        family_constant = cell_family_constant(family)
        rows.extend(
            [
                "    (",
                f"        CellFamilyId::{family_constant},",
                f"        EventCellExecution::{execution_variant},",
                f"        StateModelKind::{state_model_variant},",
                f"        EventCellValueShape::{value_shape_variant},",
                f"        {bottom_value},",
                "    ),",
            ]
        )
    return "\n".join(
        [
            "// @generated by tools/generate-sdk-state-model-bindings.py; do not edit.",
            f"// Source sha256: {source_digest}",
            "",
            "use arkret_state::state_model::StateModelKind;",
            "use arkret_wire::{CellFamilyId, EventCellBottom, EventCellExecution, EventCellValueShape};",
            "",
            "pub(crate) const SPEC_STATE_MODEL_BINDINGS: &[(&str, EventCellExecution, StateModelKind, EventCellValueShape, Option<EventCellBottom>)] = &[",
            *rows,
            "];",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifacts-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    source_path = args.artifacts_dir / "registry" / "event-kind-registry.json"
    registry = json.loads(source_path.read_text(encoding="utf-8"))
    output = render(source_path, registry)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output} ({len(collect_bindings(registry))} bindings)")


if __name__ == "__main__":
    main()
