param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\arkret-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\error\codes.rs"),
    [string]$ReasonOutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\error\reasons.rs")
)

# Emits crates/core/src/error/codes.rs from
# arkret-spec/spec/v1/artifacts/registry/error-code-registry.json.
#
# One `pub const ERROR_CODE_<UPPER>: &str = "<code>"` per top-level `codes`
# entry (canonical wire error codes), in registry order, plus the
# `KNOWN_ERROR_CODES` slice listing every constant in the same order.
#
# The top-level `codes` and subordinate `reason_codes` arrays are emitted into
# separate modules so callers cannot accidentally use a reason as a top-level
# wire error code. Both generated surfaces are exact registry mirrors.

$registryPath = Join-Path $ArtifactsDir "registry\error-code-registry.json"
if (!(Test-Path -LiteralPath $registryPath)) {
    throw "error-code registry artifact not found: $registryPath"
}

$artifact = (Get-Content -LiteralPath $registryPath -Raw) | ConvertFrom-Json
if ($null -eq $artifact.codes) {
    throw "error-code-registry.json missing top-level 'codes' array"
}
if ($null -eq $artifact.reason_codes) {
    throw "error-code-registry.json missing top-level 'reason_codes' array"
}

$codes = @($artifact.codes | ForEach-Object { [string]$_.code })
$reasons = @($artifact.reason_codes | ForEach-Object { [string]$_.code })

function ConvertTo-ConstName {
    param([string]$Code)
    "ERROR_CODE_" + ($Code.ToUpperInvariant() -replace '[.\-]', '_')
}

function ConvertTo-ReasonConstName {
    param([string]$Code)
    "REASON_" + ($Code.ToUpperInvariant() -replace '[.\-]', '_')
}

$entries = New-Object System.Collections.Generic.List[object]
$seen = @{}
foreach ($code in $codes) {
    $name = ConvertTo-ConstName -Code $code
    if ($seen.ContainsKey($name)) {
        throw "error-code constant collision: '$name' from both '$($seen[$name])' and '$code'"
    }
    $seen[$name] = $code
    $entries.Add([PSCustomObject]@{ Name = $name; Code = $code }) | Out-Null
}

$reasonEntries = New-Object System.Collections.Generic.List[object]
$seenReasons = @{}
foreach ($code in $reasons) {
    $name = ConvertTo-ReasonConstName -Code $code
    if ($seenReasons.ContainsKey($name)) {
        throw "reason-code constant collision: '$name' from both '$($seenReasons[$name])' and '$code'"
    }
    $seenReasons[$name] = $code
    $reasonEntries.Add([PSCustomObject]@{ Name = $name; Code = $code }) | Out-Null
}

$dq = [char]34
$lines = New-Object System.Collections.Generic.List[string]
function Add-Line { param([string]$s) $script:lines.Add($s) | Out-Null }

Add-Line '// @generated by tools/generate-sdk-error-codes.ps1 from'
Add-Line '// arkret-spec/spec/v1/artifacts/registry/error-code-registry.json; do not edit by hand.'
Add-Line '//'
Add-Line '// One constant per canonical top-level error code. The failed_precondition'
Add-Line '// sub-reasons live in reasons.rs as REASON_* constants; they are NOT top-level'
Add-Line '// wire codes and must never be declared here as ERROR_CODE_*.'
Add-Line ''
foreach ($e in $entries) {
    $value = $dq + $e.Code + $dq
    $head = 'pub const ' + $e.Name + ': &str = '
    $decl = $head + $value + ';'
    if ($decl.Length -le 100) {
        Add-Line $decl
    } else {
        Add-Line ($head.TrimEnd())
        Add-Line ('    ' + $value + ';')
    }
}
Add-Line ''
Add-Line '/// Canonical top-level error codes from error-code-registry.json, in registry order.'
Add-Line 'pub const KNOWN_ERROR_CODES: &[&str] = &['
foreach ($e in $entries) {
    Add-Line ('    ' + $e.Name + ',')
}
Add-Line '];'

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline

$reasonLines = New-Object System.Collections.Generic.List[string]
function Add-Reason-Line { param([string]$s) $script:reasonLines.Add($s) | Out-Null }

Add-Reason-Line '// @generated by tools/generate-sdk-error-codes.ps1 from'
Add-Reason-Line '// arkret-spec/spec/v1/artifacts/registry/error-code-registry.json; do not edit by hand.'
Add-Reason-Line '//'
Add-Reason-Line '// One constant per canonical reason_codes entry. These are subordinate reason'
Add-Reason-Line '// values, not top-level service error codes.'
Add-Reason-Line ''
foreach ($e in $reasonEntries) {
    $value = $dq + $e.Code + $dq
    $head = 'pub const ' + $e.Name + ': &str = '
    $decl = $head + $value + ';'
    if ($decl.Length -le 100) {
        Add-Reason-Line $decl
    } else {
        Add-Reason-Line ($head.TrimEnd())
        Add-Reason-Line ('    ' + $value + ';')
    }
}
Add-Reason-Line ''
Add-Reason-Line '/// Canonical subordinate reason codes from error-code-registry.json, in registry order.'
Add-Reason-Line 'pub const KNOWN_REASON_CODES: &[&str] = &['
foreach ($e in $reasonEntries) {
    Add-Reason-Line ('    ' + $e.Name + ',')
}
Add-Reason-Line '];'

Set-Content -LiteralPath $ReasonOutputPath -Value ($reasonLines -join [Environment]::NewLine) -NoNewline
& rustfmt +nightly --edition 2024 $OutputPath $ReasonOutputPath
if ($LASTEXITCODE -ne 0) { throw "rustfmt failed for generated error registries" }
Write-Host "Wrote $OutputPath ($($entries.Count) error codes)"
Write-Host "Wrote $ReasonOutputPath ($($reasonEntries.Count) reason codes)"
