param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\contrix-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\generated\profiles.rs")
)

# Emits crates/core/src/generated/profiles.rs from
# contrix-spec/spec/v1/artifacts/profiles/conformance-profiles.json.
#
# Outputs:
#   * `PROFILE_IDS`             — sorted byte-ordered slice of every declared
#                                 profile id.
#   * `is_profile_id`           — membership helper.
#   * `ProfileRole`             — enum mirroring the spec layer's
#                                 `profile_roles` value set
#                                 (`client` / `server` / `gateway` /
#                                 `directory` / `admin` / `interop`).
#   * `PROFILE_ROLES`           — sorted `(profile_id, ProfileRole)` table.
#   * `profile_role`            — lookup helper.
#   * `profile_ids_with_role`   — reverse lookup.

$profilesPath = Join-Path $ArtifactsDir "profiles\conformance-profiles.json"
if (!(Test-Path -LiteralPath $profilesPath)) {
    throw "conformance profile artifact not found: $profilesPath"
}

$raw = Get-Content -LiteralPath $profilesPath -Raw
$artifact = $raw | ConvertFrom-Json

function Sort-Ordinal {
    # Use .NET StringComparer.Ordinal so the generated arrays sort by raw
    # byte order — matching Rust's `str::cmp` (which `binary_search_by` over
    # `PROFILE_ROLES` relies on). PowerShell's default `Sort-Object` uses
    # culture-sensitive comparison and treats `_` < `.`, which is the
    # opposite of byte order.
    param([string[]]$Values)
    if ($null -eq $Values -or $Values.Count -eq 0) { return ,@() }
    $list = [System.Collections.Generic.List[string]]::new()
    foreach ($v in $Values) { [void]$list.Add([string]$v) }
    $arr = $list.ToArray()
    [System.Array]::Sort($arr, [System.StringComparer]::Ordinal)
    $deduped = [System.Collections.Generic.List[string]]::new()
    foreach ($v in $arr) {
        if ($deduped.Count -eq 0 -or $deduped[$deduped.Count - 1] -cne $v) {
            [void]$deduped.Add($v)
        }
    }
    return ,$deduped.ToArray()
}

# Collect ids from a regex pass first, so we still notice ids that are
# referenced without a profile_roles entry (e.g. transitional candidates).
$idsFromRegex = Sort-Ordinal -Values @([regex]::Matches($raw, 'cx\.profile\.[A-Za-z0-9_.-]+\.v[0-9]+') |
    ForEach-Object { $_.Value })

if ($null -eq $artifact.profile_roles) {
    throw "conformance profile artifact missing top-level 'profile_roles' object"
}

$rolesObject = $artifact.profile_roles
$roleById = @{}
foreach ($prop in $rolesObject.PSObject.Properties) {
    $roleById[$prop.Name] = [string]$prop.Value
}
$sortedRoleIds = Sort-Ordinal -Values @($roleById.Keys)
$rolesEntries = @($sortedRoleIds | ForEach-Object {
    [PSCustomObject]@{ Id = $_; Role = $roleById[$_] }
})

# Validate role values against the documented enum.
$allowedRoles = @('client', 'server', 'gateway', 'directory', 'admin', 'interop')
foreach ($entry in $rolesEntries) {
    if ($allowedRoles -notcontains $entry.Role) {
        throw "profile $($entry.Id) has unsupported role $($entry.Role); allowed: $($allowedRoles -join ',')"
    }
}

# Every id in profile_roles MUST appear in the regex-derived id list (sanity
# check: keeps generator from accepting roles for ids that aren't declared
# anywhere else in the artifact).
foreach ($entry in $rolesEntries) {
    if ($idsFromRegex -notcontains $entry.Id) {
        throw "profile_roles references id $($entry.Id) which is not present in the artifact body"
    }
}

function ConvertTo-RoleVariant {
    param([string]$Role)
    switch ($Role) {
        'client'    { 'Client' }
        'server'    { 'Server' }
        'gateway'   { 'Gateway' }
        'directory' { 'Directory' }
        'admin'     { 'Admin' }
        'interop'   { 'Interop' }
        default     { throw "unsupported role $Role" }
    }
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("//! Generated conformance profile identifiers and role table.") | Out-Null
$lines.Add("//!") | Out-Null
$lines.Add("//! @generated by tools/generate-sdk-profile-constants.ps1 from") | Out-Null
$lines.Add("//! contrix-spec/spec/v1/artifacts/profiles/conformance-profiles.json; do not edit by hand.") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("pub const PROFILE_IDS: &[&str] = &[") | Out-Null
foreach ($id in $idsFromRegex) {
    $lines.Add("    `"$id`",") | Out-Null
}
$lines.Add("];") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("pub fn is_profile_id(value: &str) -> bool {") | Out-Null
$lines.Add("    PROFILE_IDS.contains(&value)") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Spec-layer `profile_roles` enum: every declared profile id is partitioned') | Out-Null
$lines.Add('/// into exactly one of these roles. SDK manifests, client-side feature') | Out-Null
$lines.Add('/// negotiation, and conformance loaders MUST consult this table before') | Out-Null
$lines.Add('/// claiming a profile as locally implemented.') | Out-Null
$lines.Add("#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]") | Out-Null
$lines.Add("pub enum ProfileRole {") | Out-Null
$lines.Add("    Client,") | Out-Null
$lines.Add("    Server,") | Out-Null
$lines.Add("    Gateway,") | Out-Null
$lines.Add("    Directory,") | Out-Null
$lines.Add("    Admin,") | Out-Null
$lines.Add("    Interop,") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("impl ProfileRole {") | Out-Null
$lines.Add("    pub fn as_str(self) -> &'static str {") | Out-Null
$lines.Add("        match self {") | Out-Null
$lines.Add("            Self::Client => `"client`",") | Out-Null
$lines.Add("            Self::Server => `"server`",") | Out-Null
$lines.Add("            Self::Gateway => `"gateway`",") | Out-Null
$lines.Add("            Self::Directory => `"directory`",") | Out-Null
$lines.Add("            Self::Admin => `"admin`",") | Out-Null
$lines.Add("            Self::Interop => `"interop`",") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("") | Out-Null
$lines.Add("    pub fn from_str(value: &str) -> Option<Self> {") | Out-Null
$lines.Add("        match value {") | Out-Null
$lines.Add("            `"client`" => Some(Self::Client),") | Out-Null
$lines.Add("            `"server`" => Some(Self::Server),") | Out-Null
$lines.Add("            `"gateway`" => Some(Self::Gateway),") | Out-Null
$lines.Add("            `"directory`" => Some(Self::Directory),") | Out-Null
$lines.Add("            `"admin`" => Some(Self::Admin),") | Out-Null
$lines.Add("            `"interop`" => Some(Self::Interop),") | Out-Null
$lines.Add("            _ => None,") | Out-Null
$lines.Add("        }") | Out-Null
$lines.Add("    }") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Sorted `(profile_id, ProfileRole)` table mirroring') | Out-Null
$lines.Add('/// `conformance-profiles.json#/profile_roles`. The order matches Rust''s') | Out-Null
$lines.Add('/// byte-ordered `str::cmp` so binary search is valid.') | Out-Null
$lines.Add("pub const PROFILE_ROLES: &[(&str, ProfileRole)] = &[") | Out-Null
foreach ($entry in $rolesEntries) {
    $variant = ConvertTo-RoleVariant -Role $entry.Role
    $lines.Add("    (`"$($entry.Id)`", ProfileRole::$variant),") | Out-Null
}
$lines.Add("];") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Returns the spec-declared role for `profile_id`, if any.') | Out-Null
$lines.Add("pub fn profile_role(profile_id: &str) -> Option<ProfileRole> {") | Out-Null
$lines.Add("    PROFILE_ROLES") | Out-Null
$lines.Add("        .binary_search_by(|(id, _)| (*id).cmp(profile_id))") | Out-Null
$lines.Add("        .ok()") | Out-Null
$lines.Add("        .map(|index| PROFILE_ROLES[index].1)") | Out-Null
$lines.Add("}") | Out-Null
$lines.Add("") | Out-Null
$lines.Add('/// Returns every profile id whose spec role is `role`, in sorted order.') | Out-Null
$lines.Add("pub fn profile_ids_with_role(role: ProfileRole) -> Vec<&'static str> {") | Out-Null
$lines.Add("    PROFILE_ROLES") | Out-Null
$lines.Add("        .iter()") | Out-Null
$lines.Add("        .filter(|(_, r)| *r == role)") | Out-Null
$lines.Add("        .map(|(id, _)| *id)") | Out-Null
$lines.Add("        .collect()") | Out-Null
$lines.Add("}") | Out-Null

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline
Write-Host "Wrote $OutputPath ($($idsFromRegex.Count) ids, $($rolesEntries.Count) roles)"
