param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\contrix-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\core\src\generated\profiles.rs")
)

$profilesPath = Join-Path $ArtifactsDir "profiles\conformance-profiles.json"
if (!(Test-Path -LiteralPath $profilesPath)) {
    throw "conformance profile artifact not found: $profilesPath"
}

$raw = Get-Content -LiteralPath $profilesPath -Raw
$ids = [regex]::Matches($raw, 'cx\.profile\.[A-Za-z0-9_.-]+\.v[0-9]+') |
    ForEach-Object { $_.Value } |
    Sort-Object -Unique

$lines = @()
$lines += "//! Generated conformance profile identifiers."
$lines += "//!"
$lines += "//! @generated by tools/generate-sdk-profile-constants.ps1 from"
$lines += "//! contrix-spec/spec/v1/artifacts/profiles/conformance-profiles.json; do not edit by hand."
$lines += ""
$lines += "pub const PROFILE_IDS: &[&str] = &["
foreach ($id in $ids) {
    $lines += "    `"$id`","
}
$lines += "];"
$lines += ""
$lines += "pub fn is_profile_id(value: &str) -> bool {"
$lines += "    PROFILE_IDS.contains(&value)"
$lines += "}"

Set-Content -LiteralPath $OutputPath -Value ($lines -join [Environment]::NewLine) -NoNewline
