param(
    [string]$ArtifactsDir = (Join-Path $PSScriptRoot "..\..\arkret-spec\spec\v1\artifacts"),
    [string]$OutputPath = (Join-Path $PSScriptRoot "..\crates\wire\src\generated\event_kinds.rs")
)

. (Join-Path $PSScriptRoot 'utf8-byte-order.ps1')

# Emits the clean-break Event kind surface. Ordering, finality and projection
# state no longer live in the producer Event, so only intrinsic Event metadata
# is projected into the SDK catalog.
$registryPath = Join-Path $ArtifactsDir "registry\event-kind-registry.json"
if (!(Test-Path -LiteralPath $registryPath)) {
    throw "event-kind registry artifact not found: $registryPath"
}

$artifact = Get-Content -LiteralPath $registryPath -Raw | ConvertFrom-Json
$digest = (Get-FileHash -LiteralPath $registryPath -Algorithm SHA256).Hash.ToLowerInvariant()
if ($null -eq $artifact.event_kinds) {
    throw "event-kind-registry.json missing top-level 'event_kinds' array"
}

function ConvertTo-Variant {
    param([string]$Value, [string]$Prefix = '')
    $body = if ($Prefix -and $Value.StartsWith($Prefix)) { $Value.Substring($Prefix.Length) } else { $Value }
    (($body -split '[^A-Za-z0-9]+' | ForEach-Object {
        if ($_.Length -eq 0) { '' } else { $_.Substring(0, 1).ToUpper() + $_.Substring(1) }
    }) -join '')
}

function ConvertTo-AssociatedName {
    param([string]$Kind)
    (($Kind -replace '^ak\.', '') -replace '[^A-Za-z0-9]+', '_').ToUpperInvariant()
}

function ConvertTo-OptionString {
    param($Value)
    if ($null -eq $Value) { return 'None' }
    'Some(' + ([string]$Value | ConvertTo-Json -Compress) + ')'
}

$rowsByKind = @{}
foreach ($row in $artifact.event_kinds) {
    if ([string]$row.status -ne 'active') { continue }
    $kind = [string]$row.event_kind
    if ($rowsByKind.ContainsKey($kind)) { throw "duplicate active Event kind: $kind" }
    $rowsByKind[$kind] = $row
}
$kinds = Sort-Utf8ByteLexicographic -Values @($rowsByKind.Keys | ForEach-Object { [string]$_ })
$entries = @($kinds | ForEach-Object {
    $row = $rowsByKind[$_]
    $wireScope = switch ([string]$row.wire_scope) {
        'durable_event' { 'DurableEvent' }
        'actor_private_event' { 'ActorPrivateEvent' }
        'ephemeral_event' { 'EphemeralEvent' }
        default { throw "unsupported event wire scope: $($row.wire_scope)" }
    }
    [PSCustomObject]@{
        Kind = $_
        Variant = ConvertTo-Variant -Value $_ -Prefix 'ak.'
        AssociatedName = ConvertTo-AssociatedName -Kind $_
        Category = ConvertTo-Variant -Value ([string]$row.category)
        WireScope = $wireScope
        Admission = ConvertTo-OptionString -Value $row.admission
        PayloadSchemaRef = ConvertTo-OptionString -Value $row.payload_schema_ref
    }
})

$variantOwners = @{}
foreach ($entry in $entries) {
    if ($variantOwners.ContainsKey($entry.Variant)) {
        throw "event-kind variant collision: '$($entry.Variant)' produced by '$($variantOwners[$entry.Variant])' and '$($entry.Kind)'"
    }
    $variantOwners[$entry.Variant] = $entry.Kind
}
$categories = Sort-Utf8ByteLexicographic -Values @($artifact.event_kinds | Where-Object { $_.status -eq 'active' } | ForEach-Object { [string]$_.category })

$lines = [System.Collections.Generic.List[string]]::new()
function Add-Line { param([string]$Line = '') $lines.Add($Line) | Out-Null }

Add-Line '//! Generated strongly-typed Arkret Event kind catalog.'
Add-Line '//!'
Add-Line '//! @generated by tools/generate-sdk-event-kinds.ps1 from'
Add-Line '//! arkret-spec/spec/v1/artifacts/registry/event-kind-registry.json; do not edit by hand.'
Add-Line "//! Input version: $($artifact.version); sha256=$digest; active=$($entries.Count)."
Add-Line
Add-Line 'use serde::{Deserialize, Deserializer, Serialize, Serializer};'
Add-Line
Add-Line 'use crate::events::kinds::{EventProductClass, event_product_class, event_wire_scope};'
Add-Line
Add-Line '/// Count of active standard `ak.*` Event kinds.'
Add-Line "pub const EVENT_KIND_COUNT: usize = $($entries.Count);"
Add-Line '/// SHA-256 of the exact Event kind registry used to generate this module.'
Add-Line "pub const EVENT_KIND_REGISTRY_SHA256: &str = `"$digest`";"
Add-Line
Add-Line '#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]'
Add-Line 'pub enum EventRegistryCategory {'
foreach ($category in $categories) { Add-Line "    $(ConvertTo-Variant -Value $category)," }
Add-Line '}'
Add-Line
Add-Line '/// Producer Event transport scope. Commit stream placement is carried by RealmCommit.'
Add-Line '#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]'
Add-Line 'pub enum EventWireScope {'
Add-Line '    DurableEvent,'
Add-Line '    ActorPrivateEvent,'
Add-Line '    EphemeralEvent,'
Add-Line '    Custom,'
Add-Line '}'
Add-Line
Add-Line '/// Registry metadata that is intrinsic to the producer Event.'
Add-Line '#[derive(Clone, Copy, Debug, PartialEq, Eq)]'
Add-Line 'pub struct EventKindDescriptor {'
Add-Line "    pub kind: &'static str,"
Add-Line '    pub category: EventRegistryCategory,'
Add-Line '    pub wire_scope: EventWireScope,'
Add-Line "    pub admission: Option<&'static str>,"
Add-Line "    pub payload_schema_ref: Option<&'static str>,"
Add-Line '}'
Add-Line
Add-Line '/// Canonical wire strings for active standard Event kinds.'
Add-Line 'pub mod event_kind_str {'
foreach ($entry in $entries) { Add-Line "    pub const $($entry.AssociatedName): &'static str = `"$($entry.Kind)`";" }
Add-Line '}'
Add-Line
Add-Line '/// Strongly typed Event kind with a forward-compatible unknown case.'
Add-Line '#[derive(Clone, Debug, PartialEq, Eq, Hash)]'
Add-Line '#[non_exhaustive]'
Add-Line 'pub enum EventKind {'
foreach ($entry in $entries) {
    Add-Line "    /// ``$($entry.Kind)``"
    Add-Line "    $($entry.Variant),"
}
Add-Line '    Unknown(String),'
Add-Line '}'
Add-Line
Add-Line 'impl EventKind {'
Add-Line "    pub const ALL: &'static [Self] = &["
foreach ($entry in $entries) { Add-Line "        Self::$($entry.Variant)," }
Add-Line '    ];'
Add-Line
Add-Line '    pub const fn as_str(&self) -> &str {'
Add-Line '        match self {'
foreach ($entry in $entries) { Add-Line "            Self::$($entry.Variant) => event_kind_str::$($entry.AssociatedName)," }
Add-Line '            Self::Unknown(raw) => raw.as_str(),'
Add-Line '        }'
Add-Line '    }'
Add-Line
Add-Line '    pub fn from_wire(value: &str) -> Self {'
Add-Line '        match value {'
foreach ($entry in $entries) { Add-Line "            event_kind_str::$($entry.AssociatedName) => Self::$($entry.Variant)," }
Add-Line '            _ => Self::Unknown(value.to_owned()),'
Add-Line '        }'
Add-Line '    }'
Add-Line
Add-Line '    pub fn try_new(value: &str) -> Option<Self> {'
Add-Line '        match Self::from_wire(value) {'
Add-Line '            Self::Unknown(_) => None,'
Add-Line '            known => Some(known),'
Add-Line '        }'
Add-Line '    }'
Add-Line
Add-Line '    pub fn is_standard(&self) -> bool { self.descriptor().is_some() }'
Add-Line
Add-Line "    pub fn descriptor(&self) -> Option<&'static EventKindDescriptor> {"
Add-Line '        EVENT_KIND_DESCRIPTORS'
Add-Line '            .binary_search_by_key(&self.as_str(), |descriptor| descriptor.kind)'
Add-Line '            .ok()'
Add-Line '            .map(|index| &EVENT_KIND_DESCRIPTORS[index])'
Add-Line '    }'
Add-Line
Add-Line '    pub fn registry_category(&self) -> Option<EventRegistryCategory> {'
Add-Line '        self.descriptor().map(|descriptor| descriptor.category)'
Add-Line '    }'
Add-Line
Add-Line '    pub fn product_class(&self) -> EventProductClass { event_product_class(self) }'
Add-Line
Add-Line '    pub fn wire_scope(&self) -> EventWireScope {'
Add-Line '        self.descriptor()'
Add-Line '            .map(|descriptor| descriptor.wire_scope)'
Add-Line '            .unwrap_or_else(|| event_wire_scope(self.as_str()))'
Add-Line '    }'
Add-Line '}'
Add-Line
Add-Line 'impl std::fmt::Display for EventKind {'
Add-Line "    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result { f.write_str(self.as_str()) }"
Add-Line '}'
Add-Line
Add-Line 'impl AsRef<str> for EventKind { fn as_ref(&self) -> &str { self.as_str() } }'
Add-Line 'impl std::str::FromStr for EventKind {'
Add-Line '    type Err = std::convert::Infallible;'
Add-Line '    fn from_str(value: &str) -> Result<Self, Self::Err> { Ok(Self::from_wire(value)) }'
Add-Line '}'
Add-Line 'impl From<&str> for EventKind { fn from(value: &str) -> Self { Self::from_wire(value) } }'
Add-Line 'impl From<String> for EventKind { fn from(value: String) -> Self { Self::from_wire(&value) } }'
Add-Line 'impl From<&String> for EventKind { fn from(value: &String) -> Self { Self::from_wire(value) } }'
Add-Line 'impl PartialEq<str> for EventKind { fn eq(&self, other: &str) -> bool { self.as_str() == other } }'
Add-Line 'impl PartialEq<&str> for EventKind { fn eq(&self, other: &&str) -> bool { self.as_str() == *other } }'
Add-Line 'impl PartialEq<String> for EventKind { fn eq(&self, other: &String) -> bool { self.as_str() == other.as_str() } }'
Add-Line 'impl PartialEq<EventKind> for str { fn eq(&self, other: &EventKind) -> bool { self == other.as_str() } }'
Add-Line
Add-Line 'impl Serialize for EventKind {'
Add-Line '    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {'
Add-Line '        serializer.serialize_str(self.as_str())'
Add-Line '    }'
Add-Line '}'
Add-Line "impl<'de> Deserialize<'de> for EventKind {"
Add-Line "    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {"
Add-Line '        let raw = String::deserialize(deserializer)?;'
Add-Line '        Ok(Self::from_wire(&raw))'
Add-Line '    }'
Add-Line '}'
Add-Line
Add-Line 'pub mod event_spec {'
Add-Line '    use super::{EventKind, event_kind_str};'
foreach ($entry in $entries) {
    Add-Line '    #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]'
    Add-Line "    pub struct $($entry.Variant);"
    Add-Line "    impl $($entry.Variant) {"
    Add-Line "        pub const KIND: EventKind = EventKind::$($entry.Variant);"
    Add-Line "        pub const KIND_STR: &'static str = event_kind_str::$($entry.AssociatedName);"
    Add-Line '    }'
}
Add-Line '}'
Add-Line
Add-Line 'pub const REGISTERED_EVENT_KINDS: &[EventKind] = &['
foreach ($entry in $entries) { Add-Line "    EventKind::$($entry.Variant)," }
Add-Line '];'
Add-Line
Add-Line 'pub const REGISTERED_EVENT_KIND_WIRE_VALUES: &[&str] = &['
foreach ($entry in $entries) { Add-Line "    event_kind_str::$($entry.AssociatedName)," }
Add-Line '];'
Add-Line
Add-Line 'pub const EVENT_KIND_DESCRIPTORS: &[EventKindDescriptor] = &['
foreach ($entry in $entries) {
    Add-Line '    EventKindDescriptor {'
    Add-Line "        kind: event_kind_str::$($entry.AssociatedName),"
    Add-Line "        category: EventRegistryCategory::$($entry.Category),"
    Add-Line "        wire_scope: EventWireScope::$($entry.WireScope),"
    Add-Line "        admission: $($entry.Admission),"
    Add-Line "        payload_schema_ref: $($entry.PayloadSchemaRef),"
    Add-Line '    },'
}
Add-Line '];'
Add-Line
Add-Line '#[cfg(test)]'
Add-Line 'mod tests {'
Add-Line '    use super::*;'
Add-Line '    #[test]'
Add-Line '    fn every_standard_kind_resolves_through_the_sorted_descriptor_table() {'
Add-Line '        assert!(EVENT_KIND_DESCRIPTORS.windows(2).all(|pair| pair[0].kind < pair[1].kind));'
Add-Line '        for kind in EventKind::ALL {'
Add-Line '            assert_eq!(kind.descriptor().map(|descriptor| descriptor.kind), Some(kind.as_str()));'
Add-Line '        }'
Add-Line '    }'
Add-Line '}'

$generatedSource = $lines -join [Environment]::NewLine
foreach ($entry in $entries) {
    $quotedKind = '"' + $entry.Kind + '"'
    $literalCount = [regex]::Matches($generatedSource, [regex]::Escape($quotedKind)).Count
    if ($literalCount -ne 1) {
        throw "generated Event kind literal $quotedKind must occur exactly once, found $literalCount"
    }
}

Set-Content -LiteralPath $OutputPath -Value $generatedSource -NoNewline
& rustfmt +nightly --edition 2024 $OutputPath
if ($LASTEXITCODE -ne 0) { throw "rustfmt failed for $OutputPath" }
Write-Host "Wrote $OutputPath ($($entries.Count) variants)"
