#!/usr/bin/env python3
"""Generate the closed MLS security-frontier registry surface."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


def cell_family_constant(family: str) -> str:
    body = family.removeprefix("ak.component.")
    return re.sub(r"[^A-Za-z0-9]+", "_", body).upper()


def load_contract(source_path: Path) -> tuple[str, list[str], str]:
    registry = json.loads(source_path.read_text(encoding="utf-8"))
    profile_id = registry.get("profile_id")
    rules = registry.get("cell_rules")
    if not isinstance(profile_id, str) or not profile_id:
        raise ValueError("MLS security-frontier registry requires profile_id")
    if not isinstance(rules, list) or not rules:
        raise ValueError("MLS security-frontier registry requires cell_rules")
    families: list[str] = []
    for rule in rules:
        if not isinstance(rule, dict) or not isinstance(rule.get("cell_family"), str):
            raise ValueError("MLS security-frontier cell rules require cell_family")
        families.append(rule["cell_family"])
    families = sorted(set(families), key=lambda value: value.encode("utf-8"))
    canonical = json.dumps(
        registry, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    registry_digest = f"sha256:{hashlib.sha256(canonical).hexdigest()}"
    return profile_id, families, registry_digest


def render(source_path: Path) -> str:
    profile_id, families, registry_digest = load_contract(source_path)
    source_digest = hashlib.sha256(source_path.read_bytes()).hexdigest()
    rows = [f"    CellFamilyId::{cell_family_constant(family)}," for family in families]
    return "\n".join(
        [
            "// @generated by tools/generate-mls-security-frontier.py; do not edit.",
            f"// Source sha256: {source_digest}",
            "",
            "use arkret_wire::CellFamilyId;",
            "",
            f'pub(crate) const MLS_SECURITY_FRONTIER_PROFILE_ID: &str = "{profile_id}";',
            f'pub(crate) const MLS_SECURITY_FRONTIER_REGISTRY_DIGEST: &str = "{registry_digest}";',
            "pub(crate) const MLS_SECURITY_FRONTIER_CELL_FAMILIES: &[&str] = &[",
            *rows,
            "];",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifacts-dir", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()
    source_path = args.artifacts_dir / "registry" / "mls-security-frontier-registry.json"
    output = render(source_path)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    _, families, _ = load_contract(source_path)
    print(f"Wrote {args.output} ({len(families)} frontier families)")


if __name__ == "__main__":
    main()
