use std::path::{Path, PathBuf};

use contrix_core::Result;
use serde_json::{Value, json};

use crate::registry::service_routes;

const SPEC_OPENAPI_RELATIVE_PATH: &str = "openapi/contrix-service-api.openapi.yaml";

/// Load the canonical OpenAPI document generated by `contrix-spec`.
///
/// The service OpenAPI surface is owned by
/// `spec/v1/artifacts/openapi/contrix-service-api.openapi.yaml`. This helper
/// keeps the SDK from maintaining a second hand-written OpenAPI truth. When a
/// source checkout is unavailable, it returns a tiny registry-derived fallback
/// that preserves operation IDs for tooling but intentionally omits schemas,
/// examples and error definitions.
pub fn openapi_document() -> Value {
    match openapi_document_from_default_spec_artifacts() {
        Ok(Some(document)) => document,
        Ok(None) => catalog_fallback_openapi_document(),
        Err(error) => panic!("failed to load Contrix spec OpenAPI artifact: {error}"),
    }
}

pub fn openapi_document_from_default_spec_artifacts() -> Result<Option<Value>> {
    let Some(artifacts_dir) = contrix_core::schema::default_spec_artifacts_dir() else {
        return Ok(None);
    };
    Ok(Some(openapi_document_from_spec_artifacts(artifacts_dir)?))
}

pub fn openapi_document_from_spec_artifacts(artifacts_dir: impl AsRef<Path>) -> Result<Value> {
    let path = artifacts_dir.as_ref().join(SPEC_OPENAPI_RELATIVE_PATH);
    let text = std::fs::read_to_string(&path).map_err(|error| {
        contrix_core::Error::Protocol(format!(
            "failed to read OpenAPI artifact {}: {error}",
            path.display()
        ))
    })?;
    let mut document: Value = serde_norway::from_str(&text).map_err(|error| {
        contrix_core::Error::Protocol(format!(
            "failed to parse OpenAPI artifact {}: {error}",
            path.display()
        ))
    })?;
    annotate_artifact_source(&mut document, &path);
    Ok(document)
}

fn annotate_artifact_source(document: &mut Value, path: &Path) {
    let Some(object) = document.as_object_mut() else {
        return;
    };
    object.insert("x-contrix-source".to_owned(), Value::String("spec-artifact".to_owned()));
    object.insert("x-contrix-source-path".to_owned(), Value::String(path.display().to_string()));
}

fn catalog_fallback_openapi_document() -> Value {
    let mut paths = serde_json::Map::new();
    for endpoint in service_routes() {
        let mut methods = paths
            .remove(endpoint.path)
            .and_then(|value| value.as_object().cloned())
            .unwrap_or_default();
        methods.insert(
            endpoint.method.to_owned(),
            json!({
                "operationId": endpoint.operation_id,
                "x-contrix-source": "server-registry-fallback"
            }),
        );
        paths.insert(endpoint.path.to_owned(), Value::Object(methods));
    }

    json!({
        "openapi": "3.1.0",
        "info": {
            "title": "Contrix Service API",
            "version": contrix_core::PROTOCOL_VERSION
        },
        "x-contrix-source": "server-registry-fallback",
        "paths": paths,
        "components": {
            "schemas": {},
            "responses": {},
            "securitySchemes": {}
        }
    })
}

pub fn default_spec_openapi_path() -> Option<PathBuf> {
    contrix_core::schema::default_spec_artifacts_dir()
        .map(|artifacts_dir| artifacts_dir.join(SPEC_OPENAPI_RELATIVE_PATH))
}
