use super::*;

#[derive(Clone, Debug)]
pub enum ServerReqBody {
    ServerDescribe,
    IdentityDescribe,
    IdentityResolve(IdentityResolveReqBody),
    IdentityDocument { did: String, version: Option<String> },
    IdentityLog { did: String, cursor: Option<String>, limit: Option<u32> },
    IdentitySubmitDidOperation(SubmitDidOperationReqBody),
    IdentityReceipts { did: String, head: String },
    Sync(SyncReqBody),
    SyncDescribe,
    AccountCursorRevoke(AccountCursorRevokeReqBody),
    SyncBackfill { space_id: String, cursor: Option<String>, limit: Option<u32> },
    SyncSnapshotHead { space_id: String },
    FederationTransaction { txn_id: String, request: FederationTransactionReqBody },
    FederationPushOperations(FederationPushOperationsReqBody),
    FederationPullOperations { space_id: String, after_cursor: Option<String>, limit: Option<u32> },
    FederationSpaceMembers { space_id: String, cursor: Option<String>, limit: Option<u32> },
    FederationVerifyActor(FederationVerifyActorReqBody),
    DirectoryDescribe,
    DirectorySearchRealms(DirectorySearchRealmsReqBody),
    DirectoryResolveRealm(DirectoryResolveRealmReqBody),
    DirectorySearchOrganizations(DirectorySearchOrganizationsReqBody),
    DirectoryResolveOrganization(DirectoryResolveOrganizationReqBody),
    DirectorySearchActors(DirectorySearchActorsReqBody),
    DirectorySearchUsers(DirectorySearchUsersReqBody),
    DirectoryResolveHandle(DirectoryResolveHandleReqBody),
    BlobUpload { metadata: BlobUploadMetadata, bytes: Option<Vec<u8>> },
    BlobHead { blob_ref: String },
    BlobGet { blob_ref: String, range: Option<String> },
    PushRegisterDevice(PushRegisterDeviceReqBody),
    PushUnregisterDevice(PushUnregisterDeviceReqBody),
    PushNotify(PushNotifyReqBody),
    DeviceMessagesPut { txn_id: String, request: DeviceMessagesSendReqBody },
    DeviceMessagesGet { from: Option<String>, limit: Option<u32> },
    KeysUpload(KeysUploadReqBody),
    KeysQuery(KeysQueryReqBody),
    KeysClaim(KeysClaimReqBody),
    AuthzEffectiveGrants { space_id: String, subject: String, at: Option<String> },
    AuthzInvites { subject: String, space_id: Option<String>, cursor: Option<String> },
    AuthzCheck(AuthzCheckReqBody),
    PolicyCheck(PolicyCheckReqBody),
    MediaIceConfig(MediaIceConfigReqBody),
    ModerationReport(ModerationReportReqBody),
    AppletPing,
    AppletDescribe,
    AppletTransaction { txn_id: String, request: AppletTransactionReqBody },
    AppletActor { actor_id: String },
    AppletRealm { realm_id_or_alias: String },
    AppletProtocol { protocol: String },
    AppletThirdPartyUsers,
    AppletThirdPartyLocations,
}

#[derive(Clone, Debug)]
pub enum ServerResBody {
    ServerDescription(ServerDescription),
    IdentityDescription(IdentityDescription),
    IdentityResolve(IdentityResolveResBody),
    IdentityDocument(IdentityDocumentResBody),
    IdentityLog(IdentityLogResBody),
    SubmitDidOperation(SubmitDidOperationResBody),
    IdentityReceipts(IdentityReceiptsResBody),
    Sync(SyncResBody),
    SyncDescription(SyncDescription),
    AccountCursorRevoke(AccountCursorRevokeResBody),
    SyncBackfill(SyncBackfillResBody),
    SyncSnapshotHead(SyncSnapshotHeadResBody),
    FederationTransaction(FederationTransactionResBody),
    FederationPushOperations(FederationPushOperationsResBody),
    FederationPullOperations(FederationPullOperationsResBody),
    FederationSpaceMembers(FederationSpaceMembersResBody),
    FederationVerifyActor(FederationVerifyActorResBody),
    DirectoryDescription(DirectoryDescription),
    DirectorySearchRealms(DirectorySearchRealmsResBody),
    DirectoryResolveRealm(DirectoryResolveRealmResBody),
    DirectorySearchOrganizations(DirectorySearchOrganizationsResBody),
    DirectoryResolveOrganization(DirectoryResolveOrganizationResBody),
    DirectorySearchActors(DirectorySearchActorsResBody),
    DirectorySearchUsers(DirectorySearchUsersResBody),
    DirectoryResolveHandle(DirectoryResolveHandleResBody),
    BlobUpload(BlobUploadResBody),
    BlobHead(BlobMetadata),
    BlobBytes(Vec<u8>),
    PushRegisterDevice(PushRegisterDeviceResBody),
    Ok(OkResBody),
    PushNotify(PushNotifyResBody),
    DeviceMessagesSend(DeviceMessagesSendResBody),
    DeviceMessagesReceive(DeviceMessagesReceiveResBody),
    KeysUpload(KeysUploadResBody),
    KeysQuery(KeysQueryResBody),
    KeysClaim(KeysClaimResBody),
    EffectiveGrants(EffectiveGrantsResBody),
    AuthzInvites(AuthzInvitesResBody),
    AuthzCheck(AuthzCheckResBody),
    PolicyCheck(PolicyCheckResBody),
    MediaIceConfig(MediaIceConfigResBody),
    ModerationReport(ModerationReportResBody),
    AppletPing(AppletPingResBody),
    AppletDescription(AppletDescription),
    AppletTransaction(AppletTransactionResBody),
    AppletActor(AppletActorResBody),
    AppletRealm(AppletRealmResBody),
    AppletProtocol(AppletProtocolResBody),
    AppletThirdPartyUsers(Value),
    AppletThirdPartyLocations(Value),
}

pub trait EndpointHandler {
    fn handle(&mut self, request: ServerReqBody) -> Result<ServerResBody>;
}
