use super::*;

#[derive(Clone, Debug)]
pub enum ServerReqBody {
    ServerDescribe,
    IdentityDescribe,
    IdentityResolve(IdentityResolveReqBody),
    IdentityDocument { did: String, version: Option<String> },
    IdentityLog { did: String, cursor: Option<String>, limit: Option<u32> },
    IdentitySubmitDidOperation(SubmitDidOperationReqBody),
    IdentityReceipts { did: String, head: String },
    Sync(SyncReqBody),
    SyncDescribe,
    SyncBackfill { space_id: String, cursor: Option<String>, limit: Option<u32> },
    SyncSnapshotHead { space_id: String },
    FederationTransaction { txn_id: String, request: FederationTransactionReqBody },
    FederationPushOperations(FederationPushOperationsReqBody),
    FederationPullOperations { space_id: String, after_cursor: Option<String>, limit: Option<u32> },
    FederationSpaceMembers { space_id: String, cursor: Option<String>, limit: Option<u32> },
    FederationVerifyActor(FederationVerifyActorReqBody),
    DirectoryDescribe,
    DirectorySearchSpaces(DirectorySearchSpacesReqBody),
    DirectoryResolveSpace(DirectoryResolveSpaceReqBody),
    DirectorySearchOrganizations(DirectorySearchOrganizationsReqBody),
    DirectoryResolveOrganization(DirectoryResolveOrganizationReqBody),
    DirectorySearchActors(DirectorySearchActorsReqBody),
    DirectorySearchUsers(DirectorySearchUsersReqBody),
    DirectoryResolveHandle(DirectoryResolveHandleReqBody),
    BlobUpload { metadata: BlobUploadMetadata, bytes: Option<Vec<u8>> },
    BlobHead { blob_ref: String },
    BlobGet { blob_ref: String, range: Option<String> },
    PushRegisterDevice(PushRegisterDeviceReqBody),
    PushUnregisterDevice(PushUnregisterDeviceReqBody),
    PushNotify(PushNotifyReqBody),
    DeviceMessagesPut { txn_id: String, request: DeviceMessagesSendReqBody },
    DeviceMessagesGet { from: Option<String>, limit: Option<u32> },
    KeysUpload(KeysUploadReqBody),
    KeysQuery(KeysQueryReqBody),
    KeysClaim(KeysClaimReqBody),
    AuthzEffectiveGrants { space_id: String, subject: String, at: Option<String> },
    AuthzInvites { subject: String, space_id: Option<String>, cursor: Option<String> },
    AuthzCheck(AuthzCheckReqBody),
    PolicyCheck(PolicyCheckReqBody),
    MediaIceConfig(MediaIceConfigReqBody),
    ModerationReport(ModerationReportReqBody),
    AppletPing,
    AppletDescribe,
    AppletTransaction { txn_id: String, request: AppletTransactionReqBody },
    AppletActor { actor_id: String },
    AppletSpace { space_id_or_alias: String },
    AppletProtocol { protocol: String },
    AppletThirdPartyUsers,
    AppletThirdPartyLocations,
}

#[derive(Clone, Debug)]
pub enum ServerOutput {
    ServerDescription(ServerDescription),
    IdentityDescription(IdentityDescription),
    IdentityResolve(IdentityResolveOutput),
    IdentityDocument(IdentityDocumentOutput),
    IdentityLog(IdentityLogOutput),
    SubmitDidOperation(SubmitDidOperationOutput),
    IdentityReceipts(IdentityReceiptsOutput),
    Sync(SyncOutput),
    SyncDescription(SyncDescription),
    SyncBackfill(SyncBackfillOutput),
    SyncSnapshotHead(SyncSnapshotHeadOutput),
    FederationTransaction(FederationTransactionOutput),
    FederationPushOperations(FederationPushOperationsOutput),
    FederationPullOperations(FederationPullOperationsOutput),
    FederationSpaceMembers(FederationSpaceMembersOutput),
    FederationVerifyActor(FederationVerifyActorOutput),
    DirectoryDescription(DirectoryDescription),
    DirectorySearchSpaces(DirectorySearchSpacesOutput),
    DirectoryResolveSpace(DirectoryResolveSpaceOutput),
    DirectorySearchOrganizations(DirectorySearchOrganizationsOutput),
    DirectoryResolveOrganization(DirectoryResolveOrganizationOutput),
    DirectorySearchActors(DirectorySearchActorsOutput),
    DirectorySearchUsers(DirectorySearchUsersOutput),
    DirectoryResolveHandle(DirectoryResolveHandleOutput),
    BlobUpload(BlobUploadOutput),
    BlobHead(BlobMetadata),
    BlobBytes(Vec<u8>),
    PushRegisterDevice(PushRegisterDeviceOutput),
    Ok(OkOutput),
    PushNotify(PushNotifyOutput),
    DeviceMessagesSend(DeviceMessagesSendOutput),
    DeviceMessagesReceive(DeviceMessagesReceiveOutput),
    KeysUpload(KeysUploadOutput),
    KeysQuery(KeysQueryOutput),
    KeysClaim(KeysClaimOutput),
    EffectiveGrants(EffectiveGrantsOutput),
    AuthzInvites(AuthzInvitesOutput),
    AuthzCheck(AuthzCheckOutput),
    PolicyCheck(PolicyCheckOutput),
    MediaIceConfig(MediaIceConfigOutput),
    ModerationReport(ModerationReportOutput),
    AppletPing(AppletPingOutput),
    AppletDescription(AppletDescription),
    AppletTransaction(AppletTransactionOutput),
    AppletActor(AppletActorOutput),
    AppletSpace(AppletSpaceOutput),
    AppletProtocol(AppletProtocolOutput),
    AppletThirdPartyUsers(Value),
    AppletThirdPartyLocations(Value),
}

pub trait EndpointHandler {
    fn handle(&mut self, request: ServerReqBody) -> Result<ServerOutput>;
}
