use super::*;

#[derive(Clone, Debug)]
pub enum ServerRequest {
    ServerDescribe,
    IdentityDescribe,
    IdentityResolve(IdentityResolveRequest),
    IdentityDocument { did: String, version: Option<String> },
    IdentityLog { did: String, cursor: Option<String>, limit: Option<u32> },
    IdentitySubmitDidOperation(SubmitDidOperationRequest),
    IdentityReceipts { did: String, head: String },
    Sync(SyncRequest),
    SyncDescribe,
    SyncBackfill { space_id: String, cursor: Option<String>, limit: Option<u32> },
    SyncSnapshotHead { space_id: String },
    FederationTransaction { txn_id: String, request: FederationTransactionRequest },
    FederationPushOperations(FederationPushOperationsRequest),
    FederationPullOperations { space_id: String, after_cursor: Option<String>, limit: Option<u32> },
    FederationSpaceMembers { space_id: String, cursor: Option<String>, limit: Option<u32> },
    FederationVerifyActor(FederationVerifyActorRequest),
    DirectoryDescribe,
    DirectorySearchSpaces(DirectorySearchSpacesRequest),
    DirectoryResolveSpace(DirectoryResolveSpaceRequest),
    DirectorySearchOrganizations(DirectorySearchOrganizationsRequest),
    DirectoryResolveOrganization(DirectoryResolveOrganizationRequest),
    DirectorySearchActors(DirectorySearchActorsRequest),
    DirectorySearchUsers { q: String, space_id: Option<String>, limit: Option<u32> },
    DirectoryResolveHandle(DirectoryResolveHandleRequest),
    BlobUpload { metadata: BlobUploadMetadata, bytes: Option<Vec<u8>> },
    BlobHead { blob_ref: String },
    BlobGet { blob_ref: String, range: Option<String> },
    PushRegisterDevice(PushRegisterDeviceRequest),
    PushUnregisterDevice(PushUnregisterDeviceRequest),
    PushNotify(PushNotifyRequest),
    DeviceMessagesPut { txn_id: String, request: DeviceMessagesSendRequest },
    DeviceMessagesGet { from: Option<String>, limit: Option<u32> },
    KeysUpload(KeysUploadRequest),
    KeysQuery(KeysQueryRequest),
    KeysClaim(KeysClaimRequest),
    AuthzEffectiveGrants { space_id: String, subject: String, at: Option<String> },
    AuthzInvites { subject: String, space_id: Option<String>, cursor: Option<String> },
    AuthzCheck(AuthzCheckRequest),
    PolicyCheck(PolicyCheckRequest),
    MediaIceConfig(MediaIceConfigRequest),
    ModerationReport(ModerationReportRequest),
    AppletPing,
    AppletDescribe,
    AppletTransaction { txn_id: String, request: AppletTransactionRequest },
    AppletActor { actor_id: String },
    AppletSpace { space_id_or_alias: String },
    AppletProtocol { protocol: String },
    AppletThirdPartyUsers,
    AppletThirdPartyLocations,
}

#[derive(Clone, Debug)]
pub enum ServerResponse {
    ServerDescription(ServerDescription),
    IdentityDescription(IdentityDescription),
    IdentityResolve(IdentityResolveResponse),
    IdentityDocument(IdentityDocumentResponse),
    IdentityLog(IdentityLogResponse),
    SubmitDidOperation(SubmitDidOperationResponse),
    IdentityReceipts(IdentityReceiptsResponse),
    Sync(SyncResponse),
    SyncDescription(SyncDescription),
    SyncBackfill(SyncBackfillResponse),
    SyncSnapshotHead(SyncSnapshotHeadResponse),
    FederationTransaction(FederationTransactionResponse),
    FederationPushOperations(FederationPushOperationsResponse),
    FederationPullOperations(FederationPullOperationsResponse),
    FederationSpaceMembers(FederationSpaceMembersResponse),
    FederationVerifyActor(FederationVerifyActorResponse),
    DirectoryDescription(DirectoryDescription),
    DirectorySearchSpaces(DirectorySearchSpacesResponse),
    DirectoryResolveSpace(DirectoryResolveSpaceResponse),
    DirectorySearchOrganizations(DirectorySearchOrganizationsResponse),
    DirectoryResolveOrganization(DirectoryResolveOrganizationResponse),
    DirectorySearchActors(DirectorySearchActorsResponse),
    DirectorySearchUsers(DirectorySearchUsersResponse),
    DirectoryResolveHandle(DirectoryResolveHandleResponse),
    BlobUpload(BlobUploadResponse),
    BlobHead(BlobMetadata),
    BlobBytes(Vec<u8>),
    PushRegisterDevice(PushRegisterDeviceResponse),
    Ok(OkResponse),
    PushNotify(PushNotifyResponse),
    DeviceMessagesSend(DeviceMessagesSendResponse),
    DeviceMessagesReceive(DeviceMessagesReceiveResponse),
    KeysUpload(KeysUploadResponse),
    KeysQuery(KeysQueryResponse),
    KeysClaim(KeysClaimResponse),
    EffectiveGrants(EffectiveGrantsResponse),
    AuthzInvites(AuthzInvitesResponse),
    AuthzCheck(AuthzCheckResponse),
    PolicyCheck(PolicyCheckResponse),
    MediaIceConfig(MediaIceConfigResponse),
    ModerationReport(ModerationReportResponse),
    AppletPing(AppletPingResponse),
    AppletDescription(AppletDescription),
    AppletTransaction(AppletTransactionResponse),
    AppletActor(AppletActorResponse),
    AppletSpace(AppletSpaceResponse),
    AppletProtocol(AppletProtocolResponse),
    AppletThirdPartyUsers(Value),
    AppletThirdPartyLocations(Value),
}

pub trait EndpointHandler {
    fn handle(&mut self, request: ServerRequest) -> Result<ServerResponse>;
}
